### PR TITLE
[Ready to review] Documentation for online Collaboration Cafes in autumn 2019

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Doesn't close an open issue

First draft of project management documentation explaining proposed online Collaboration Cafes in autumn 2019.

### List of changes proposed in this PR (pull-request)

* Description, dates and times for online collaboration events in autumn 2019

### What should a reviewer concentrate their feedback on?

- [ ] Does the documentation make sense? What's missing?
- [ ] Any other suggestions?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by pherterich** [comment]
Currently on a phone, so this might not be the most structured feedback but is there still a photo from our pomodoro session back in January? I just think some examples of tasks to achieve in 25 minutes would be cool as I think a lot of people at the book dash struggled with that and only the super determined ones will attend (also one of the things I struggle with at the Mozilla Global Sprint is figuring out what to contribute when only having a bit of time). Plus would be nice to re-iterate the book dash point that we're happy to teach you GitHub in a break out one to one of you need that to get started but maybe I'm too tired and that is in there and brain just didn't notice.

**Comment by pherterich** [comment]
Also, as easy as it is for you guys to do this at the Turing, it would be cool to keep this "all online" to create a level playing field.

**Comment by KirstieJane** [comment]
> Also, as easy as it is for you guys to do this at the Turing, it would be cool to keep this "all online" to create a level playing field.

This is a SUPER interesting point. One of my goals is to get more contributions from within the Turing (there are relatively few in the book so far) so I’d quite like to incentivise getting folks in a room together. There are almost no spaces to take a call at the Turing (mutter mutter open plan mutter mutter).

Your point is really important though. I wonder if having folks in a room together but all connected to zoom w headphones would work??

**Comment by KirstieJane** [comment]
> Currently on a phone, so this might not be the most structured feedback but is there still a photo from our pomodoro session back in January? I just think some examples of tasks to achieve in 25 minutes would be cool as I think a lot of people at the book dash struggled with that and only the super determined ones will attend (also one of the things I struggle with at the Mozilla Global Sprint is figuring out what to contribute when only having a bit of time). Plus would be nice to re-iterate the book dash point that we're happy to teach you GitHub in a break out one to one of you need that to get started but maybe I'm too tired and that is in there and brain just didn't notice.

Yep - I’m tired and so I figured I’d push it and get external feedback on what’s missing. A list of types of contributions to do in 20 mins is great. And DEFINITELY hand holding through first PRs needs to be explicitly listed.

Folks - please comment with ideas for short, good first contributions. It’s weirdly difficult for me to name them (because I keep saying “everything” 🤦‍♀)

**Comment by malvikasharan** [comment]
I agree with both of your points. I think it will make sense to have a 'todo' page - or several todo pages sorted by level of urgency or tagged with some categories such as TEXT (typo, grammar, format), TECH (config, CI, programming related content/example), FEEDBACK (a part or complete chapter that needs multiple eyes on them). This sounds like an idea for the first cafe.

**Comment by rosiehigman** [comment]
I really like this idea, only thing I would add is that it would be useful to make it clear that you don't have to attend all of them (if I've understood the idea correctly). Obviously there are benefits to the project if people do attend regularly but it's better to drop in occasionally than not at all.

I like @malvikasharan idea of categories, could we also try to tag things by (roughly!) how many poms it might take to complete? E.g. re-format prerequisites for each chapter could be tagged with TEXT 🍅 🍅. This would help people take on realistic amounts in the time they have.

**Comment by rainsworth** [comment]
> Folks - please comment with ideas for short, good first contributions. It’s weirdly difficult for me to name them (because I keep saying “everything” 🤦‍♀)

Could having them fill out the [Google Form](https://docs.google.com/forms/d/e/1FAIpQLSfcyYH_E03Y5zuBdwrikQP4QldqzKmD-aPngCKthdV9e9alaA/viewform) be a short, good first contribution? Or ask folks if they want to share their experience with one of the chapter topics? It would be nice to have more personal experiences throughout the book like in the [FAIR data section](https://the-turing-way.netlify.com/rdm/rdm.html#susanna-assunta-sansone-from-fair-co-author-to-fair-doer).

**Comment by KirstieJane** [comment]
Thank you so much everyone! @rainsworth I've added a few bullet points about good first contributions at the very end including the form. I'm going to merge this now because I want to work on a newsletter to let folks know that they're happening. We can absolutely fix forwards as we go.

I really appreciate all the thoughts! Thank you 🙏 💖 🙌

**Pull request merged**
