### PR TITLE
[Ready for review] Improve open data chapter, links to rdm (see #835)

### LINKED ISSUE #835: Mention FAIR data principles in open research / open data
### Summary

*I think it would make sense to mention the FAIR principles in the open data section.*
https://www.go-fair.org/fair-principles/

### What needs to be done?

- [ ] Add text on FAIR principles to open data section in open research chapter
- [ ] Optional: Add visualisation on FAIR principles to open data section in open research chapter

### Who can help?

* Anyone who knows how to contribute to a chapter

---

### Updates

*Pull request #837 *

### PR DESCRIPTION
**Pull request by HeidiSeibold**
***This pull request has been identified as suitable for review by a first time reviewer. If you don't feel confident reviewing PRs but would like to learn please ask any questions as you do your review!***
If you *are* confident reviewing pull requests please consider finding a different PR to review and leave this one for first time contributors 💖 

### Summary

Fixes #835 and adds new line after each sentence (see contributing guidelines).

### List of changes proposed in this PR (pull-request)

* Add links to RDM chapter, mention FAIR
* Add new line after each sentence

### What should a reviewer concentrate their feedback on?

- [ ] Links work?
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: HeidiSeibold

### CODE REVIEW

**Comment by KirstieJane** [comment]
I'm super confused at what's happened here - I can't see the PR review and I thought we were keeping this for a first time reviewer? Am I just missing the review from this view?

**Comment by HeidiSeibold** [comment]
Oh no, I am so sorry. When I look at it it seems like I did the merge. I wanted to merge a different PR.

**Comment by HeidiSeibold** [comment]
> the other possibility is that our branch protection was turned off! But I don't think that's the case.... 

It must have been, right? How was I able to merge? Completely my mistake!

**Comment by KirstieJane** [comment]
Super weird!! No worries - I'll keep an eye out for bugs in the branch rules just in case the settings are broken!

**Pull request merged**
