### PR TITLE
Remove redundant bit out and update README-Korean.md

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

The Korean file had contributors table that we don't want in the README translated files

### List of changes proposed in this PR (pull-request)

* Update the main README to link Korean file
* Request @rabbits99 to translate the three last lines

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@rabbits99 Can you please help translate these lines in the README-Korean file in this branch ?

```
## Contributors

Thanks goes to these wonderful people (emoji key):

List of contributors

Contributions of any kind welcome!
```

**Comment by rabbits99** [comment]
Should we have to change the file?
We just comment with translation
## Contributors

Thanks goes to these wonderful people (emoji key):
이 모든 멋진 사람들에게 감사를 표합니다:
List of contributors
기여자들 목록
Contributions of any kind welcome!
모든 종류의 기여를 환영합니다!

**Comment by malvikasharan** [comment]
Wonderful @rabbits99. 🙏🌺

**Comment by malvikasharan** [comment]
@all-contributors please add @rabbits99 for tranlation.

**Comment by malvikasharan** [comment]
@all-contributors please add @rabbits99 for translation

**Review by pherterich — APPROVED** [review]
The bit I can double check looks good - nice addition! 😮

**Comment by malvikasharan** [comment]
Thank you @pherterich 🌺

**Pull request merged**
