### PR TITLE
small edits/additions in "Reusable code" section

### PR DESCRIPTION
**Pull request by bast**
### Summary

Small edits/additions in "Reusable code" section.

### List of changes proposed in this PR (pull-request)

- Small edits for more consistency
- Added examples so that concepts like "findable in space and time" and "hardcoded bits" are more relatable. 

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.

### CODE REVIEW

**Comment by bast** [comment]
@c-martinez for info

**Comment by malvikasharan** [comment]
@bast I have just made some changes in this chapter (split them into subchapters) and included them in the _toc.yml (table of content so you can find them in the book). I can pull those changes in this PR to make sure your edits are reflected as intended.

**Comment by bast** [comment]
Sure. I can also rebase/conflict-resolve my changes on top of your changes if that helps?

**Comment by malvikasharan** [comment]
That would really helpful @bast 🙌

**Comment by bast** [comment]
I have now replayed the changes on top of latest `main`.

**Review by malvikasharan — APPROVED** [review]
Looks fantastic. Thank you @bast 🌸

**Comment by malvikasharan** [comment]
@all-contributors please add @bast for review

**Pull request merged**
