### PR TITLE
Removal of duplicate "schedule" heading

### LINKED ISSUE #2503: Remove repeated 'schedule' heading in the Weekly Coworking template
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Collaborations Workshop in October 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @BrainonSilicon or @EKaroune know on Zoom so that we can assist you.

## Summary
In the [Weekly Coworking Call Template](https://the-turing-way.netlify.app/community-handbook/templates/template-coworking-weekly.html) subchapter, under the 'Code of conduct heading there are two subheadings of 'Schedule:' when there should only be one.

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their GitHub usernames.

2. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/community-handbook/templates/template-coworking-weekly.md

3. Search for statement: 
> "Code of conduct"

4. Click 'Edit this file'.

5. Remove the second appearance of Schedule (you can remove the entire line and blank line above it, i.e. lines 29-30).

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project.

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a `#` in the description. You can find the issue number next to the title of this issue (this one of #2503).

Example: `this pull request fixes #2503`

10. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

11. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

12. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

### PR DESCRIPTION
**Pull request by BrianAndrewOneil**
this pull request fixes #2503

### CODE REVIEW

**Review by aleesteele — APPROVED** [review]
Thanks so much, @BrianAndrewOneil! Looks great 😄

**Comment by aleesteele** [comment]
Thanks so much for all your help, @BrianAndrewOneil! I've accepted your pull request, feel free to merge. :tada:

We would love if you stayed in touch with us through [Slack](https://tinyurl.com/jointuringwayslack), [Twitter](https://github.com/alan-turing-institute/the-turing-way/pull/twitter.com/turingway), or right here in the Github repo. Hope to see you in one of our community calls: [You can find more info here](https://hackmd.io/@turingway/demo-intro).

Just going to tag you with all-contributors-bot, to make sure that you're added to the [Contributors table](https://github.com/alan-turing-institute/the-turing-way#contributors). Congratulations again on making your first pull request! 💃

We hope you stay in touch with the community!

**Comment by aleesteele** [comment]
@all-contributors please add @BrianAndrewOneil for bugs

**Comment by da5nsy** [comment]
@all-contributors please add @BrianAndrewOneil for bugs

**Comment by da5nsy** [comment]
(@aleesteele - all-contributors is great but doesn't handle multiple simultaneous requests well, so deleting and re-doing)

**Review by da5nsy — APPROVED** [review]

**Pull request merged**
