### PR TITLE
Adding crowdin-contributors

### PR DESCRIPTION
**Pull request by BatoolMM**
### Summary

This PR is to add crowdin-contributors to the README file along with other contributors.

### What should a reviewer concentrate their feedback on?

- [ ] Where to add the contributors?
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by aleesteele** [comment]
Hi @BatoolMM - maybe this is something we could help to automate with the all-contributors bot. Is this something you and the team might be interested in? Because the bot automatically tallies the number of contributors from the table (which draws from a JSON file), adding them manually may break the bot. In fact, this just happened to me today! 😓

**Comment by da5nsy** [comment]
Is this superseded by #3184 ?

**Comment by RealRichi3** [comment]
> Is this superseded by #3184 ?

I think so, I'll confirm from @BatoolMM

**Comment by BatoolMM** [comment]
Thank you @RealRichi3 @aleesteele @da5nsy - YES this is no longer needed, @RealRichi3 is working on automating the process at https://github.com/alan-turing-institute/the-turing-way/pull/3184 - thank you a lot @RealRichi3!

**Pull request closed without merging**
