### PR TITLE
Enabling collaborative annotation in the book

### PR DESCRIPTION
**Pull request by BatoolMM**
### Summary

After a discussion in slack regarding the book-layout, @lauracion and @SamGuay suggested implementing [hypothes.is](https://web.hypothes.is/). I gave it a try and made minor changes in `_config.yml`. After that, I tried to build up the Jupyter book locally and it worked. It became easy to highlight any text and to add any notes in the book.

### List of changes proposed in this PR (pull-request)

* *Implementing [hypothes.is](https://web.hypothes.is/) in the TW book .*

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by BatoolMM** [comment]
For some reason, the first 6 commits from PR #1551 were copied in this PR, although they were in a different branch. I'll try to remove them. The only commit which concerns this PR is the last one `activate hypothesis in Jupyter book`.

**Comment by paulowoicho** [comment]
> For some reason, the first 6 commits from PR #1551 were copied in this PR, although they were in a different branch. I'll try to remove them. The only commit which concerns this PR is the last one `activate hypothesis in Jupyter book`.

Hi @BatoolMM, I had the same problem with my first few PRs. The best work around for me was to work from a branch off the main Turing Way repo and not from my fork of the project. Hope this helps!

**Comment by BatoolMM** [comment]
Thank you so much @paulowoicho. I'll close this PR and open a new one.

**Comment by BatoolMM** [comment]
I'll open a new PR with the same changes.

**Pull request closed without merging**
