### PR TITLE
[Don't merge] Add Binder Tech Talk to Presentations

### PR DESCRIPTION
**Pull request by sgibson91**
### Summary

This PR adds my tech talk on Binder to the presentations folder

### List of changes proposed in this PR (pull-request)

* Add `conferences/presentations/binder_techtalk.pdf`
* Update `conferences/README.md`

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

---

### Updates

Not to be merged. @KirstieJane has reformatted the slides to be smaller size and they will be added in PR #432 . This PR can be closed when that one has been merged.

### CODE REVIEW

**Comment by sgibson91** [comment]
PDF too big. Awkward 😬

**Comment by KirstieJane** [comment]
Heya! I've made a smaller version and added it to #432 ..... so once that's merged then this can close, if that's ok @sgibson91?

(I didn't see this PR before I made that one 😬)

**Comment by sgibson91** [comment]
Thank you @KirstieJane !

**Comment by sgibson91** [comment]
Closing since #432 has been merged

**Pull request closed without merging**
