### PR TITLE
Upgrade Jupyter Book / Enable collaborative annotation in the book

### PR DESCRIPTION
**Pull request by BatoolMM**
After a discussion in slack regarding the book-layout, @lauracion and @SamGuay suggested implementing [hypothes.is](https://web.hypothes.is/). I gave it a try and made changes in `_config.yml`. After that, I tried to build up the Jupyter book locally and it worked. It became easy to highlight any text and to add any notes in the book.

Screenshot 2020-11-11 at 02 10 35

### List of changes proposed in this PR (pull-request)

* *Implementing [hypothes.is](https://web.hypothes.is/) in the TW book .*

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Review by yochannah — COMMENTED** [review]
Hypothesis looks pretty neat! Either it or the newer jupyter book version seems to have applied a few changes to The Turing Way overall: 

**small sidebarr font:** I had a poke about to see why the font had gotten smaller on the deployed preview of this branch. I think something in the new styling automatically overrides the sidebar's previous styles which happens sometimes :) thankfully the css rule itself isn't a complex fix - BUT I couldn't figure out from a quick check where custom CSS for the Turing Way should go - possibly you use the defaults so there is no custom css? Once this is figured out, this rule should do the trick: 

```css
#site-navigation li > a {
  font-size: 1.1em;
}
```
**sidebar footer:** I think it might also be overriding the config for the custom sidebar footer set up here: https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/_config.yml#L33 

**colours:** The new font colour in the sidebar is slightly darker and offers higher contrast which is probably more accessible, I would suggest sticking with it 👍 

**dropdown nav arrows** The new version also has a nice expandable table of content arrow thingy that's really nice: 
image of new dropdown nav

**Comment by martinagvilas** [comment]
Thanks @yochannah ! I created a `_static` folder with a file that contains your suggestion, and it seems to work in local deployment. I will make a commit soon to show. 

And thanks for noticing about the footer in the sidebar, it seems that we need to change the `_config` file.

**Comment by BatoolMM** [comment]
Thank you so much @yochannah for the detailed explanation 👍 . I didn't realise that @martinagvilas fixed it until she mentioned it in shareout/presentation. You are awsome Martina ❤️

**Comment by malvikasharan** [comment]
@martinagvilas and @BatoolMM - Not sure what the status of this PR is, but just wanted to let you know that we are ok to merge this and then fix any styling issue that may occur. Thank you @yochannah for the detailed feedback and all of you for being so awesome. 🎊🌻🙌

**Comment by BatoolMM** [comment]
Thank you @malvikasharan, I think it can be merged but the CI might also need to be changed to test the jupyter book build in multiple OS as @martinagvilas suggested in issue #1594.

**Comment by martinagvilas** [comment]
Hey @malvikasharan I agree we can merge this and change the styling on another PR if necessary. And as @BatoolMM we can change the CI later as well 🚀

**Review by malvikasharan — APPROVED** [review]

**Comment by malvikasharan** [comment]
@BatoolMM go ahead and merge it! 👯

**Pull request merged**
