### PR TITLE
first update of glossary

### PR DESCRIPTION
**Pull request by EKaroune**
### Summary

Here is the update for the glossary to put all keywords in the afterword rather than at the end of the chapters.

Fixes #<NUM>

### List of changes proposed in this PR (pull-request)

- [x]  Take keywords from guide for reproducibility
- [x]  Take keywords from guide for Project design
- [x] Take keywords from guide for communication
- [x] Take keywords from guide for communication
- [x] Take keywords from guide for collaboration
- [x] Take keywords from guide for ethical research    
- [ ] Check keywords have been added from new chapters created in Nov 2020. 

### What should a reviewer concentrate their feedback on?

- [ ] Check formatting
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Review by paulowoicho — APPROVED** [review]
Super awesome work @EKaroune! I just updated the headers from 4 to 2 because Jupyter Book throws warnings about non-consecutive headers when trying to build the book locally

**Comment by EKaroune** [comment]
Thanks Paul. I was wondering if we could add links for letters A to Z so that users can jump to the different alphabet letters. It would be helpful to show the letters in the right side contents. Is this done by adding the letters as header 2?

**Comment by malvikasharan** [comment]
I agree on using alphabetical order! great work @EKaroune 🙏

**Comment by paulowoicho** [comment]
> Thanks Paul. I was wondering if we could add links for letters A to Z so that users can jump to the different alphabet letters. It would be helpful to show the letters in the right side contents. Is this done by adding the letters as header 2?

Yes, I agree as well. The letters will need to be a level 2 header, then the individual terms would be level 3. I will make a new commit to reflect this

**Comment by EKaroune** [comment]
That looks good now with the letters! Good job!

**Comment by EKaroune** [comment]
I've now added all keywords from the rest of the guides as they are at the moment. There were none to add from the ethical chapter at the moment but I assume the new ethical chapter will have quite a few so I will contact those authors to see if they can send me the list .

**Comment by EKaroune** [comment]
There seems to be an issue now with latin phrases but I did not use any so not sure what this is about?

**Comment by EKaroune** [comment]
I think this is ready to be added. So I will change the status to ready to merge.

**Comment by paulowoicho** [comment]
I'll go ahead and merge it now since it's approved already

**Comment by malvikasharan** [comment]
@all-contributors please add @EKaroune for content

**Comment by malvikasharan** [comment]
@all-contributors please add @EKaroune for content

**Pull request merged**
