### PR TITLE
Remove redundant dependencies

### PR DESCRIPTION
**Pull request by da5nsy**
Following up on #2313 now that #2307 (update jupyter-book version) is merged.
Partly undoes https://github.com/alan-turing-institute/the-turing-way/commit/4c59b7f6574b69d9f22ca88b21e4f83cb924d9d0

### CODE REVIEW

**Comment by sgibson91** [comment]
Hey @da5nsy - the title of this PR is "unpin Jinja", but I see we are actually completely removing it as a dependency, along with a few other packages as well. Could you clarify a bit please?

**Comment by da5nsy** [comment]
Thanks for the great question @sgibson91 and apologies for skipping that detail.

- The jinja dependency was added as a hotfix here: https://github.com/alan-turing-institute/the-turing-way/pull/2303#issuecomment-1080513443. This is no longer required following #2307.
- `sphinxcontrib-bibtex` was added to allow for a previous jupyter-book upgrade (https://github.com/alan-turing-institute/the-turing-way/pull/2039). It is a dependency of jupyter-book 0.13 ([code link](https://github.com/executablebooks/jupyter-book/blob/09193ed0b452506267f5d2b817cf482a85a1c1e9/pyproject.toml#L47)).
- `sphinx-click`, `sphinx_inline_tabs`, and `sphinxext-rediraffe` were added to fix issues that arose following that upgrade (https://github.com/alan-turing-institute/the-turing-way/pull/2055). They are dependencies of jupyter-book 0.13 ([code link](https://github.com/executablebooks/jupyter-book/blob/09193ed0b452506267f5d2b817cf482a85a1c1e9/pyproject.toml#L79), [code link](https://github.com/executablebooks/jupyter-book/blob/09193ed0b452506267f5d2b817cf482a85a1c1e9/pyproject.toml#L81), [code link](https://github.com/executablebooks/jupyter-book/blob/09193ed0b452506267f5d2b817cf482a85a1c1e9/pyproject.toml#L83)) **but** I see now that they are under `[project.optional-dependencies]`, which I hadn't noticed before, and do not understand the impact of.

**Comment by sgibson91** [comment]
> * I see now that they are under `[project.optional-dependencies]`, which I hadn't noticed before, and do not understand the impact of.

I think this means that, if we want to install those dependencies, we need to use the syntax (this will work in the requirements file as well):

```
pip install jupyter-book[something]
```

where `something` could be `optional` or `dev`.

**Comment by da5nsy** [comment]
What's your opinion on the right move forward @sgibson91?

**Review by sgibson91 — APPROVED** [review]
I think if the book builds/works fine without explicitly finding that `[something]`, then let's just merge :)

**Pull request merged**
