### PR TITLE
Update issue and pull request templates

### PR DESCRIPTION
**Pull request by KirstieJane**
I think we could make better use of the fact that html comments aren't rendered.

This pull request contains a new pull request tempate and includes my suggestions for re-formatting the issue template we have.

This is very much open for discussion! Thank you to everyone who's been using the current template, it really helps nudge folks to add the information we need 🤗

### CODE REVIEW

**Comment by pherterich** [comment]
I'm an idiot who should read the whole file, you have mentioned that - sorry. Will everyone know what "write access" means though?

**Comment by KirstieJane** [comment]
Good question @pherterich - I think most people will know....but it’s always better to be explicit and not use unnecessary jargon!  I’m not sure of a better phrasing than “write access” though... any suggestions? Very happy to adjust!

**Comment by pherterich** [comment]
Something like "If GitHub gives you the option to assign the appropriate label (or labels) to your issue, please do so. If you do not have the rights to add a label, the core team will do it for you." ?
It's not great yet, but maybe something you can work with @KirstieJane :smiley_cat:

**Comment by KirstieJane** [comment]
Hey @pherterich - I've had a think about this phrasing, but I can't think of a way that doesn't reinforce a hierarchy. The problem is that you can only assign a label if you're added as a collaborator on the project.....and we might add people quite liberally, but the first few contributions will be through a pull request (not as an internal collaborator).

Would you mind keeping the text as it is at the moment and if lots of people are confused by that part, we'll either take it out or adjust it?

**Comment by pherterich** [comment]
@KirstieJane happy to keep as is if we can't find a better phrasing. And I guess google can easily help to understand write access if somebody really wants to figure it out.

**Pull request merged**
