### PR TITLE
[WIP] Jupyterbook beta upgrade

### PR DESCRIPTION
**Pull request by martinagvilas**
### Summary
This PR updates the current jupyter-book version to the beta version outlined [here](https://jupyterbook.org/customize/config.html) as discussed in #1017. 

### List of changes proposed in this PR (pull-request)
The jupyter-book beta version changes the structure in the following way:
- The `_config` file structure changes a lot, and some of its options are still work in progress
- The `_toc` file structure also changes (notice the naming pattern differs)
- The content folder has been moved inside the website folder
- The `testing.md` file had to be changed to remove some extra spaces that made the build fail
- Unnecessary files and folders from jekyll were removed from the `website` folder

### What should a reviewer concentrate their feedback on?

- [ ] Make sure that netlify deploys correctly
- [ ] Make sure no important file has been deleted
- [ ] Detect any important issue in the rendering (but see warning below)

### Acknowledging contributors
- [X] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: 

### Warning
- If this PR is accepted, before merging we should also change the description of how contributors should build the book.
- Probably some of the CI will need to be changed to prevent errors in the jupyter-book build
- The rendering of the book will look different from the current version (e.g. no numbered chapters), and some of it will fail (e.g. some complex tables will not be rendered correctly), but as discussed with @KirstieJane these issues can be tackled separetely from this PR and would provide nice opportunities for turing-way contributors to do some upstream work in jupyter-book

### CODE REVIEW

**Comment by malvikasharan** [comment]
@martinagvilas Is this ready for review? 😱😱

**Comment by martinagvilas** [comment]
@malvikasharan almost but not yet 😆 I added the work in progress label to not generate confusion 🚀  Will ping you when I think its ready!

**Comment by malvikasharan** [comment]
Cool! That's what I thought. Thank you for your hard work on this. ❤️️

**Comment by martinagvilas** [comment]
Hey, I need some feedback @sgibson91 @malvikasharan @KirstieJane, and whoever has an opinion on this 😄. The beta version is currently working and deploying correctly in netlify. The issue now to discuss is in which cases the CI should fail with the new deployment. In the old version, `html-proof` was used to check broken links of images and internal links. If a broken link was detected, the CI failed. 

Using `html-proof` with the current build will be an overkill in my opinion, since we have to install dependencies for it that we got rid of with the new build. So I'm looking for alternatives. Jupyter-book has an option to fail the build if a warning arises (and warnings will be raised for not found internal references), but in this case we would have to correct all the current warnings (see CI build) before merging, which would mean touching a lot of content of the book. This would be the cleanest option though.

Another option is to merge this without the fail when warning option, create separate issues to fix those warnings, and then add this option to the CI. Or we could keep looking for proofing alternatives that are more selective. 

Regardless, which aspects of the build do you think are absolutely necessary to be checked (and fail if encountered?)?

**Comment by malvikasharan** [comment]
@sgibson91 and @alexmorley will you be able to advise on @martinagvilas question on proofing (external) links without html-fix?

**Comment by alexmorley** [comment]
Hey hey. We could use a github action so we don't add any dependencies to the book itself?

I'm sure someone has made one already but I don't know which ones are good. Alternatively we could make our own github action with this library (https://github.com/linkchecker/linkchecker)?

Happy to help with either.

**Comment by martinagvilas** [comment]
@alexmorley that sounds like a great idea. There is already a github action for `html-proofer` [here](https://github.com/gjtorikian/html-proofer) so I could replicate the existing CI check with that. There are also some other options like [this one](https://github.com/gaurav-nelson/github-action-markdown-link-check). I will try them and if they don't work well we can maybe create our own action. 

Thanks for the input! Can I ping you if I get stuck?

**Comment by alexmorley** [comment]
> Can I ping you if I get stuck?

4 sure. Anytime.

**Comment by martinagvilas** [comment]
@malvikasharan everything seems to be working now. I translated what the CI does to a github action (thanks @alexmorley), so the CI (.travis.yml) should no longer be necessary, but I haven't deleted it yet until I'm sure the turing way is ok with replacing travis.

The issue now is the following: the github action is detecting internal broken links (and we want it to do so), so at the moment its failing because there are some internal broken references (I checked and they are really broken, so no false positive). So unless we change those links in this PR, the github CI will never pass. What should we do? Fix them here or accept the PR not passing and create new issues for those?

**Comment by alexmorley** [comment]
> What should we do? Fix them here or accept the PR not passing and create new issues for those?

Up to you. I don't see an issue with merging now and making a new issue / PR as long as its not forgotten about. On the other hand its nice to merge a green PR :)

**Comment by alexmorley** [comment]
Also @martinagvilas its really cool that the new checker found things we would have been missing before! That's a big win IMO. :tada:

**Comment by malvikasharan** [comment]
> > What should we do? Fix them here or accept the PR not passing and create new issues for those?
> 
> Up to you. I don't see an issue with merging now and making a new issue / PR as long as its not forgotten about. On the other hand its nice to merge a green PR :)

I Agree with @alexmorley. Let's merge this and we open a PR to fix the broken links. We have many new readers who will actually like to fix those :)

Really really great job getting all these done @martinagvilas! It is indeed a massive win all in all.

**Comment by malvikasharan** [comment]
I don't have a strong opinion about keeping Travis if the GitHub action does the same job. However, I don't know the main motivation for it being created in the first place. I think @alexmorley and @sgibson91 can fill us in on that and maybe help us judge if it's advantageous to keep the CI.

**Comment by sgibson91** [comment]
Travis and GitHub Actions are both CI. If the GitHub Action does exactly the same thing, then I vote to boot out Travis. I personally prefer GitHub Actions as the build logs are kept in the repository, rather than having to move to a different website (Travis) to see the result of the build. It feels more accessible to contributors who may not be familiar with GitHub/Travis and how they interact. This was my reasoning for moving all of our other tests to Actions during the book dash (but I didn't want to interfere with the book build at the time!).

Also, thank you @martinagvilas for all your hard work moving this forward! 💖🎉

**Comment by martinagvilas** [comment]
@alexmorley @malvikasharan @sgibson91 thanks everyone for the input! In this case the github action in doing the same thing as the CI, so I will remove the travis file then. 

I think I should also update [these](https://github.com/alan-turing-institute/the-turing-way/tree/master/book) instructions before merging so contributors don't get confused on how to build the new jupyter-book version. 

And we can keep the broken links unfixed then, so other contributors can work on them 🚀

**Comment by malvikasharan** [comment]
Thanks @sgibson91. 
@martinagvilas That all sounds great. Do let me know if I can help with updating files that will be affected by this update.

**Comment by martinagvilas** [comment]
@malvikasharan I changed the `book/README.md`. It would be great if you could proofread it to make sure it is understandable (I cannot tell at this point 😅 ).

Also, I think the travis-ci needs to be disabled by someone with permissions to the settings of this repository. Removing the `.travis.yml` doesn't seem to be enough for stopping it from being triggered.

**Comment by malvikasharan** [comment]
I will proofread README today.
@alexmorley Do you have admin access to disable travis integration? I don't have the right to disable it. I have a meeting with Kirstie on Monday, I can check with her if she can disable that.

**Comment by sgibson91** [comment]
Travis is a required status check on the repo so disabling that in settings will probably stop Travis being triggered after the PR is merged (and other PRs have been rebased). We should probably make the new GitHub Action a required status check to replace Travis. However if we're leaving the broken links for the community to fix, that will have to be done _after_ we merge this PR. IIRC, I have access to set required status checks on the repo so I can look at that tomorrow.

**Comment by KirstieJane** [comment]
Hi everyone! Just a little Sunday morning note to say THANK YOU for thinking though all of this!! I LOVE all the discussion about CI. Totally agree with all the comments, happy to drop Travis.

I don’t think the CI chapter mentioned GitHub Actions, right? It was written before GH Actions existed so I think there’s some work to do there to update that content. Does making an issue for discussion of refactoring and extending the chapter seem like the right step to you all?

I’d love for the broken links issue to be reserved for new contributors. You all (and many others) can totally fix them, but each of them is a GREAT first issue. We even have a scriberia image to promote the tasks!

image

**Comment by martinagvilas** [comment]
@KirstieJane Agreed 😄 We have 70 new possible contributions with these detected broken links 🚀 

And thanks @malvikasharan for proof reading the readme 👍 

I realized that we could also run the html proofer only on those files that were modified by the contributor, so the CI would not fail when the contributor fixes a file but the others are still broken. The problem is that the tool we are using at the moment does not support this option via command line (and is written in ruby😅). I don't want to delay this merge so that the book restructuring can be done, but I will try to figure out how to achieve this in the github action with another PR.

**Comment by sgibson91** [comment]
@martinagvilas I was working on a similar idea in PR https://github.com/alan-turing-institute/the-turing-way/pull/985, so if you'd like to work together on that at some point, hit me up!

Also, I've just removed Travis as a required status check from the repo. Hopefully 🤞if you push to this branch again, Travis will no longer block the merge. I will add the new GitHub Action as a required status after merging so we recover our branch protection rules 💖

**Comment by sgibson91** [comment]
Oh, you didn't even need to push!! Hooray!

**Comment by sgibson91** [comment]
P.S. Agree with @KirstieJane that an issue with all the links that need fixing and a "good first issue" label would be AMAZING!

**Comment by sgibson91** [comment]
(Sorry for the comment spam!)

I just edited our status badge in the main README to be the GitHub Action one and get rid of the Travis one ✨

**Comment by martinagvilas** [comment]
@sgibson91 oh that's great, I hadn't seen #985. I will check it out and if I come across some possibilities I would suggest them there 🚀 And the badge looks great!

**Comment by malvikasharan** [comment]
A heads up, after this merge I will update (and merge when ready) #977 . @martinagvilas, Alex and I had been already discussing earlier to leave the broken links for new contributors, but I forgot to add that there will be more broken links as we need to sort the redirects as well.

**Comment by martinagvilas** [comment]
hmmm the netlify deployment is throwing an error, and is not very informative: 
image

I don't fully understand why the deployment worked before and now fails in master. Could it be that if the CI is failing in master netlify does not deploy?

**Comment by malvikasharan** [comment]
That's exactly whats happening:
> Could it be that if the CI is failing in master netlify does not deploy?

**Comment by malvikasharan** [comment]
@martinagvilas just to confirm, I can build this locally, no issue at all there (and it looks fantastic!!!).
image

**Comment by martinagvilas** [comment]
@malvikasharan great that it is working locally at least! 

Yeah the CI fails for the broken links. I don't immediately know how to make the step optional, but I will look it up. In the meantime I can comment out that step from the github action file so the HTML proofer is not run and the ci does not fail. The broken links are written down in the ci history anyways, so issues can be created from that.

**Comment by sgibson91** [comment]
Could we just have html proofer run in a separate GitHub Action workflow file?

**Comment by martinagvilas** [comment]
@sgibson91 we could, the only "issue" is that for running the HTML proofer you need to follow the exact same steps that the CI does until that point. But that is only an issue in terms of "build efficiency".  In any case, do you think that if html proofer is run on a separate github action but keeps failing the netlify deployment would stop failing?

**Comment by sgibson91** [comment]
We could save the `_site` folder as an artefact so that we wouldn't be running steps twice? But no, perhaps it wouldn't fix the deployment failure 🤔

**Pull request merged**
