### PR TITLE
📝Fix typo and outdated labels on the French translation

### LINKED ISSUE #2107: [HACKTOBERFEST] README translated versions to update during HacktoberFest
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

*Please note that, we have [Code of Conduct](./CODE_OF_CONDUCT.md) and [Contribution guideline](./CONTRIBUTING.md) that applies to this issue and related PRs.*

**What is my task?**

* In the last year's Hacktoberfest, our contributors translated [README.md](https://github.com/alan-turing-institute/the-turing-way#readme) file in various languages to allow more people to learn about The Turing Way
* Since last year we update the English version of the file, and hence rest of the translated version need to be updated as described in #2051 
* This issue invites people from various language to help update the README file in their language

**Who is this issue for**
* Any contributor including the Hacktoberfest participants are invited to help update the translated version of [README](https://github.com/alan-turing-institute/the-turing-way/blob/master/README-translated/) on this repository

**What should they do?**
* Identify the existing translated README file in a language they are fluent in
  * [x] Dutch ([README-Dutch](README-translated/README-Dutch.md))
  * [ ] French ([README-French.md](README-translated/README-French.md))
  * [x] German ([README-German.md](README-translated/README-German.md))
  * [ ] Indonesian ([README-Indonesian](README-translated/README-Indonesian.md))
  * [x] Italian ([README-Italian](README-translated/README-Italian.md))
  * [ ] Korean ([README-Korean](README-translated/README-Korean.md))
  * [x] Portuguese ([README-Portuguese](README-translated/README-Portuguese.md))
  * [x] Spanish ([README-Spanish](README-translated/README-Spanish.md)). - Ongoing #2065 
* If the file in your language doesn't exist in the [README-translated](https://github.com/alan-turing-institute/the-turing-way/tree/master/README-translated), please create an issue stating the language (e.g. #1338 and #1346) 
  - create a file named `README-{language}.md`, for example, `README-Hindi.md` in the [README-translated](https://github.com/alan-turing-institute/the-turing-way/tree/master/README-translated) folder

**How to proceed?**

If you would like to get involved in this translation process, please follow the steps below:

- [ ] Read our [README](./README.md)
- [ ] Create an issue describing which translated file you will be working on
- [ ] Comment below to share the issue and ping @malvikasharan (if you don't know how to open the issue, simply comment below and we will help you create the issue)
- [ ] Updated the translation of the README in your local fork 
- [ ] Do not translate the [Contributors table](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) and leave them as they appear currently (last section)

## [Contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors)`

- [ ] If you are translating, send a pull request to the main repository and we will try to review your contribution as soon as possible (though, we will need to find someone who speaks the language you are working on)
- [ ] If someone is already translating the file (please check the current issues) offer to help review their PR by commenting under their issues or PRs <-- your review will be considered for the HacktoberFest PR 

*If you would like to help translate the book chapters, we use Transifex for that. Please see more details here #970*

**What happens next? Checkboxes to finish your contribution**

- [ ] Reply below with the PR link you created (if you know someone who is fluent in your language of choice and can review your PR, please tag them for review)
- [ ] Let us know if you agree to be included in our contributor's table

---

### PR DESCRIPTION
**Pull request by Zenigata**
### Summary

Addresses but does not close #2107.

*Updating and upgrading the French translation of the ReadMe file.*

### List of changes proposed in this PR (pull-request):

* *Typo.*
* *Broken syntax.*
* *Better translation.*
* *Missing text from the English file.*

### What should a reviewer concentrate their feedback on?

- [ ] Read and test the preview.

### Acknowledging contributors

- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: Zenigata

### CODE REVIEW

**Review by LauraCarter — APPROVED** [review]
Merci @Zenigata! Tous ces changements me semblent bonnes (avec l'avertissement que je ne suis pas une locutrice native française). Je crois que c'est prêt á «merge»!

**Comment by Zenigata** [comment]
Hey 👋 How can I help in order to merge this?

**Comment by aleesteele** [comment]
@Zenigata approved on checks, you should be okay to merge! 🚀

**Comment by Zenigata** [comment]
Thanks @aleesteele 🤗 But I don't have the right to merge. Can somebody help me? 🙏

**Pull request merged**
