### PR TITLE
Add content to chapter on data licensing

### LINKED ISSUE #1: Introduce yourself
*This issue needs to be discussed as currently all the contributors' names are recorded on README file*

I've pulled together a fantastic team for the Turing Way but I don't think many of you know each other (or at least there are non overlapping connections in the social networks!)

Please could you submit a pull request with your edits to the [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md) file.

1. Fork the repository (let me know if you don't know how to do this!)
2. Open the humans.md file.
3. Copy the template to just below the last person who has entered their information.
4. Replace the words "Template" with your full name and replace the words *in italics* with your answers.
5. Save the file and open a pull request to the main repository ✨ 👾 

Ping me here if you have any questions! 

---

Please check off your name when you've submitted the PR 😺 

- [x] Alex @alexmorley 
- [x] Anna @annakrystalli 
- [x] Becky @r-j-arnold 
- [x] Louise @LouiseABowler 
- [x] Martin @martintoreilly 
- [x] Patricia @pherterich 
- [x] Rosie @rosiehigman 
- [x] Kirstie @KirstieJane 
- [x] Sarah @sgibson91 
- [ ] Amit @amitmulji 

I've listed here the folks who are named on the project, but if you'd like to be additionally involved then THAT IS AWESOME. Just comment below and I'll update this list. (Eg Tim & Alex - I'm not sure how involved you want to be - its totally up to you!)

---

Update - Welcome to Sarah (@sgibson91) who is joining us as a member of the Turing research engineering team!

### PR DESCRIPTION
**Pull request by agarwalmanvi**
### Summary

Addresses a sub-task in #1075

In this PR, I make a start with the chapter on Data Licenses. 

### List of changes proposed in this PR (pull-request)

* Brief intro to data licenses
* Table with permission levels
* CC0 license

Edit:
More changes in subsequent commits:
* Corrections to section on CC licences
* ODC licenses
* Comparing CC and ODC licenses
* Other licensing options specific to communities or use cases

### What should a reviewer concentrate their feedback on?

* Clarity of content
* Adquate to make into a chapter?
* Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [X] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: agarwalmanvi

### CODE REVIEW

**Comment by malvikasharan** [comment]
hi @agarwalmanvi, thank you for the PR. I will invite review on this by community members. Please wait for the review.

**Comment by agarwalmanvi** [comment]
Thanks for your detailed feedback @rosiehigman ! I will address points 1, 2 and 3 in a new commit that can be included in this PR. For point 4, I see that the chapter on software licences uses "license" also as a noun throughout, so perhaps I should stick with using "license" everywhere?

**Comment by agarwalmanvi** [comment]
@rosiehigman In the meantime, I've addressed points 1, 2, and 3 in some new commits. Especially for point 3, I've added new content.
For now, I'm used "license" as verb and noun throughout the chapter, with the exception of "Open Government Licence" on line 100, because it's part of the name. Perhaps @malvikasharan also has a pointer on the recommended use of "licence" vs "license"?

**Comment by agarwalmanvi** [comment]
Awesome, thanks! :smile_cat:

**Comment by malvikasharan** [comment]
Hey @c-martinez, can I bring you in to break the tie on the use of License in Software License chapter? @rosiehigman raises a good point here, an apology that we did not pay attention to that earlier. We can agree to actually use Rosie's recommendations (and add it to the overview/landing page and create consistency through this PR)

@agarwalmanvi thank you again for this PR. I see that you have covered some important ground. However, I will wait to merge it as there are a few areas of Data Licensing that needs to be covered in this chapter. We have a reference from our colleagues from DCC (see [here](https://www.dcc.ac.uk/guidance/how-guides/license-research-data)). Unfortunately, I am swamped right now, but I can come back to it next week.

For your GSoD exploration contribution, this should be enough for us to discuss if we can support your application. Please wait to hear from us by Monday.

**Comment by c-martinez** [comment]
Hi @malvikasharan !

I agree with @rosiehigman point and that changing it en masse might be best. I would even say that we could focus in this PR on data licensing, and do a separate PR dealing with the licence vs license topic.

**Comment by malvikasharan** [comment]
This PR for data license has moved to #1448 - due to multiple conflicts in many unrelated files, we can't merge this PR, but all the history, revisions and comments have been fairly recorded in #1448, where @paulowoicho will address the concerns and add missing details.

**Pull request closed without merging**
