### PR TITLE
Update Solidarity Bot configuration

### PR DESCRIPTION
**Pull request by aldenc**
### Summary

Adds configuration file for the In Solidarity bot that will change the default settings so that any use of "master", "slave", "whitelist", or "blacklist" will cause the check to fail rather than generate a warning. This way the person who created the PR will be required to fix the language before submitting the PR

Contributes to #2149

### List of changes proposed in this PR (pull-request)

* Creates .yml file that configures solidarity bot to issue a failure rather than a warning for outdated language
* This has been tested on my own fork of the repo and is working as expected

### What should a reviewer concentrate their feedback on?

Is it appropriate to have the check fail in the case of outdated language? @sgibson91 and I thought it would be better to have the check fail rather than issue a warning, because a warning could be missed and then the burden is on the reviewer to edit the text or send back to the contributor. 

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.

### CODE REVIEW

**Review by sgibson91 — APPROVED** [review]
Thanks for this work @aldenc! It's a great start towards inclusive language in the Turing Way! 💖 

It will be great to hear @malvikasharan's opinion on the failure level when she returns, but I'll approve for now.

**Comment by malvikasharan** [comment]
Thank you @aldenc and @sgibson91. Can you explain if this fail happens for any file using these terms? What happens when a documentation explains this term?

**Comment by malvikasharan** [comment]
LGTM! Thank you both. Happy to merge when you are ready.

**Comment by malvikasharan** [comment]
@all-contributor please add @aldenc for tool

**Comment by malvikasharan** [comment]
@all-contributors please add @aldenc for tool

**Pull request merged**
