### PR TITLE
Fix typo: project-design/pd-overview/pd-overview-sharing

### PR DESCRIPTION
**Pull request by TheAbstract**
### Summary

Contributes to (but does not close) https://github.com/alan-turing-institute/the-turing-way/issues/2760.  Specifically, does not address:
- modify opening paragraph - FAIR principles are considered throughout project life
- review full page for tweaks to reinforce message in opening paragraph

### List of changes proposed in this PR (pull-request)

-  fixed: inoperable->interoperable typo
- added python virtual environments to `.gitignore`

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: @TheAbstract

### CODE REVIEW

**Comment by da5nsy** [comment]
LGTM! Go ahead and merge @TheAbstract 
Thanks for your contribution! 🎉

**Comment by da5nsy** [comment]
@all-contributors please add @TheAbstract for bug

**Comment by TheAbstract** [comment]
@da5nsy about this 👇🏾
> LGTM! Go ahead and merge @TheAbstract
> Thanks for your contribution! 🎉

do you mean I should merge the PR? If so, I can't; no merge option available for me, CI is green and no conflict but there's a message "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Comment by da5nsy** [comment]
> @da5nsy about this 👇🏾
> 
> > LGTM! Go ahead and merge @TheAbstract
> > Thanks for your contribution! 🎉
> 
> do you mean I should merge the PR? If so, I can't; no merge option available for me, CI is green and no conflict but there's a message "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

Oop sorry, my misunderstanding - looks like I misunderstood our permissions settings

**Pull request merged**
