### PR TITLE
Added a resource

### LINKED ISSUE #2546: Adding resource to the Data Storage and Organisation section
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during CarpentryCon 2022. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aleesteele, @harisood, @BrainonSilicon or @EstherPlomp know on Zoom so that we can assist you.

## Summary
In the [Data Storage and Organisation](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-storage.html#) subchapter in the [Research Data Management chapter](https://the-turing-way.netlify.app/reproducible-research/rdm.html), add a resource at the end of the section on backups and storage. 

## Guide to Contribution 

1. Comment on the issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/edit/main/book/website/reproducible-research/rdm/rdm-storage.md

3. Scroll all the way down to line 81 to add the resource

4. Click 'Edit this file' to add the resource.
> Add a video on safe data storage and backup (https://www.youtube.com/watch?v=bgbbToXHgW0) from the TU Delft Open Science MOOC (https://online-learning.tudelft.nl/courses/open-science-sharing-your-research-with-the-world/). 

5. Use Markdown format to correct the wording on the page:
`Watch this video on [Safe data storage and backup](https://www.youtube.com/watch?v=bgbbToXHgW0) from the [TU Delft Open Science MOOC](https://online-learning.tudelft.nl/courses/open-science-sharing-your-research-with-the-world/).`

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue (this one is #2546). 

Example: `this pull request fixes #2546`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

### PR DESCRIPTION
**Pull request by pascalflohr**
### Summary

Added resources at the end of the section on backups and storage: [Data Storage and Organisation](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-storage.html#) subchapter in the [Research Data Management chapter](https://the-turing-way.netlify.app/reproducible-research/rdm.html)

fixes #2546

### CODE REVIEW

**Review by EstherPlomp — APPROVED** [review]
Looks great!

**Comment by EstherPlomp** [comment]
@all-contributors please add @pascalflohr for bugs

**Comment by EstherPlomp** [comment]
@all-contributors please add @klbarnes20 @brynnelliott @peranti  for bugs

**Comment by EstherPlomp** [comment]
@all-contributors please add @brynnelliott for bugs

**Comment by EstherPlomp** [comment]
@all-contributors please add @peranti for bugs

**Comment by da5nsy** [comment]
@all-contributors please add @klbarnes20 for bugs

Asking again because of [this bug](https://github.com/all-contributors/all-contributors/issues/661)

**Comment by da5nsy** [comment]
Try again please.
@all-contributors please add @klbarnes20 for bugs

**Comment by da5nsy** [comment]
Good bot.

**Pull request merged**
