### PR TITLE
Fix broken path to humans.md in PR template

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Fixes no open issues

### List of changes proposed in this PR (pull-request)

* Fix broken path to humans.md file in PR template

### What should a reviewer concentrate their feedback on?

- [x] What I did makes sense!

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [humans.md](humans.md).

### CODE REVIEW

**Comment by sgibson91** [comment]
Actually, this is still broken 🤔

**Comment by r-j-arnold** [comment]
Humans.md Has been renames to contributors.md, that that's likely the problem.

**Comment by KirstieJane** [comment]
Sorry folks!! I did that yesterday - I've reverted it now and we can discuss the renaming!

**Comment by r-j-arnold** [comment]
I think contributers.md is better- it's more explicit about who the humans inside are. Humans.md is ambiguous. We could even go further and call it contributors_list.md

**Comment by KirstieJane** [comment]
@r-j-arnold - lets discuss that in a different issue - I shouldn't have changed it without asking (I gave myself fancy privilages last night to get the contributors in using the bot!)

**Comment by r-j-arnold** [comment]
Fair enough, keeps things cleaner, I'll make an issue now.

**Pull request merged**
