### PR TITLE
Update the open research chapter by changing heading "Motivation and Background"

### LINKED ISSUE #1663: Updating Chapter Landing Pages
### Summary

The new chapter template recommends that the `How This is Useful/Why This is Helpful` section of chapter landing pages should be titled as `Motivation and Background`. This issue curates a list of all chapters that still use the old title and welcomes contributors to update them to follow the template's recommendations.

### What needs to be done?

Pick a chapter landing page from the list (tick it off from the list) below and change the title of the `How This is Useful/Why This is Helpful` section to `Motivation and Background`:

- [x] [Open Research](https://the-turing-way.netlify.app/reproducible-research/open.html)
- [x] [Licensing](https://the-turing-way.netlify.app/reproducible-research/licensing.html)
- [x] [Research Data Management](https://the-turing-way.netlify.app/reproducible-research/rdm.html)
- [x] [Reproducible Environments](https://the-turing-way.netlify.app/reproducible-research/renv.html)
- [x] [BinderHub](https://the-turing-way.netlify.app/reproducible-research/binderhub.html)
- [x] [Code Testing](https://the-turing-way.netlify.app/reproducible-research/testing.html)
- [x] [Continuous Integration](https://the-turing-way.netlify.app/reproducible-research/ci.html)
- ~~[ ] [Credit for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/credit.html)~~  **404- Note that this page no longer exists.**
- [x] [Case Studies](https://the-turing-way.netlify.app/reproducible-research/case-studies.html)
- [x] [File Naming Convention](https://the-turing-way.netlify.app/project-design/filenaming.html)
- [x] [Community Communications for Open Source Projects](https://the-turing-way.netlify.app/communication/os-comms.html)
- ~~[ ] [Collaborating on GitHub/GitLab](https://the-turing-way.netlify.app/collaboration/github-collaboration.html)~~ **404- Note that this page no longer exists.**
- [x] [Ethical Decisions in Preclinical Research](https://the-turing-way.netlify.app/ethical-research/preclinical-research.html)

### Who can help?

* Anyone interested in keeping the Turing Way consistent. We especially welcome new contributors to try their hand at this

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### PR DESCRIPTION
**Pull request by malvikasharan**
!--
Please complete the following sections when you submit your pull request. You are encouraged to keep this top level comment box updated as you develop and respond to reviews. Note that text within html comment tags will not be rendered.
-->
### Summary

Partially Fixes #1663

* I replaced the wrong header with "motivation and background"

### List of changes proposed in this PR (pull-request)

* I replaced the wrong header with "motivation and background"

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by sliaqat3** [comment]
Looks good to me, it can be merged

**Comment by malvikasharan** [comment]
@paulowoicho this has been reviewed by @sliaqat3. Please approve and merge this.

**Review by paulowoicho — APPROVED** [review]
Looks great!

**Comment by malvikasharan** [comment]
@all-contributors please add @sliaqat3 for review

**Comment by malvikasharan** [comment]
Thank you @sliaqat3 @TimRodgers340125go  for discussing GitHub with me :)

**Pull request merged**
