### PR TITLE
updates guide name and fixes some links

### PR DESCRIPTION
**Pull request by lauracion**
### Summary

Addresses (but does not close) #2028

### List of changes proposed in this PR (pull-request)

- [x] Changing name from book to guide
- [x] Changes several links from .md to .html

### What should a reviewer concentrate their feedback on?

- [x] Changing name from book to guide
- [x] Changes several links from .md to .html
- [x] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.

### CODE REVIEW

**Comment by da5nsy** [comment]
Thanks for spotting this @lauracion! I've updated the formatting to make use of the jupyter book label system (that way if the URLs change in the future) it ~~won't~~ shouldn't break. 

I've also [removed the broken link](https://github.com/alan-turing-institute/the-turing-way/pull/2029/commits/5ec86f69c2ebb52c7ea75356e97e3c70bab09b36) at the start because I couldn't work out where it was meant to point to.

Is anything else required to close #2028?

**Comment by lauracion** [comment]
Thank you, @da5nsy, for updating the formatting!
I had the same doubt about the broken link you removed, but preferred someone else confirmed the removal 😄 
#2028 could be close now. 
@malvikasharan suggested the creation of an issue for broken links spotted in the Ethics Guide. If future links are detected broken there, should #2028 be reopened? A new issue created? It does not matter either way? (not completely sure about the mechanics 😅 )

**Review by da5nsy — APPROVED** [review]

**Comment by da5nsy** [comment]
> @malvikasharan suggested the creation of an issue for broken links spotted in the Ethics Guide. If future links are detected broken there, should #2028 be reopened? A new issue created? It does not matter either way? (not completely sure about the mechanics 😅 )

I'm not sure about the best practice/community norms on this either! 😸 
Hopefully, @malvikasharan will be able to offer us some guidance (should we close #2082 or keep it open?).

**Comment by LauraCarter** [comment]
We had a bit of a discussion about this at Book Dash and decided good practice would be to open new issues and PRs for new fixes, rather than keep this one open (it's also good for new contributors, as more opportunity to practice opening issues and PRs!) - so I'm going to close this PR and #2028. Thank you all!

**Pull request merged**
