### PR TITLE
Fix link to University of Leicester Study Skills

### LINKED ISSUE #1865: There is a missing link in the Inclusivity section of `CONTRIBUTING.md`
### Summary

A link in the **Inclusivity** section of [`CONTRIBUTING.md`](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md), specifically within this sentence

> use respectful, gender-neutral and inclusive language (learn more about [inclusive writing](https://www.le.ac.uk/oerresources/ssds/studyskills/page_37.htm), resource by University of Leicester).

is missing (raises a [404 error](https://en.wikipedia.org/wiki/HTTP_404)). A version I've found via the wayback machine is here (but hard to read): https://web.archive.org/web/20170901073508/http://www.le.ac.uk/oerresources/ssds/studyskills/page_37.htm

### What needs to be done?

- [ ] *Ideally find a new example of that page.*
- [ ] *If the previous doesn't work, find a new citation or simply copy some of the text and reference the original author if possible.*

### Who can help?

* *Whoever originally cited that text could provide helpful advice on what's essential to the quote.*

---

### Updates

*None yet.*

### PR DESCRIPTION
**Pull request by griff-rees**
### Summary

Fixes #1865

*Replaces broken link to Leicester Study Skills PDF.*

### List of changes proposed in this PR (pull-request)

* *Fixed link.*
* *Add alternate link for zipped html option.*
* *Slightly rephrased copy to cover both options.*

### What should a reviewer concentrate their feedback on?

- [ ] *Double check the links.*
- [ ] Make sure the rephrasing is ok.

### Acknowledging contributors

- [X] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: griff-rees

### CODE REVIEW

**Review by inwaves — APPROVED** [review]

**Comment by inwaves** [comment]
@all-contributors please add @griff-rees for bug

**Comment by griff-rees** [comment]
Cool thanks for all that.

**Comment by griff-rees** [comment]
Apologies: I'm so used to working on my own projects, hence accidently closing before when merging with my fork! Shall I assume this gets sorted when someone with write access merges/closes? Will hopefully avoid that mistake in the future...

**Comment by inwaves** [comment]
No worries, I've merged it in now.

**Pull request merged**
