### PR TITLE
Adding new set of images and compressing file larger than 700 kb

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

We recently published new sets of images in 2022, this PR adds them all in the Book folder

### List of changes proposed in this PR (pull-request)

* Adding new images, see https://zenodo.org/record/7587336
* Reducing larger files

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?
- [ ] After merging this issue, they can help others link images to different chapters

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by da5nsy** [comment]
Hi Malvika, for most of these images, indexed-png is going to be more efficient and look better than jpeg. I'm happy to lend a hand with this sometime if that would be useful.

@sgibson91 - any idea why we don't see `auto-compress-images` (#2251) act on this PR?

**Review by da5nsy — CHANGES_REQUESTED** [review]
Hi Malvika, for most of these images, indexed-png is going to be more efficient and look better than jpeg. I'm happy to lend a hand with this sometime if that would be useful.

**Comment by sgibson91** [comment]
> @sgibson91 - any idea why we don't see `auto-compress-images` (#2251) act on this PR?

Because the PR has not been reviewed merged, so the workflow is not in `main` to act on all subsequent PRs.

**Comment by da5nsy** [comment]
> > @sgibson91 - any idea why we don't see `auto-compress-images` (#2251) act on this PR?
> 
> Because PR #2251 has not been reviewed merged, so the workflow is not in `main` to act on all subsequent PRs.

I hadn't had my coffee yet this morning. In my head we merged that ages ago!

**Comment by malvikasharan** [comment]
> Hi Malvika, for most of these images, indexed-png is going to be more efficient and look better than jpeg. I'm happy to lend a hand with this sometime if that would be useful.

@da5nsy that sounds good to me. We might have lots of image-not-found errors if we change the file format for images that are already linked in the book. Not a big issue as they can be updated.

**Comment by da5nsy** [comment]
> > Hi Malvika, for most of these images, indexed-png is going to be more efficient and look better than jpeg. I'm happy to lend a hand with this sometime if that would be useful.
> 
> @da5nsy that sounds good to me. We might have lots of image-not-found errors if we change the file format for images that are already linked in the book. Not a big issue as they can be updated.

I modified a lot of image references (all of them?) to have the `.*` extension in #2767, so hopefully this won't be an issue.

**Comment by malvikasharan** [comment]
Cool! then please go ahead with updating and merging this PR with those changes when you can.

**Comment by bsipocz** [comment]
I've added the infrastructure label as well, as this PR is held up with image format/autocompress/etc issues, so to ensure we have an eye on it.

@da5nsy - I maybe able to give a hand with this, let me know what you've been thinking to do here. I suppose rebase to trigger the autocompress workflow? and then maybe an autoconvert of jpeg --> png, and checking on the links?

**Comment by da5nsy** [comment]
Summary of previous commit:

- Contributing.jpg, pandoc.jpg, binderhub.jpg, community.jpg, continuous-integration-may19.jpg, culture-shift.jpg, decolonising-knowledge.jpg, fair-domains.jpg, fair-principles.jpg, machine-learning-reusable-pipeline.jpg, notifications-and-surveillence.jpg, readable-code.jpg, reproducible-definition-grid.jpg, reproducible-journey.jpg, research-cycle.jpg, road-to-reproducibility.jpg, thank-you-contributors.jpg, that-could-be-a-chapter.jpg, too-easy-not-to-do.jpg - SVG is available (and so jpg will not be used in book), so reverting to avoid repo bloat.
- Replaced new images from `zz-TheTuringWay-Latest-Scriberia-2022-Nov-AllJPG-English-text.zip` with indexed png versions of the same.
- Unclear where archive-or-publish.jpg, article-types.jpg, collaborative-policy.jpg, github-workflow.jpg, giving-a-talk.jpg, hybrid-work.jpg, integrating-practices.jpg, legal-challenges.jpg, low-traffic-tool.jpg, open-governence.jpg, rdm-storage.jpg, research-communities.jpg, research-object.jpg, reusability-loop.jpg, rse-community.jpg, storage-archiving.jpg, sustainability-path.jpg, translation-memory.jpg have come from, but if we have the source files I suspect we could have better quality and smaller file size.
- As above for community-exchange but I _don't_ think we could have better quality and smaller file size, because of the gradient.
- bug-catching.jpg, bugs-are-features.jpg, collaboration-house.jpg, continuous-integration-nov20.jpg, data-privacy.jpg, data-stewards.jpg, ethical-research.jpg, ethics.jpg, evolution-open-research.jpg, evolution-open-science.jpg, fair-cookbook.jpg, fixing-links.jpg, fountain-of-open-data.jpg, mentored-contributions.jpg, no-issues-no-users.jpg, recognition.jpg, research-tools.jpg, reusable-code-garden.jpg, robo-debt.jpg, routes-to-OA.jpg, rse-community.jpg, share-work-openly.jpg, software-library-feedback.jpg, the-turing-way-chapters.jpg, theturingway-consistency.jpg replaced with equivalent png.
- _Unclear what has changed with the svgs that is making them show up as changed in this PR_
- Come back to data-are-people.jpg, data-equals-people.jpg, data-is-people.jpg, data-wrangler.jpg
- ethics-committee-with-text.jpg - negligible space saving, reverting.
- engaging-with-unions.jpg, fireside-chat.jpg, peer-review-process.jpg, software-credit.jpg - not suitable for conversion to png because of gradients. If we had the svg it would be better.
- turing-rss.jpg - is this named correctly?

_Note: it appears that the pdfs in the linked zenodo are just jpgs packaged as pdfs, they are not true vector images, unfortunately._

**Comment by da5nsy** [comment]
> I suppose rebase to trigger the autocompress workflow? and then maybe an autoconvert of jpeg --> png, and checking on the links?

@bsipocz - afraid it's fiddlier than that because the image compressor doesn't do indexed pngs, which is the type of compression that works best for our images (by a long shot)

**Review by da5nsy — APPROVED** [review]

**Review by da5nsy — APPROVED** [review]

**Pull request merged**
