### PR TITLE
Migrate figures to the content directory and fix links

### PR DESCRIPTION
**Pull request by yochannah**
### Summary

Let's keep all content, _including_ figures, in the content directory. There were two locations that had figures,

ROOT/figures/*
ROOT/book/website/assets/figures/*

I _think_ these were the same, just duplicated, but I'm only like 80% sure. 

### List of changes proposed in this PR (pull-request)

* I've deleted the ROOT/figures folder
* migrate the ROOT/book/website/assets/figures/ folder to now be in ROOT/book/content/figures
* update links in the textual content to point to the new figures path. 

### What should a reviewer concentrate their feedback on?

- [ ] Check for broken images in the book. 

(I've checked and don't think there are any, but I may have missed something)

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by gkiar** [comment]
Only found two! They are here:
- [ ] https://deploy-preview-507--the-turing-way.netlify.com/open_research/06/openscholarship
- [ ] https://deploy-preview-507--the-turing-way.netlify.com/risk_assessment/risk_assessment

**Comment by yochannah** [comment]
I think these are fixed now - thanks for the review @gkiar - could you re-review? 😍

**Comment by sgibson91** [comment]
Hey @yochannah I don't think the second figure @gkiar found is till broken

**Comment by pherterich** [comment]
Is this related to #551 @alexmorley ? Not sure how to untangle this PR, could you give it a look? Thanks!

**Comment by alexmorley** [comment]
Merged with master so we can use the CI

**Comment by pherterich** [comment]
The risk assessment picture still doesn't show for me in the preview. I'm tempted to approve this one and see if we can fix this in #551 ...

**Comment by alexmorley** [comment]
We need to decide which order to merge them in... But yeah we can do that for sure!

**Comment by pherterich** [comment]
@gkiar do you want to move your review from request changes to approved? Otherwise we will dismiss your review in a bit to unblock the merge. Thanks for your contribution to this!

**Comment by gkiar** [comment]
Approved! Sorry for the delay - there's SO many emails related to this repo so I've had a hard time knowing which ones to pay attention to 😅

**Comment by pherterich** [comment]
Haha, I feel you @gkiar - thank you so much for your help!

**Pull request merged**
