### PR TITLE
Add "tips" section

### PR DESCRIPTION
**Pull request by inwaves**
### Summary

Add a "tips" section containing to ensure moving forward #1740 and #1670 are avoided. 

### List of changes proposed in this PR (pull-request)

* Added "tips" section to offer style guidance for items that triggered previous issues.
* Also fixed two typos in the text.

### What should a reviewer concentrate their feedback on?

- [ ] Special content blocks look ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Review by EstherPlomp — COMMENTED** [review]
Hi @inwaves! Is it correct that there is no incorrect example for the 2. second list item? 
Cheers, Esther

**Comment by inwaves** [comment]
Hi @EstherPlomp 

Yes—basically what I wanted to show was that indenting the blockquote after the first list point resolves the issue with the reset numbering:
image

I will add a bit more context around why it's necessary, because right now it isn't clear what issue we're trying to avoid.

**Comment by EstherPlomp** [comment]
Ah thanks, that makes more sense now! 
In the deploy preview the wrong numbering is displayed correctly, however, the notes are also kind of strange visually: 
image
Would it be possible to remove the note parts and have it displayed similar as the rest of the guide? 

I also think it makes sense to have the note on 'Write external links using http:// instead of the www.' as a separate section with a little explanation about why people should use http://? Cheers!

**Review by EstherPlomp — APPROVED** [review]
Thanks very much for adjusting, I think it is very clear now!

**Pull request merged**
