### PR TITLE
Create newsletter for September 2020

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

* Create a draft for Sep 2020 Newsletter

### List of changes proposed in this PR (pull-request)

* Text and news items are added
* Images are uploaded

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Hi Malvika! The content looks great. I have general feedback for structure and readability, but if it's not useful then feel free to disregard 😄 

Suggestion 1) Introduction

I would shorten the intro so that it's easier to info capture eg:
"Here's what you missed in August
-  We published a chapter on Book Dash events (there will be another event coming in November 📅 )
- co-authored chapter on how The Turing Way supports and recognizes contributors (Your feedback and suggestions are very welcome on all these resources. 🙌)
- The second cohort of Open Life Science started with 13 members joining the OLS-2 for Turing Collaboration with 6 projects Congratulations! 🎉
- Esther Plomp represented The Turing Way in two conferences by giving lightning talks. Thank you! 💐

More details on these can be found below the Community Meeting Info 👇 "

Suggestion 2)

Moving events to the bottom for flow of information ie. 
- intro 
- community meetings 
- all news from the community 
- events 

10/10 ⭐ work on the newsletter!

**Comment by malvikasharan** [comment]
All are very useful feedback. Thanks @Ismael-KG and @BrainonSilicon. I will integrate all your suggestions and update the newsletter to share with @KirstieJane 🙌 🎉

**Comment by malvikasharan** [comment]
@paulowoicho can you please approve this? this has already been reviewed by 3 people. 🙏

**Comment by paulowoicho** [comment]
@malvikasharan no worries!

**Review by paulowoicho — APPROVED** [review]

**Comment by paulowoicho** [comment]
Hi @malvikasharan . I didn't mean to remove the request to review from Kirstie. I was working from my phone!

**Pull request merged**
