### PR TITLE
Update links and Gitter section in contributing guide

### LINKED ISSUE #1755: [BUG] Broken or out-of-date links in contributor's guide
### Description
The two links in inclusivity section of contributor's guide do not work. https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md

- [ ] Link to University of Leicester inclusive writing guide redirects to Skills Centre homepage
- [ ] Link to about blogpost on colour-blind friendly plots goes to 'Page Not Found' page

Please tick off the boxes above when a resolution is made (either find new link or remove the link).

### PR DESCRIPTION
**Pull request by Lovkush-A**
### Summary
Fixes #1755 

### List of changes proposed in this PR (pull-request)
* found updated link for inclusive writing guide.
* found different blogpost about creating colour-blind friendly diagrams.

### What should a reviewer concentrate their feedback on?
- [ ] Check the new link to inclusive writing guide works
- [ ] Check that the new blogpost for colour blindness is appropriate (and that the link works!)

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: Lovkush-A

### CODE REVIEW

**Review by malvikasharan — APPROVED** [review]
Thanks for fixing the links! Approving this change with the rephrasing on Gitter.

**Comment by malvikasharan** [comment]
@all-contributors please add @Lovkush-A for bug fix

**Comment by malvikasharan** [comment]
@Lovkush-A let me know when you are ready for this to be merged.

**Comment by Lovkush-A** [comment]
All good for me. Please go ahead with the merge!

**Pull request merged**
