### PR TITLE
Added contents to "Leadership and Management" for Remote Collaboration

### PR DESCRIPTION
**Pull request by IIITM-Jay**
## Summary:
Added Contents to _"Leadership and Management"_ for Remote Collaboration , with refernce to issue #1116 and discussion #942 .
## What it contains:
- [x] Elucidated the Classifications of management
- [x] Discussed the problems faced when remotely located
- [x] Discussed the solution for the proposed problems
- [x] Focused on representing the contents in a pictorial way
- [x] Key points are well explained diagrammatically
## What should a reviewer concentrate their feedback on?
- [ ] Feedback on the contents to be incorporated
- [ ] The positioning of images
- [ ] Images and corresponding contents are well established

### CODE REVIEW

**Comment by IIITM-Jay** [comment]
@malvikasharan sorry for disturbing and inconvenience so faced. Hope you will find something new and interesting. Need your valuable feedback and suggestions on the same.

**Comment by IIITM-Jay** [comment]
@malvikasharan I have given a lot of effort to give the content a nicer look and more prettier one so as to have *less reading and more understanding* of the concepts used in the management via **flow charts and smart diagrams**,keeping in mind all the **key points of the management**.
Hence want your feedback and more suggestions as well.

**Comment by malvikasharan** [comment]
Thanks @IIITM-Jay for your hardwork.
A few first comments:
1) The content doesn't seem to have synced to the remote collaboration branch. Your file should exist in the book/content/remote-collaboration - at the moment it is in your main repo (with a name different from suggested in my branch). If it is easier, you can send a PR to this branch where a file already exists: https://github.com/alan-turing-institute/the-turing-way/pull/962, preview here: https://deploy-preview-962--the-turing-way.netlify.app/remote_collaboration/management/management.html

2) This is supposed to capture leadership and management related caveats for remote collaboration. What you have written is about managament, which is good but maybe doesn't really fit in the remote collaboration. You can adapt your content for project design or collaboration related content.

**Comment by IIITM-Jay** [comment]
@malvikasharan I have already opened an issue related to this and thanks for your suggestions. I will work on it to cover the caveats for remote collaboration. For the time being, can you assign someone to review it and can give feedbacks.

**Comment by malvikasharan** [comment]
@IIITM-Jay I don't think your issue or PR addresses my concerns as mentioned in my last response.

**Pull request closed without merging**
