### PR TITLE
Test Sphinx Book Update

### PR DESCRIPTION
**Pull request by da5nsy**
### Summary

The Sphinx Book template has been updated a couple of times recently and the updates seem to provide meaningful benefit (in combination with the Jupyter Books update - see #2307).

There's mainly CSS/HTML updates, and so I don't think there's anything that should break, but worth checking.

### What should a reviewer concentrate their feedback on?

- [ ] Check elements that you suspect might break, and report as a comment below

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by da5nsy** [comment]
I *really* like this. 

Mainly for https://github.com/executablebooks/sphinx-book-theme/pull/454 fixing https://github.com/executablebooks/jupyter-book/issues/950 which has been a pet peeve of mine for a while.

What do others think?

**Comment by da5nsy** [comment]
There might be an issue where 'Toggle Navigation' button pops up. (Will follow up later)

**Comment by malvikasharan** [comment]
Hi @da5nsy, The executable book team will be releasing a new version, can we update that in this PR when it's out to sync it with main?

**Comment by da5nsy** [comment]
> Hi @da5nsy, The executable book team will be releasing a new version, can we update that in PR #2307 when it's out to sync it with main?

Hi @malvikasharan, Yep - I imagine that once https://github.com/executablebooks/jupyter-book/pull/1682 is merged, I'll update https://github.com/alan-turing-institute/the-turing-way/pull/2307, and then once (if) we merge that, _this_ PR can be closed without merging.

**Comment by da5nsy** [comment]
Closing following the merging of #2307

**Pull request closed without merging**
