### PR TITLE
Add first Version of German README

### PR DESCRIPTION
**Pull request by glumand**
The English-README was used as a reference and the text was translated
to German. The links were kept English most of the time, as it did not
seem to make sense to translate them to me.

Signed-off-by: glumand <trundle13@googlemail.com>

### Summary
Adresses #1335 . A German Version of the README was added.

### List of changes proposed in this PR (pull-request)

- add German README

### What should a reviewer concentrate their feedback on?

- [ ] Is the format the way you expect it to be?
- [ ] If there is someone speaking German: Are you fine with the choice of words, especially in the cases where there is no direct translation?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@glumand Thank you for your contribution. Can you recommend someone to review this? 
I wonder if @HeidiSeibold can recommend for this PR?

**Comment by glumand** [comment]
@malvikasharan it would be really nice, if someone speaking German could review, because it is just the second time I have translated something related to this topic, so I am not completely confident about my translation. Would you mind to mark this PR as hacktoberfest-accepted, even though we are still working on it? I will keep on working on the translation until it is ready to be merged anyways. Thank you. :)

**Comment by tomsing1** [comment]
> @malvikasharan it would be really nice, if someone speaking German could review, because it is just the second time I have translated something related to this topic, so I am not completely confident about my translation. Would you mind to mark this PR as hacktoberfest-accepted, even though we are still working on it? I will keep on working on the translation until it is ready to be merged anyways. Thank you. :)

I am a native German speaker and am happy to go over the translation, if that's still helpful.

**Comment by malvikasharan** [comment]
That would be fantastic @tomsing1 🎉

**Comment by HeidiSeibold** [comment]
Cool @tomsing1 :clap:

**Comment by glumand** [comment]
@tomsing1 thank you for your corrections. It sounds much better now. Do I have to do anything so these changes can be merged?

**Review by malvikasharan — APPROVED** [review]

**Comment by malvikasharan** [comment]
Great work @glumand and @tomsing1. This PR is approved to be merged.

**Comment by malvikasharan** [comment]
@all-contributors please add @tomsing1 for translation

**Comment by malvikasharan** [comment]
@all-contributors please add @glumand for translation

**Pull request merged**
