### PR TITLE
Create bookdash-illustrator chapter in Book Dash chapter

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

* Converting comment from the Book Dash planning issue  #2064 from last year on how we work with Scriberia into a chapter

### List of changes proposed in this PR (pull-request)

* Adding a new chapter
* Updating toc file
* Linking some relevant docs where TTW images have been used (besides the book)
* Adding an image from the Book Dash Manchester that is linked to the main repo figure folder

### What should a reviewer concentrate their feedback on?

- [x] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by cassgvp — APPROVED** [review]
Wonderfully helpful inclusion, thank you. :)

**Comment by malvikasharan** [comment]
Thank you @cassgvp and @ClauFischer for the review.

**Comment by malvikasharan** [comment]
@all-contributors please add @ClauFischer for review

**Comment by malvikasharan** [comment]
@all-contributors please add @cassgvp for idea and review

**Pull request merged**
