### PR TITLE
Update Jupyter Book version

### PR DESCRIPTION
**Pull request by da5nsy**
### Summary

Testing the new version of Jupyter Book

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by da5nsy** [comment]
All LGTM? Others?

**Comment by da5nsy** [comment]
Adding a review request label here because building seems to be broken with the previous Jupyter Book version (see comments on #2306)

**Comment by da5nsy** [comment]
Need to modify zero-to-binder (and any other pages that use the tabbed layouts) to respond to jupyter book's move away from 'Sphinx Panels' to 'Sphinx Design'

**Review by sgibson91 — APPROVED** [review]
Thanks for this work @da5nsy - this LGTM!

I noticed for the tabs in the Zero-to-Binder tutorial that if you select a given tab in one section, it updates all the other sections to match - which is really nice! 😄

**Comment by da5nsy** [comment]
> I noticed for the tabs in the Zero-to-Binder tutorial that if you select a given tab in one section, it updates all the other sections to match - which is really nice! 😄

Yeah I thought this was a nice flourish! ✨

**Pull request merged**
