### PR TITLE
Added community_profile.png and fixed the broken link

### LINKED ISSUE #1079: Broken link of image
### Bug description
In the chapter `Collaborating Github' under [checklist_bibliography](book/content/collaborating_github/4/checklist_bibliography.md) section, the image link provided is broken ( results in Error 404).

#### Expected behavior
On clicking the link it should give an image of [Community Profile](https://github.com/alan-turing-institute/the-turing-way/community)

### How to reproduce
Updating the broken link with the desired image should work.

- Browser:

- [x]  *Chromre*
- [ ]  *Firefox*

### PR DESCRIPTION
**Pull request by Yash-Varshney**
### Summary

Added the image of `community_profile` in [Collaborating Github](https://github.com/Yash-Varshney/the-turing-way/blob/master/book/content/collaborating_github/4/checklist_bibliography.md) and fixed the broken link

Fixes #1079

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thanks @Yash-Varshney! This looks good.

**Comment by malvikasharan** [comment]
@all-contributors please add @Yash-Varshney for bug fix.

**Comment by Yash-Varshney** [comment]
Thank you @malvikasharan . An honor to be a part of this tremendous team !!

**Comment by Yash-Varshney** [comment]
I think it is ready to be merged @malvikasharan !!

**Pull request merged**
