### PR TITLE
Fixing jupyter warning

### LINKED ISSUE #1670: [BUG] Fixing external links
### Summary

The way some external links are written trigger a warning in the Jupyter-Book build. External links should be written down with `https://` (e.g.  `https://twitter.com`) and not with `www.` (e.g.  `www.twitter.com`) or without prefix (e.g. `twitter.com`)

### What needs to be done?

Replace the external links written down with `www.` and without prefix, with external links written down with `https://`

The following links should be corrected:

- [x] link `twitter.com/` in line 23 of file `collaboration/new-community/new-community-guide.md`
- [x] link `arewemeetingyet.com` in line 121 of file `collaboration/remote-collab/remote-collab-conferences.md`
- [x] link `osf.io/meetings` in line 187 of file `collaboration/remote-collab/remote-collab-conferences.md`
- [ ] link  `www.slack.com` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md`
- [ ] link `www.twitter.com` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md` 
- [ ] link `www.github.com` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md` 
- [ ] link `www.gitter.im` in line 29 of file `collaboration/remote-collab/remote-collab-participation.md` 
- [ ] link `www.grammarly.com` in line 19 of file `community-handbook/consistency/consistency-language.md`
- [ ] link `arewemeetingyet.com/` in line 89 of file `community-handbook/coworking/coworking-organisation.md`
- [ ] link `theturingway.slack.com` in line 38 of file `community-handbook/newsletters/newsletters-process.md`
- [ ] link `tinyletter.com/` in line 96 of file `community-handbook/newsletters/newsletters-process.md`
- [ ] link `theturingway.slack.com` in line 116 of file `community-handbook/newsletters/newsletters-process.md`

### Who can help?

Everyone!

### PR DESCRIPTION
**Pull request by Hanaffi**
### Summary

Partly addresses #1670

### List of changes proposed in this PR (pull-request)
Jupyter warnings..

### What should a reviewer concentrate their feedback on?

- [X] Everything looks ok?

### Acknowledging contributors

- [X] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [X] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by Hanaffi** [comment]
@malvikasharan  Can you review it please?

**Comment by malvikasharan** [comment]
Thanks @Hanaffi. Can you try testing locally if all the related error messages are addressed?
Here is a README  describing how you can do it: https://github.com/alan-turing-institute/the-turing-way/tree/master/book

**Comment by Hanaffi** [comment]
@malvikasharan It doesn't state how to deploy on windows :D

**Comment by malvikasharan** [comment]
The process is explained here: https://jupyterbook.org/advanced/advanced.html#working-on-windows.
I can assign someone else to test this.

**Comment by malvikasharan** [comment]
I am gonna review this now, can you please create a PR to update the README page for the local build of JupyterBook by adding a sentence with the link I shared for Windows user?

**Review by malvikasharan — APPROVED** [review]
The links fixed on this PR are correct.
There are still quite a bit of Jupyter broken link warnings that will need to be fixed either on this branch or by new contributors on other branches.

**Comment by malvikasharan** [comment]
@all-contributors please add @Hanaffi for bug fix

**Comment by Hanaffi** [comment]
@malvikasharan 
Okay, I have updated the readme https://github.com/alan-turing-institute/the-turing-way/issues/1753 .
I will work on these other errors.

**Pull request merged**
