### PR TITLE
Fix figure name

### PR DESCRIPTION
**Pull request by JimMadge**
### Summary

~~Contributes to #2611 ~~

Ensure figure file name matches the corresponding reference in Markdown so that it is rendered in the book. To be (more) consistent I have made the file name lower case.

```
/home/jim/Documents/the-turing-way/book/website/reproducible-research/binderhub.md:17: WARNING: image file not readable: figures/binderhub.jpg
/home/jim/Documents/the-turing-way/book/website/reproducible-research/vcs/vcs-data.md:1: WARNING: image file not readable: figures/provenance.jpg
```

### List of changes proposed in this PR (pull-request)

* Change the name of `provenance.jpg`
* Change the name of `binderhub.jpg`

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by da5nsy — APPROVED** [review]
This does fix an error, but not one that I see represented in #2611. 
Am I missing it, or does it not show as an error for some reason? 🤔

**Comment by JimMadge** [comment]
@da5nsy My mistake, I assumed the warning would have been captured there :sweat_smile:.

I've added the warning message to the PR and fixed a similar problem with another image.

**Comment by da5nsy** [comment]
> @da5nsy My mistake, I assumed the warning would have been captured there 😅.
> 
> I've added the warning message to the PR and fixed a similar problem with another image.

Curious! I wonder why I don't see those errors 🤔

**Comment by JimMadge** [comment]
> Curious! I wonder why I don't see those errors thinking

Are you using Windows? If I recall correctly, NTFS filesystems are not case sensitive, so `abc.jpg`==`Abc.jpg`.

That may be important; depending on which OS is used to build the published book, figure may be failing to appear. I'm not sure what the process is for deploying the book to netlify.

**Comment by da5nsy** [comment]
> Are you using Windows? If I recall correctly, NTFS filesystems are not case sensitive, so `abc.jpg`==`Abc.jpg`. Linux (and MacOS) file systems are case sensitive (at least all of the ones I have encountered).


I am indeed using Windows! That'll explain it. Good to know! Thanks!

**Pull request merged**
