### PR TITLE
Add checklist for chairing coworking sessions

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

* Since we will have new members chairing these sessions, I am adding a small checklist describing what chairing involves

### List of changes proposed in this PR (pull-request)

* Add checklist
* update where needed

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@acocac and @Arielle-Bennett, can you please review this PR adding from your work (coworking and other meetings you organise and chair)?

**Comment by acocac** [comment]
@malvikasharan, the changes LGTM. It would be great to rescue/mention somewhere in `coworking-collabcafe.md ` this great [YouTube video](https://www.youtube.com/watch?v=XUw5kpypeo8) of a session between you and Kirstie improving the collaboration cafe 🕐

**Review by acocac — APPROVED** [review]

**Comment by malvikasharan** [comment]
Video integration idea is brilliant, this one is the very first one and hosting is much more structured :D https://www.youtube.com/watch?v=I0z7OEbBzes

**Comment by malvikasharan** [comment]
YouTube videos added! Merging this. 💃

**Pull request merged**
