### PR TITLE
Format glossary with JupyterBook standard

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

* Testing if the glossary format of JupyterBook can be used

### List of changes proposed in this PR (pull-request)

*  Update the glossary page
* Update style guide with description on how to crosslink glossary 

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@paulowoicho I have added a new file in the Style Guide to describe glossary. This can later be updated for the special block as well.

Can you and/or @EKaroune have a look at these rendered link and see if this is ok?
- Glossary: https://deploy-preview-1624--the-turing-way.netlify.app/afterword/glossary.html
- "Authors" is referenced in [this file](https://deploy-preview-1624--the-turing-way.netlify.app/community-handbook/acknowledgement/acknowledgement-members.html) "All the substantial contributors are also highlighted in the Contributors Table and named as co-authors [def]"
- "Binder" is referenced in [this file](file:///Users/msharan/github/the-turing-way/book/website/_build/html/reproducible-research/binderhub/binderhub-build.html) "Binder [def] is an open source project maintained by ..."
- Style guide: https://deploy-preview-1624--the-turing-way.netlify.app/community-handbook/style/style-more-styling.html

**Review by EKaroune — COMMENTED** [review]
This all looks good. The only issue is with the definition for system testing in the glossary as it is coming up as bold text.

**Comment by malvikasharan** [comment]
Cool, I updated that and corrected the issue with formatting.

**Review by paulowoicho — APPROVED** [review]
This looks great!

**Comment by malvikasharan** [comment]
Thank you both! I am merging this.

**Comment by malvikasharan** [comment]
@paulowoicho I think Emma is already working on that. She is linking the glossary and removing the preexisting blocks in the same branch. I think we can leave this to her.

**Comment by EKaroune** [comment]
yes  I have started removing the glossaries from the end of the chapters on a new branch, i think called update glossary links. I can also do the links to the words in the chapters now that Malvika has shown me how to do it. thanks @malvikasharan and @paulowoicho for your help with this!

**Pull request merged**
