### PR TITLE
[Ready for review] Develop open science chapter

### PR DESCRIPTION
**Pull request by r-j-arnold**
Edit and add material to the open science chapter. Currently there is a lot of material but only some subsections have been edited into single flowing units.

### CODE REVIEW

**Comment by r-j-arnold** [comment]
**To reviewers of this pull request**

This branch is ready for high level review, i.e. major-moderate changes to the chapter such as adding more material about a subject, moving sections etc. After those changes are done I'll merge this into the open_source branch and then make another pull request to handle smaller details.

I suggest that for minor but unarguable changes, e.g. typos or if I've screwed up some grammar you could either 

- make a branch from my branch of the project and change those as you go along, and then make a pull request to my branch, or instead
- Keep a note of all those changes and then bring then up on the pull request I'll make after this one which will deal with low level changes.

**Comment by KirstieJane** [comment]
These are great recommendations @r-j-arnold. Either options work in my opinion and will allow you to merge and go to a “next step” PR without growing this PR into a great big beast!

**Comment by sgibson91** [comment]
@pherterich Did you fork/branch from a branch that hasn't been merged yet instead of from master? In that case, any commits that haven't been merged from the parent branch would also appear your branch's PR to master. (Don't worry, I've made this mistake before.)

**Comment by pherterich** [comment]
I'm pretty sure all the PRs I see here from me and others were forked from master and not @r-j-arnold 's open science branch which is really confusing me. Maybe it's just the GitHub interface messing with me again...

**Comment by r-j-arnold** [comment]
@pherterich @sgibson91 

Hey, there's nothing going wrong, here's what's happened.

This pull request is from my fork's version control branch.

This morning I merged the changes in the alan turing master into that branch to keep it up to date and reduce the likelihood of merge conflicts in the future.

As a result all the recent commits in the turing master branch have been applied (i.e. merged in) to this pull request, so unless I'm missing anything it all should be fine.

**Comment by pherterich** [comment]
Got it! I'm usually too stupid to get all the changes in sync with my fork and various branches, so I don't know the expected behaviour - you learn something new every day.

**Comment by r-j-arnold** [comment]
@pherterich You're not stupid, there'a a reason https://ohshitgit.com/ exists and there aren't many dim people using version control. I was in a talk *yesterday* where an RSE warned a bunch of theoretical physicists it's a steep learning curve, and god knows I've screwed up more than once.

**Comment by KirstieJane** [comment]
Just following along on this conversation & wanted to send some big ✨💃🏼🙌🏻🚀😂 for everyone pushing through the “aaaargh - I’ve got lost in a git mess” pain points and helping each other out.

This kind of situation is a great “gotcha”, so @r-j-Arnold, if you can think of screenshots that would tell the story of “this is the error I saw, this is what I thought I was doing, this is what I was *actually* doing and this is how I fixed it” that would be awesome.

I think you’re all fixed now, so maybe this can just be something for the whole team to remember to capture if they (inevitably!) get into a git related confusion in the future :smiley:

But mostly, THANK YOU for playing along! It’s so wonderful to see all this open conversation 🤩

**Comment by r-j-arnold** [comment]
Screenshots saved.

**Comment by r-j-arnold** [comment]
@pherterich  Following from your review:

> Agree with @KirstieJane's point on RDM, we can cover that and this chapter can just mention something along the lines of "you should share your data in a form that makes it re-usable to others, check out the RDM chapter to learn how to do so". I can grab your content and shove it into a file on my fork as a starting point for the RDM chapter.
> 
> Similar for the collaboration for GitHub, though that can stay in here to start with.
> 

Grabbing the content whenever you're ready to start writing the chapter's fine.

> I personally would restructure the OA section, take out some of the current content and add other stuff in (I don't think anyone still talks about gratis or libre OA, but there's plenty of conversation about green, gold, platinum and diamond). I can make an attempt to rewrite once this is merged if you'd like.
> 

This isn't something I know much about so yeah, if what I've come up with is out of date I'm happy for you to rewrite it on another pull request once this is merged.

> The summary mentions Open Notebooks (they get merged with data here and there and we could do that if wanted) and Open Research Software which actually don't show up in the chapter. I'd especially think some paragraphs around the difference between Open Source and Open Research Software would be useful, I feel that gets conflated a lot.
> _Update:_ This could help, haven't watched it yet though https://www.youtube.com/watch?v=1fwGliIyAZs&
> 
 I've added a section on open notebooks, and made the open source section more clearly about open source software (I don't think it's important to specify research software, so right near the top I've also changed "Open Research Software" to "Open Source Software".

> Some definitions of open science also include open hardware (http://openhardware.science/). I'm wondering if it's worth including as the data for data science will need to come from somewhere and being open in the equipment collecting the data can only be good.

I've added a section on open hardware.

Take a look and let me know what you think/if it's ready for approval and moving on to low-level reviews.

**Pull request merged**
