### PR TITLE
updating reproducible-definition-grid figure resolves issue #3048

### LINKED ISSUE #3048: Improving the reproducible definition figure
### Summary

The current version of the [figure 6](https://the-turing-way.netlify.app/reproducible-research/overview/overview-definitions.html) could be a bit better at communicating the point it is trying to get across. Specifically the distinction between the different definitions as characterized by the combination of same/different data & same/different analysis. The current use of colour does not emphasize this - the key message of the figure. In addition the original alt text whilst reasonable fails to convey the key message of the figure, which is to re-iterate the connection of each word to its combination of same/different data & same/different analysis.

reproducible-definition-grid-original

alt text: "Grid with the characteristics of reproducible, replicable, robust and generalisable research"

### What needs to be done?

To address this I propose:
- [x] Encoding the data, analysis, same and different in the colours of the representations of data and analysis.
- [x] Removing the current green colour which does not map to a meaningful encoding
- [x] Updating the alt text to better convey the content of the figure

This is my updated figure:

reproducible-definition-grid

I've encoded 'analysis' as green, 'data' as blue, 'same' as light shades, and 'different' as dark shades. The colours used from colourbrewer's 'colourblind safe' 4 colour qualitative differences palette: https://colorbrewer2.org/#type=qualitative&scheme=Paired&n=4 so should be accessible. I also filled in some of the hollow shapes in 

alt text: "Grid with the characteristics of: Reproducible; same data, same analysis. Replicable; different data, same analysis. Robust; same data, different analysis. And generalisable; different data, different analysis; Research"

This alt text is more descriptive, the punctuation may seem a little odd but I tested this with text-to-speech tools to see what would yield the correct intonation and this is what worked best. The contents of Parentheses for example where ignored by some tools.

License information, alt text, and other details are also included in the svg version's file metadata.

(I'll be resolving this with a PR shortly - following discussion on slack wanted to open an issue first as I find they are easier to search than merged PRs)

### PR DESCRIPTION
**Pull request by RichardJActon**
### Summary

Fixes #3048 

This PR existed solely to address #3048 and this issue contains a detailed description of the proposed changes and their motivation.

### What should a reviewer concentrate their feedback on?

Is this change sufficient or is there anything else I need to change for this change to be applied in the book?

### Acknowledging contributors

- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: @RichardJActon

### CODE REVIEW

**Review by Arielle-Bennett — COMMENTED** [review]
Hey @RichardJActon could you update the alt text in https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/reproducible-research/overview/overview-definitions.md as well? I can't see it in the files changed here :)

**Comment by RichardJActon** [comment]
> Hey @RichardJActon could you update the alt text in https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/reproducible-research/overview/overview-definitions.md as well? I can't see it in the files changed here :)

Oops forgot to change that thanks!

**Review by Arielle-Bennett — APPROVED** [review]
looks great thank you @RichardJActon !

**Review by Arielle-Bennett — APPROVED** [review]

**Comment by KirstieJane** [comment]
Looks great to me! ✨

**Comment by RichardJActon** [comment]
FYI I've got the book building locally now so I shouldn't be holding up the CI on syntax errors in the future.

**Comment by Arielle-Bennett** [comment]
Merging as I don't think @RichardJActon will have write access yet as a first time contributor - thank you for your work though 

@all-contributors please add @RichardJActon for ideas

**Pull request merged**
