### PR TITLE
Update open-scholarship.md

### LINKED ISSUE #3063: Correct a broken link on the 'open scholarship' page
# A Beginner's Guide to Contributing to _The Turing Way_

This is a guide for getting started with contributing to The Turing Way during the Book Dash in May 2023. We're so glad to have you here! 🎉 

Below you'll find some instructions for contributing to the project. If you have any questions, please let @aldenc, @Arielle-Bennett, @AlexandraAAJ know on Zoom so that we can assist you.

## Summary
In the chapter for [open scholarship](https://the-turing-way.netlify.app/communication/open.html#cm-open-scholarship), the link citing 'open scholarship' is incorrect.

## Guide to Contribution 

1. Comment on this issue with the people working on the issue using their Github usernames.

1. Visit the relevant part of the repository to address this issue: https://github.com/alan-turing-institute/the-turing-way/blob/main/book/website/reproducible-research/open/open-scholarship.md

3. Find line 4 to find the phrase `Open research and its subcomponents fit under the umbrella of a broader concept - open scholarship [{term}`def<Open Scholarship>`].`

4. Click 'Edit this file'. 

5. Delete the phrase `Open research and its subcomponents fit under the umbrella of a broader concept - open scholarship [{term}`def<Open Scholarship>`].` Change the phrase to `Open research and its subcomponents fit under the umbrella of a broader concept - open scholarship`, deleting the syntax at the end of the phrase.

6. Click 'Preview' to check that the changes look the way you'd like them too!

7. Navigate to 'Propose changes' at the bottom of the page: edit the title and the description of the issue to describe your update to the community.

8. Click 'Propose changes'. You will be redirected to a new page to make a Pull Request within the project. 

9. There will be template text in the Pull Request as is: don't worry too much about that! Erase the text, then link the issue tag using a`#`. You can find the issue number next to the title of this issue.  

Example: `this pull request fixes #3063`

10. Click 'Create Pull Request'! Congratulations! 🎉 

11. A reviewer will review your pull request, and ask you if you need to make any changes before it can be approved.

12. There are a number of checks your project will undergo: to check for merge conflicts, inclusive language, and formatting issues. Wait until those checks are complete before merging.

13. Once your pull request is approved and the checks are complete, you can merge your change into the repository! ✅

### PR DESCRIPTION
**Pull request by aldenc**
remove broken link

### Summary

removed a broken link

Fixes #3063

### List of changes proposed in this PR (pull-request)

removed text

### What should a reviewer concentrate their feedback on?

does the text render correctly 

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: @robbykha @mkhslaa

### CODE REVIEW

**Review by Arielle-Bennett — APPROVED** [review]
These changes look good to me!

**Comment by Arielle-Bennett** [comment]
@all-contributors please add @robbykha and @mkhslaa for editing


https://github.com/all-contributors

**Comment by Arielle-Bennett** [comment]
@all-contributors please add @robbykha and @mkhslaa for 'content'

**Review by aleesteele — APPROVED** [review]
Great! Thanks @aldenc

**Comment by malvikasharan** [comment]
@all-contributors please add @robbykha for 'content'

**Comment by malvikasharan** [comment]
Flagging that having multiple users in the same line with all-contributor comments create conflicts in contributors file, better option is to have separate comment like this
> @all-contributors 
> please add @robbykha for 'content'
> please add @mkhslaa for 'content'

**Pull request merged**
