### PR TITLE
Fix link to Continuous Integration chapter

### PR DESCRIPTION
**Pull request by spier**
### Summary

While reading the contribution guidelines in `CONTRIBUTING.md`, I noticed a broken link.

### List of changes proposed in this PR (pull-request)

* Fix link to "Continuous Integration chapter"

### What should a reviewer concentrate their feedback on?

- [ ] Did I use the correct way to specify the link in this markdown file? I went by example from other instances in the file.
- [ ] Everything looks ok?

### Acknowledging contributors

_Whether anything needs to get done here depends on if #3174 (my first contribution) is merged before this._

- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: 

https://github.com/spier

### CODE REVIEW

**Review by da5nsy — APPROVED** [review]
Good spot! Thanks! 👏
Looks like this fixes something I messed this up in #3014 😬

**Comment by spier** [comment]
Cool. Btw I saw your talk at FOSSBackstage. So you might consider this PR a side effect of that ;)

**Comment by da5nsy** [comment]
I've just invited you as a collaborator on the repo so you should be able to hit merge now @spier 😄

**Comment by spier** [comment]
Wow, that's exciting! Doing that just now.

**Comment by da5nsy** [comment]
We can do that now!

@all-contributors please add @spier for bug

Documentation is here: https://github.com/alan-turing-institute/the-turing-way/blob/main/CONTRIBUTING.md#recognising-contributions

Once the bot has added you to the table of contributors, that is copied over into the book on a weekly basis semi-automatically ([though this is likely changing soon](https://github.com/alan-turing-institute/the-turing-way/pull/3093)).

**Pull request merged**
