### PR TITLE
Preview/test Plausible analytics on this branch

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

Tests #1660 #431

* Creating a new test for Plausible

### List of changes proposed in this PR (pull-request)

* Plausible URL: TBA
* User: theturingway@gmail.com
* Ask Malvika for the password by pinging her [on Slack](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw)

### What should a reviewer concentrate their feedback on?

- [ ] The test looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@paulowoicho I wonder if you would have a chance to test this one as well. 🌻

**Comment by paulowoicho** [comment]
Yup @malvika, I will take a look later today!

**Review by paulowoicho — COMMENTED** [review]
I tried clicking around to see if my activity got logged to the dashboard, but it doesn't seem to be working. 

Screenshot from 2021-02-26 18-11-25

The JavaScript code seems fine, so the behavior is quite strange

**Comment by malvikasharan** [comment]
I tried a few more times, but I could not get the data collected :( I will try to find someone who knows about Plausible and can help with this error.

**Comment by malvikasharan** [comment]
We tested Matomo and are in the process of getting a legal approval to use that.

**Pull request closed without merging**
