### PR TITLE
Fixed dead link to eScience Center language guides

### PR DESCRIPTION
**Pull request by tpronk**
### Summary

Fixes a dead link to the eScience Center language guides.
* Old (dead) link: https://guide.esciencecenter.nl/best_practices/language_guides/languages_overview.html
* New (working) link: https://guide.esciencecenter.nl/#/best_practices/language_guides/languages_overview

### List of changes proposed in this PR (pull-request)
* Dead link fix

### What should a reviewer concentrate their feedback on?
* Check if the new link points to the right page

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: GitHubID = 8987504, Profile = https://github.com/tpronk

### CODE REVIEW

**Review by da5nsy — APPROVED** [review]
Thank you for the contribution @tpronk!
All LGTM!

**Comment by da5nsy** [comment]
@all-contributors please add @tpronk for bugs

**Comment by da5nsy** [comment]
Feel free to go ahead and hit merge @tpronk! 👍

**Comment by tpronk** [comment]
Cool! I don't think I've got the rights to hit merge though @da5nsy

**Comment by da5nsy** [comment]
Oop, sorry, my bad!

**Pull request merged**
