### PR TITLE
Added docker-compose back in -- fixes #1016.

### LINKED ISSUE #1016: docker-compose file mentioned in CONTRIBUTING.md#Local-development is missing
### Summary

The instructions for running a local development server in the CONTRIBUTING guide mention a `docker-compose.yml` file, that file is missing.

### What needs to be done?

To fix this, I believe there's just two things:

- [ ] Add the file back; and
- [ ] Make sure the local environment still works.

### Who can help?

* masonlr

---

### Updates

No updates yet.

### PR DESCRIPTION
**Pull request by chadsgilbert**
The instuctions for Local development in CONTRIBUTING.md mention that there is a `docker-compoe.yml` file in `book/website`, but it's no longer there on `master`.

The `docker-compose.yml` file was added by Lachlan Mason in PR #592 (commit 49c8ee4988987bdc4c0724679d8945bd09dae97d), but then got dropped in commit 7f20f66fb224f0265beda8e7cca18eaf7ed08d87, which was labelled "MASSIVE COMMIT". One has to assume this was unintentional.

This commit just adds Lachlan's compose file back.

### Summary

Fixes #1016

### List of changes proposed in this PR (pull-request)

* Add the previous `docker-compose.yml` file.

### What should a reviewer concentrate their feedback on?

Is this `docker-compose.yml` file still desired? It looks ike it's been missing for a while. THe other option could be to remove reference to it form CONTRIBUTING.md.

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: @chadsgilbert

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thank you for raising the issue and PR @chadsgilbert. Can you please join our Gitter: https://gitter.im/alan-turing-institute/the-turing-way. I am hoping that those involved in this massive commit would be able to clarify  this.

**Comment by sgibson91** [comment]
The massive commit was updating the Juptyer Book itself - maybe the Docker compose file isn't needed anymore? I've never actually gone through the local development instructions - I've just opened a PR and used Netlify's deploy preview to see how the book would look

**Comment by KirstieJane** [comment]
@martinagvilas or @choldgraf - can you help us out with this? (Sorry I'm not much help here!)

**Comment by martinagvilas** [comment]
Hi! I'm pretty sure the docker-compose file is indeed something that jupyter-book does not contain by default, but @choldgraf of course will know best. I don't know if jupyter-update deletes this kind of files intentionally, or if its a bug, @choldgraf? 

Regardless, I think the docker-compose is a nice addition (the alternative would be to run the steps outlined here: https://jupyterbook.org/guide/publish/book-html.html#Docker, instead of docker-compose up). I don't know why netlify deploy is failing though. I'm not really familiar with it, but I can explore the issue further if no one knows why.

**Comment by sgibson91** [comment]
Thanks @martinagvilas! I think the build failure is a problem on netlify's side. The logs say "Error scheduling build". I don't know how to restart it though :/

Off topic: @malvikasharan here's a case of Travis acting up not due to the all-contributors bot!

**Comment by choldgraf** [comment]
Hey all - I'm not sure about the docker-compose piece, I believe that @emdupre did a lot of the Docker work in there, so maybe she knows.

That said, at this point I would recommend trying out the beta version of the new Jupyter Book (beta.jupyterbook.org). I think it will be **much** easier to install and run than the old version, because it no longer uses Jekyll which is the main reason we had to use Docker (since Jekyll is such a pain to install). I am happy to step somebody through it if they are interested!

**Comment by emdupre** [comment]
Hi all -- 

the Docker image was really designed for local deployment, but since you're using Netlify you should be able to follow [the instructions here](https://jupyterbook.org/guide/publish/netlify.html) to get the book up and running ! The reason that you don't need to worry about Docker when deploying on Netlify is that they have their own Ruby environment that you can use just by specifying the build steps described :smile_cat: 

Definitely a +1 on looking into the Sphinx build system, though !

**Comment by martinagvilas** [comment]
I would be happy to try out and help with the transition to the Sphinx beta version if the turing-way team thinks it's a good idea 😄

**Comment by choldgraf** [comment]
@martinagvilas let me know if you'd like to hop on a chat and I could show you around the new build system, I would be happy to do so

**Comment by martinagvilas** [comment]
@choldgraf that would be amazing, thanks! whenever you have spare time for showing me let me know and we can chat via gitter or slack (or whatever else) 🚀

**Comment by chadsgilbert** [comment]
> Thanks @martinagvilas! I think the build failure is a problem on netlify's side. The logs say "Error scheduling build". I don't know how to restart it though :/
> 
> Off topic: @malvikasharan here's a case of Travis acting up not due to the all-contributors bot! #1002

Glad to hear this isn't my fault. It was quite puzzling last night when these checks failed!

**Comment by choldgraf** [comment]
@martinagvilas cool! which time-zone are you in? We can set up a time to chat.

Actually, even better would be if you tried to follow the documentation at `beta.jupyterbook.org` and then when we meet you could also give feedback about what is confusing etc :-)

**Comment by martinagvilas** [comment]
@choldgraf Great! I will go over that documentation and ping you when I finish. I'm in Germany, so timezone GMT+2

**Comment by KirstieJane** [comment]
Just a little comment to say thank you everyone for thinking through this. @Martinagvilas & @choldgraf - I would LOVE IT if you met up (along with anyone else who wants to play around with this) to see whether we can switch to the new jupyterbook! I’m happy for us to go across early if it’s working well 🥰🥰🥰

**Comment by choldgraf** [comment]
FWIW, I do think that, at this point, the new jupyter book is ready to be adopted. It may still have some bugs here and there, and there is certainly much to be improved, but I think if anything just the simplified build process would be worth switching a bit early.

@martinagvilas wanna have a phone call in my morning / your evening in the next few days? I'm on California time...

**Comment by martinagvilas** [comment]
@choldgraf sounds good! I can do tomorrow or Monday (or any day after Wednesday) during my evening. Let me know what works for you 🚀

**Comment by choldgraf** [comment]
@martinagvilas I'd be happy to chat tomorrow if you like (I know it is the weekend, but...I have nothing to do 🤣😭)

Shall we chat at, say, 9am Pacific time on Saturday? I can post a zoom link here that I will take down once the chat is over so we don't get zoom-bombed?

**Comment by martinagvilas** [comment]
@choldgraf haha that makes us two! The time works perfectly, looking forward!

**Comment by choldgraf** [comment]
hey @martinagvilas (and anybody else that's around, I'm hanging out in here: https://berkeley.zoom.us/j/7633159873?pwd=QllpaDFoZDZhZ2VpTWVwWlFjb0xoUT09)

**Comment by martinagvilas** [comment]
hey @choldgraf thanks again for the chat! Is there a way to share the hackmd of the conversation through here? I accidentally closed the link and cannot find it again 🤦‍♀️

**Comment by choldgraf** [comment]
https://hackmd.io/BXuwmAZ7TymhF1UxpoBPaQ 👍

**Comment by malvikasharan** [comment]
Thank you so much @martinagvilas and @choldgraf for the notes. 🙌🌸

**Comment by martinagvilas** [comment]
Hey @malvikasharan, that sounds great! I will take a look into #977 

Do you want me to wait until you merge the new structure and then I open a new issue upgrading jupyter-book? Or did you want to do the upgrade in the same PR? 

A thing to keep in mind is that the toc file structure in the new jupyter-book is slightly different. If you want to have the upgrade in the same PR we need to change that toc file once it looks ready for the new structure. If we do the upgrade in a new PR, I can map whatever structure you have in the toc you have written to a new toc and do the upgrade. 

The logo can be definitely included! I have been playing with this already. I will explore what happens with intermediate folders and let you know 🚀

**Comment by malvikasharan** [comment]
Martina and I had a discussion that it will be better to have the Jupyter Book update first and then do the second PR merged for the book restructure to keep the history understandable. Both this merge will have massive TOC change, however, for people outside this process, it will be useful to follow these changes separately to avoid assumption on what comes with Jupyterbook update.

To merge the restructure we will also have the link redirections sorted with the upgrade.

**Comment by malvikasharan** [comment]
I just want to update the original docker related changes that have been integrated into the project. So this PR can be renamed to best reflect the ongoing discussions around Jupyter update.

@martinagvilas Can you please help me edit this?

**Comment by martinagvilas** [comment]
@malvikasharan I think that since this PR introduces a docker-compose that will be not be used in the new jupyter-book version (docker should not be necessary at all then) we can either merge this PR  or close it and reference it in the new jupyter-upgrade PR.

I would actually go for the first option since the file @chadsgilbert is bringing back is super useful for those still using the current jupyter-book version in the turing way. Even when the jupyter-book upgrade is ready and this file gets deleted, it would be nice to have it incorporated in the git history nevertheless.

But I wouldn't rename it since we can't base the jupyter upgrade in this PR. 

What do you think?

**Comment by malvikasharan** [comment]
Sounds good. We can close this issue and move the communication here to a new issue. Thanks again for clarifying that @martinagvilas.

**Comment by chadsgilbert** [comment]
Thanks for all the great discussion on this everyone. Exciting to hear you'll be upgrading JupyterBook. It looks like the location of this `docker-compose` file will conflict with that. Is that right?

How would you all feel if I close this PR and put in another one instead to remove the section that mentions it from  `CONTRIBUTING.md` instead? I am interested in the idea of being able to run in docker, but having read the discussion that's ensured, I don't believe this `docker-compose` file will be the right way to do it.

**Pull request closed without merging**
