### PR TITLE
Kw binderhub agenda

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Quick fix on the agenda as discussed in the meeting.

### What should a reviewer concentrate their feedback on?

- [ ] Check that it makes sense!

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by KirstieJane** [comment]
AH - this looks gigantic because the `SG/binderhub-workshop` branch is behind `master`.....@sgibson91 if you can sync your branch w master this should just look like a tiny change!

**Comment by sgibson91** [comment]
I did:
```
git checkout master
git pull
git checkout SG/binderhub-workshop
git merge master
git push origin SG/binderhub-workshop
```
🤷‍♀️

**Comment by sgibson91** [comment]
Why not just merge to master? `agenda.md` wasn't made in my branch.

**Comment by KirstieJane** [comment]
The honest answer @sgibson91 is “but it SHOULD” work this waaaaay!

I don’t know why it didn’t update when you synced with master. I changed the base of this PR, and then changed it back again and now it’s doing what I thought it would do.

I think we found a GitHub gremlin 🐙

It’s quite helpful to have the update to the agenda in your PR as it develops for the workshop, but if you’d rather merge directly to master just let me know and I'll change the base again 😃

**Comment by sgibson91** [comment]
It's fine now there aren't a million commits that would be added! 😂

**Pull request merged**
