### PR TITLE
[Work in Progress] Update BinderHub workshop 2

### PR DESCRIPTION
**Pull request by sgibson91**
### Summary

This PR is a reconstruction of #762 

Addresses #694 

This PR is implementing improvements to the Zero to BinderHub workshop recommended through feedback from RSE Con UK 2019.

### List of changes proposed in this PR (pull-request)

- See check list in issue #694 for changes to the actual workshop.
- A hackmd template has been added for collecting feedback/distributing links during the workshop

### What should a reviewer concentrate their feedback on?

- [x] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@sgibson91 Thank you for recovering it! And sorry for rushing.

**Comment by sgibson91** [comment]
No problem @malvikasharan, I learned some new git along the way! 🚀

**Comment by sgibson91** [comment]
No problem @malvikasharan, I learned some new git along the way! 🚀

**Comment by sgibson91** [comment]
This PR has lost its head, looks like its coming from `unknown repository`. Closing in favour of #1552

**Pull request closed without merging**
