### PR TITLE
Create Bham_HackerWithin

### PR DESCRIPTION
**Pull request by pherterich**
### Summary

Trying to create a folder for my slides following @KirstieJane 's suggestions

Fixes #212 

### List of changes proposed in this PR (pull-request)

* Create a folder (if I got it right)

### What should a reviewer concentrate their feedback on?

- [ ] Correct me if I get it wrong please

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x ] all contributors to this pull request who wish to be included are named in [humans.md](humans.md).

### CODE REVIEW

**Comment by r-j-arnold** [comment]
Hi @pherterich, as far as I can tell this isn't right (but I could hvae just misunderstood what you're trying to do. If I'm right you're trying to make a folder called Bham_HackerWithin under conferences/presentations.

When I look in the conferences/presentations directory on this branch I don't see such a folder, but I do see a *file* called TuringWay_HackerWithin.pdf.

So if I understand what you're trying to to with the pull request you still need to create the folder in this directory so you can put the pdf in it and finish #212.

Have I got that right?

**Comment by pherterich** [comment]
yeah, realized that and fixed it. I uploaded the PDF but can't figure out how to move that into a folder through the interface. So now this is the upload of the slides and adding it to the readme rather than creating the folder.

**Comment by r-j-arnold** [comment]
I'm not even sure if it can be done via github @pherterich , but it would be no trouble for me to make the folder and commit it on this pull request if that would help?

**Comment by pherterich** [comment]
Feel free to give it a shot @r-j-arnold - it will take me a while to get around to try other approaches.

**Pull request merged**
