### PR TITLE
[WIP] BinderHub/JupyterHub Notes

### LINKED ISSUE #46: Linking Azure Resources and Services to Binderhubs

### LINKED ISSUE #47: Collate all documentation RE JupyterHub and BinderHubs
Notes on methods and issues in deployment of a BinderHub are being documented in `binderhub-notes.md`

#77

### PR DESCRIPTION
**Pull request by sgibson91**
A series of notes concerning the methods and issues encountered when setting up a BinderHub

will fix #46 
will fix #47

### CODE REVIEW

**Comment by sgibson91** [comment]
@pherterich @r-j-arnold All those commits we were wondering about before have turned up in this PR too. What's going on?! @KirstieJane ?

**Comment by r-j-arnold** [comment]
@sgibson91 That's weird, did you do any kind of pull/push/fetch/merge/upstream or has it just happened out of nowhere?

**Comment by sgibson91** [comment]
@r-j-arnold Out of nowhere I think I only pushed my own files

**Comment by r-j-arnold** [comment]
Ok so looking at the commits you're got all your commits + commits on master, but only up until 2 weeks ago. If you synched back then and forgot, but only now pushed 2+ weeks of your commits to this branch from your local to github then that would explain it. Roughly when did you last push your work to github?

**Comment by sgibson91** [comment]
I last pushed today

**Comment by r-j-arnold** [comment]
Do you remember when you last did a fetch upstream or a pull from github to your local? Also before you pushed to github today when do you remember roughly how long it was since you pushed  before that?

**Comment by sgibson91** [comment]
There's a gap in commits between 13th Dec and 7 days ago. I don't usually do fetch upstream, unsure of pull.

**Comment by r-j-arnold** [comment]
I *suspect* (may well be wrong) that this s what happened.

1. You made this pull request back in december and pushed to github so it had a copy of your work
2. On your local you continued to work and continued to make commits. Simultaneously work contiued on the alan turing main repo which you had not pulled from your local copy.
3. About 2 weeks ago you got your local copy up to date by pulling the changes that had been made to the alan turing copy of the repo.
4. Note that at this point you have a copy of all the work in the alan turing github, but the alan turing git hub does *not* have your work because you haven't pushed it.
5. Again you continued to make commits on your local copy, and work continues on the alan turing github. You do not have a copy of those subsequent commits because you haven't pulled htem into your local.
6. You push your work to github today.  This pushes all the work you've done + all the commits to the alan turing one you got and incorporated into your work in step 3.

From what you remember is that plausible?

**Pull request closed without merging**
