### PR TITLE
Update broken link

### PR DESCRIPTION
**Pull request by da5nsy**
Update broken link, as pointed out by user `wwhsiao` oh hypothes.is ([here](https://hyp.is/lDRhTAOOEey-4x-gvZjW3Q/the-turing-way.netlify.com/afterword/bibliography.html))

### CODE REVIEW

**Review by arronlacey — APPROVED** [review]
good spot @da5nsy

**Comment by arronlacey** [comment]
build fail related to [this issue](https://github.com/sphinx-doc/sphinx/issues/10291) ?

**Comment by da5nsy** [comment]
> build fail related to [this issue](https://github.com/sphinx-doc/sphinx/issues/10291) ?

Hoping that #2307 fixes this (seems to, but I'm no expert)

**Comment by da5nsy** [comment]
Waiting on #2313

**Comment by arronlacey** [comment]
looks good - I'll merge this.

**Pull request merged**
