### PR TITLE
Changed the cake emoji

### PR DESCRIPTION
**Pull request by SianC**
This addresses issue #2504

### Summary

Fixes issue #2504 

### List of changes proposed in this PR (pull-request)

Added the cake and tea emojis

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by BrainonSilicon — APPROVED** [review]
Looks great @SianC! Feel free to Merge

**Comment by SianC** [comment]
Hi @BrainonSilicon, I cannot seem to merge as I am getting this message "Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Review by EKaroune — APPROVED** [review]
great work - thanks!

**Comment by BrainonSilicon** [comment]
@aleesteele - checking some logic here. Was the `write` permissions issue the reason why we added contributors manually in the background during CarpentriesCon?

**Comment by aleesteele** [comment]
@BrainonSilicon: Yes! That's why we added people's github names to the repository at the beginning of the workshop, so that they have the ability to merge their own PRs, and have general write access for future contributions. 

This is the approach I would recommend, though I defer to what you two think is best!:
- Add folks to the repository with write access
- If they don't merge their own PRs within a certain period of time (say: 1 week?), feel free to merge on their behalf.

**Comment by EKaroune** [comment]
@all-contributors please add @SianC for bug

**Pull request merged**
