### PR TITLE
delete figure list

### PR DESCRIPTION
**Pull request by da5nsy**
Enact #2834, perhaps temporarily, to proceed with #2838

### CODE REVIEW

**Review by bsipocz — COMMENTED** [review]
This indeed gets rid of the CI warning, but do we really want to delete the list, or keep it linked in a TOC, or maybe generate is automatically?

I would incline toward the last option, but don't know a way that works out of the box and does it.

**Comment by da5nsy** [comment]
> This indeed gets rid of the CI warning, but do we really want to delete the list, or keep it linked in a TOC, or maybe generate is automatically?
> 
> I would incline toward the last option, but don't know a way that works out of the box and does it.

I concur, but suggest we delete for now until we have a solution (otherwise all builds will fail)

**Comment by bsipocz** [comment]
If we need a workaround for CI, we can make it an orphan page, too. It's really up to whether an open issue about it or a workaround orphaned page (that could very much go out of date) is preferred by the community.

**Comment by da5nsy** [comment]
It's currently already very out of date

**Comment by bsipocz** [comment]
> It's currently already very out of date

OK, then it's an no brainer, it has to be an issue, and an automated tool.

**Review by bsipocz — APPROVED** [review]

**Comment by bsipocz** [comment]
Thanks @da5nsy, and yay for green CI!

**Pull request merged**
