### PR TITLE
The easy way with Github chapter [Ready for review]

### PR DESCRIPTION
**Pull request by EKaroune**
### Summary

New chapter for the reproducibility book on onboarding novice Github users. It has been edited by Malvika and Paul. Formatting needs to be checked further and also the links to the figures.

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* [ ] Do any further changes to the content, if needed
* [x] check formatting of easyway.md
* [x] check formatting of easyway subchapters
* [x] check figure links work
* [x] check figure sizing is correct

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

* [ ] have I included all of the relevant content?
* [ ] are the figures clear?
* [x] do all the links work?

* [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by LauraCarter** [comment]
@EKaroune for the 'getting started with github' chapter (https://github.com/alan-turing-institute/the-turing-way/blob/Easyway/book/website/collaboration/easyway/sc2_getting_started_with_github.md), I think some of the materials from the Mozilla Open Leadership files might be useful to link to or reference: https://github.com/mozilla/open-leadership-training-series.
They are licensed under the MIT license, the same as the Turing Way, which I think (@malvikasharan please correct me if I am wrong!) means we can use/remix them as we like?

**Comment by paulowoicho** [comment]
I have made a few more commits to fix the broken image link and to ensure that the images do not appear distorted

**Review by EKaroune — COMMENTED** [review]
These changes look ok so please just approve them.

**Review by malvikasharan — APPROVED** [review]
Ready to merge this one too.

**Pull request merged**
