### PR TITLE
Fixes hyperlinking Malvika Sharan

### PR DESCRIPTION
**Pull request by hlapp**
### Summary

Fixes missing opening `[` for text to be hyperlinked.

### List of changes proposed in this PR (pull-request)

* Adds the missing `[`

### CODE REVIEW

**Comment by aleesteele** [comment]
Welcome to _The Turing Way_, @hlapp :) We're so glad to have you here. Thanks for catching this typo! I've approved, feel free to merge 🚀

**Review by aleesteele — APPROVED** [review]

**Comment by hlapp** [comment]
> We're so glad to have you here.

Happy to be here 🤩

> I've approved, feel free to merge

If you meant me to merge, I don't think I have permission to do so.

**Comment by aleesteele** [comment]
Woops! Just invited you to the repository. You should have write access now @hlapp, and can merge the PR :)

**Comment by hlapp** [comment]
> Just invited you to the repository.

Thanks, I humbly accept the honor 🙏 😊

**Comment by aleesteele** [comment]
Thank you for catching this fix! Would love to see you in a community space sometime, whether that's a coworking call, collaboration cafe, or our slack workspace 😊 
You can find some of the links here: https://hackmd.io/@turingway/demo-intro

**Pull request merged**
