### PR TITLE
Fixed formatting on rdm-resources, added header and chapter summary

### LINKED ISSUE #1404: [BUG] Add a top level header with a short overview of the chapter: research data management
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

# Summary of Issue

- Part of #1321 

_The Turing Way_ chapters are written in [MarkDown format](https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf). Each chapter has a header (top-level header denoted by single # - h1 tag) and subheaders (## - h2, ### - h3, #### - h4 tags). 

A standard expected format should follow `#` (h1 tag) -> `##` (h2 tag) -> `###` (h3 tag) and so on in sequence.

## What needs to be done

The [research data management's checklist subchapter](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-resources.html) doesn't have a top header (instead of starting from h1, they start at h2).

- [ ]  This subchapter needs a top header called 'resources' followed by a short summary of what the readers will read in the rest of the chapter (all the sections listed with h2 tag).
  - If this chapter's top header is fixed, the rest of the non-sequential markdown header errors will be solved (as currently, everything has second-level headers)

### Who can help

Anyone who would like to participate in Hacktoberfest or contribute to The Turing Way GitHub repository for the first time easier to do locally (by git) but not mandatory

### About Hacktober and The Turing Way

Hacktoberfest is a month-long celebration of Open Source Projects where the goal is to make 4 Pull Requests during the month.

#### A bit about Git
If you’re new to git then here are [some instructions](https://help.github.com/articles/signing-up-for-a-new-github-account/) to help you get going. Remember that you can ask us any questions you need to along the way.

A [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) (what Hacktober is measured on) lets you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

In this issue, we’ve outlined what needs to be done, and how you can go about addressing it. Once the issue has been addressed, you can submit a Pull Request for review (tell us what you’ve done) and we can incorporate it into The Turing Way.

We’ve also created this special Hacktoberfest tag to make it easy for you to find other places to contribute if you’re new.
In the spirit of Hacktoberfest, please only do a few of these to submit your PR so that we can learn and grow as a community together.

#### Our Community
We want to ensure that every user and contributor feel welcome, included, and supported to participate in The Turing Way community. We welcome all contributions to this project via GitHub issues and pull requests. Please read our [Contributors document](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md) and our [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md) while you engage in The Turing Way. As you start contributing to The Turing Way, don't forget that your ideas are more important than perfect pull requests. ❤️

If you have any questions that aren't discussed below, please let us know through one of the many ways to get in touch.

### PR DESCRIPTION
**Pull request by blee1710**
### Summary

Fixes #1404 

### List of changes proposed in this PR (pull-request)

* Added a top header to rdm-resources.md - 'Resources'
* Added a short summary to the chapter under the top header

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [X] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: blee1710

### CODE REVIEW

**Review by ArielleBL — COMMENTED** [review]
Hi there, thanks for contributing!

Issue #1404 asks for a header as well as a short summary of the chapter - can you add 2-3 sentences summarising what the chapter is about? 

We can help if you have any questions or you're not sure what to write.

**Comment by blee1710** [comment]
Hi, thanks for getting back to me!

I'm not too sure about what to add for the summary - would something along the lines of : 

"Below are some resources for you to refer to regarding research data management, as well as some tips as to where to continue your learning!"

Work well?

Also, I noticed that the glossary terms are not in separate lines. Should I add line breaks for clarity?

Thank you!

**Comment by malvikasharan** [comment]
I think that's a good suggestion. You can also elaborate a bit, for example by adding:
> In this subchapter, we have provided a simple checklist to help you with managing your research data.
> There are also some resources for you to refer to regarding research data management and continue your learning!

**Comment by blee1710** [comment]
Thank you @malvikasharan!

I've pushed the changes in my repo.

**Comment by malvikasharan** [comment]
I will leave this for @ArielleBL to review! I am sure she can help with making the summary more descriptive. 🙌

**Review by ArielleBL — COMMENTED** [review]
Hi @blee1710 this is looking good! I've expanded on your second sentence a little more so that it is very clear what people will find below. If you would like to make these changes I can approve this (thanks for your patience over the weekend!)

> In this subchapter, we have provided a simple checklist to help you with managing your research data.
We have also listed suggested chapters to read next that build on the research data management chapter, external links for further reading on specific topics, and a glossary of terms in this chapter.

**Comment by blee1710** [comment]
Hi @ArielleBL , thank you so much for your help! 

I've made the necessary changes and pushed them. 

Thank you!

**Review by ArielleBL — APPROVED** [review]
Nice work @blee1710 ! Thank you so much for contributing :)

**Comment by malvikasharan** [comment]
@all-contributors please add @blee1710 for typo fixing.

**Comment by malvikasharan** [comment]
@all-contributors please add @blee1710 for bug fixing.

**Pull request merged**
