### PR TITLE
[Ready for review] Address remaining issues for Make chapter (closes #409)

### LINKED ISSUE #409: Remaining issues for the Make chapter
### Summary

As requested in alan-turing-institute/the-turing-way-book#21 I'm opening an issue in this repo with the remaining todo items for the Make chapter.

### What needs to be done?

Known to do items:

- [x] 1. Add a glossary
- [x] 2. Add more images (e.g. from the result pdf in the tutorial)
- [x] 3. Move some of the links in the Further Reading to the Bibliography
- [x] 4. Provide proper syntax highlighting (? - not sure how to do this in JupyterBook)
- [x] 5. Finalise/Remove TOC (it's already in the sidebar in Netlify, is it needed?)
- [x] 6. Add paragraph on Snakemake under Alternatives to Make (see alan-turing-institute/the-turing-way-book#25)
- [x] 7. Move the Make tutorial repo GjjvdBurg/IntroToMake to the alan-turing-institute organisation.
- [x] 8. Expand more in the big_data section of the chapter, to increase usefulness as reference
- [x] 9. Add reasons for using make raised in [this comment](https://github.com/alan-turing-institute/the-turing-way-book/pull/25#issuecomment-486149112)
- [x] 10. Add ``sudo`` to installation instructions
- [x] 11. Double-check spelling and writing (see also [this comment](https://github.com/alan-turing-institute/the-turing-way-book/pull/25#issuecomment-486149112))

Finally, while I wrote the tutorial from scratch, I later discovered that there are several blog posts online that also describe the use of Make for reproducibility. It might be useful to include these in the bibliography. These links are:

- https://kbroman.wordpress.com/tag/reproducible-research/
- http://zmjones.com/make/
- https://bsmith89.github.io/make-bml/
- https://kbroman.org/minimal_make/
- http://stat545.com/automation04_make-activity.html

### Who can help?

* Anyone who knows about syntax highlighting in Jupyter Book can help with that issue.
* Anyone who can answer whether or not the TOC is needed
### Updates

* Based on the review in alan-turing-institute/the-turing-way-book#25 todo items 8-11 were added above.
* A bugfix branch is maintained at alan-turing-institute/the-turing-way-book#26. To do items that are fixed in that branch will be marked completed in the above checklist.

### PR DESCRIPTION
**Pull request by GjjvdBurg**
Please see alan-turing-institute/the-turing-way-book#26 for detailed commits.

### Summary

Fixes #409 (Remaining issues for the Make chapter).

### List of changes proposed in this PR (pull-request)

- This PR fixes all the issues listed in #409. 
- It adds a "Debugging Makefiles" and (advanced) "Canned Recipes" section.

### What should a reviewer concentrate their feedback on?

The main text of this chapter has already been reviewed by @sje30 in [this comment](https://github.com/alan-turing-institute/the-turing-way-book/pull/25#issuecomment-486149112). However, the following sections could benefit from additional reviewing:

- [ ] Section "Makefile no. 5" has been clarified and is useful as reference
- [ ] Section "Debugging Makefiles"
- [ ] Section "Advanced: Generating Rules using Call" is a useful addition for advanced users and its place in the appendix is appropriate.

### Acknowledging contributors

- Thanks to @sje30 for the initial review of the Make chapter that inspired many improvements!

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hey @GjjvdBurg! Thanks so much for this! I know the team are pretty busy on organising the Book Dash events this week, but we'll try to get some reviews in in the next few days 😸

**Comment by sje30** [comment]
I can read the revised version, but wont be til end of next week - would that be okay?

**Comment by GjjvdBurg** [comment]
Works for me, thanks @sje30!

Btw, would it be better to call the chapter "Make" or "Reproducibility with Make", since the Turing Way isn't just about research practices?

**Comment by rainsworth** [comment]
Hello! Just following up - @sje30 are you still ok to review this? Just let me know when y'all are happy with the chapter and we can get it approved/merged! Thank you both for all your contributions to the book, really appreciate this chapter 👏 

There also appear to be some merge conflicts - are you ok to resolve? Thanks!

**Comment by sje30** [comment]
hi Rachael, Gertjan,

am happy to read it again - will be on a train on Wed, which would make
for ideal reading.  Is it possible for someone to point  me to a pdf/html
version to read (I'm too old-fashioned to make my way through reading
it on github!)

Stephen

**Comment by rainsworth** [comment]
> hi Rachael, Gertjan, am happy to read it again - will be on a train on Wed, which would make for ideal reading. Is it possible for someone to point me to a pdf/html version to read (I'm too old-fashioned to make my way through reading it on github!) Stephen

Thank you @sje30! You can click the `Details` link next to the `deploy/netlify — Deploy preview ready!` check by the CI to see the book build in html with the current PR.

**Comment by sje30** [comment]
perfect!

**Comment by sje30** [comment]
I have just read through the revised chapter (albeit online, so may have missed a few things that I normally see only in print!).  The chapter is excellent.  Highly readable, and I am happy with the revisions.  Approve!

**Comment by GjjvdBurg** [comment]
That's great to hear! Thanks a lot for the review @sje30! 

@rainsworth I'll add a commit to resolve the merge conflicts today. Also, should the chapter be renamed as I suggested above? "Reproducibility with Make" or simply "Make"?

**Comment by rainsworth** [comment]
"Reproducibility with Make" sounds great! I will go ahead and approve this PR and you can merge it in when you are ready! (I'll double check you have write access to do so.)

Thank you so much @GjjvdBurg and @sje30 for your contributions with this chapter! 👏

**Pull request merged**
