### PR TITLE
[quick-fix] Website update

### PR DESCRIPTION
**Pull request by LouiseABowler**
### Summary

A couple of additions to the proposed website content. Contributes to #41.

### List of changes proposed in this PR

* Add workshop titles and sign-up links. ~~At this point, I haven't included a blurb but can add/borrow one from the promotional emails later.~~ Edit: Workshop descriptions added after feedback from @sgibson91 and @r-j-arnold.
* Add link to newsletter sign-up.
* Add content for a widget describing the contrinutions of the Research Engineering Group. This will show up as a small extra section at the bottom of the page (see examples [here](https://www.turing.ac.uk/research/research-projects/evaluating-homomorphic-encryption) and [here](https://www.turing.ac.uk/research/research-projects/security-cloud)).

### What should a reviewer concentrate their feedback on?

* @sgibson91, could you read over the REG widget section as I've written a sentence about your work on the BinderHub?
* The other changes are pretty small and the rest of the text was approved in #62, but another pair of eyes looking over it would still be welcome :)

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [humans.md](humans.md).

### CODE REVIEW

**Comment by r-j-arnold** [comment]
@LouiseABowler Looks good, one thing, blurbs for the workshops are available on the eventbrite, it may be worth adding them in here too?

**Comment by LouiseABowler** [comment]
Wow, you're both quick - thanks @sgibson91 and @r-j-arnold!

I thought bringing both blurbs in from the Eventbrite pages would make that section too long compared to the rest of the website. What do you think of taking part of it? Perhaps the paragraphs beginning "During this free workshop..." and the bullet points?

**Comment by r-j-arnold** [comment]
Yeah, part of it sounds perfect, i agree the whole thing would be too much.

**Comment by sgibson91** [comment]
(Actually, thought I was slow since git emails go to a sub-dir and I'm not notified 😂)

I think the second paragraph and the bullets would be great

**Comment by LouiseABowler** [comment]
I've added those descriptions (thank you @rosiehigman for preparing them!) and a short sentence introducing Binder. Is it clear enough what Binder is or should I add more?

**Comment by r-j-arnold** [comment]
Looks good to me, happy for you to go ahead and merge

**Comment by sgibson91** [comment]
Yep, I think that's the most succinct explanation I've seen of Binder yet!

**Pull request merged**
