### PR TITLE
[Ready for review] Open research

### LINKED ISSUE #504: Open Research chapter - fix content overview
### Summary

After a successful restructure of the chapter, the content overview now needs fixing as the links have been moved

### What needs to be done?
- [ ] Fix all the links to match the restructured content (see [contributing guidelines](CONTRIBUTING.md) for instructions on how to add relative links)

### Who can help?

Anyone!

### PR DESCRIPTION
**Pull request by PranavMahajan25**
### Fixes links in content overview of Open Research chapter

Fixes #504 

*After a successful restructure of the chapter, the content overview needed fixing as the links have were moved. The changes proposed fix all the relative links in the content overview.*

### Acknowledging contributors

Pranav Mahajan

### CODE REVIEW

**Comment by rainsworth** [comment]
Thanks @PranavMahajan25, we'll get this reviewed as soon as we can! 🎉

**Comment by PranavMahajan25** [comment]
Noob doubt here, but do I have to keep my open-research-links branch (on my fork) updated with all recent changes on the-turing-way upstream master branch at the time of merging the Pull request? 

Because the main repo gets many commits daily, even hourly sometimes, it might be possible that it shows my branch is 'x' commits ahead and 'y' commits behind the-turing-way master branch. ( 'x' being the changes I made, 'y' due to commits on the main repo by other people.)

**Comment by rainsworth** [comment]
> Noob doubt here, but do I have to keep my open-research-links branch (on my fork) updated with all recent changes on the-turing-way upstream master branch at the time of merging the Pull request?
> 
> Because the main repo gets many commits daily, even hourly sometimes, it might be possible that it shows my branch is 'x' commits ahead and 'y' commits behind the-turing-way master branch. ( 'x' being the changes I made, 'y' due to commits on the main repo by other people.)

Hi @PranavMahajan25 - yes, you have to keep your fork and branch updated. There are instructions on how to do this in our [Contributing Guidelines](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md#2-fork-the-turing-way-repository-to-your-profile). 

I'm also getting 404 errors for almost all the links in your pull request - possibly due to all the changes happening in the repo from the book dashes 🙈 Do you want to have another go? Thank you again for working on this! 👏

**Comment by PranavMahajan25** [comment]
Hi @rainsworth, thanks, yes I've followed the guidelines to keep my branch updated. I think it's showing error 404 in the readme files on Github because the links point to content in different folders as in openreasearch/01/...

But actually it seemed to work fine in the netlify deployment built with commit 6a486dd (and most of my recent commits are just updating branch). Is there a way to get the deployment link of the latest commit? (where you could review).

Because I figured out similar is the case with reproducibility.md, where the content is in different folders than in a single readme file. Thus even there, if you happen to click on the links in Github it'll show error 404, but is working fine in the website!
On a side note: Shouldn't there be uniformity regarding the structure of each chapter? (as in some are written in just 1 file while some distribute into folders 01,02,03 and so on)
Thanks

**Comment by rainsworth** [comment]
> Hi @rainsworth, thanks, yes I've followed the guidelines to keep my branch updated. I think it's showing error 404 in the readme files on Github because the links point to content in different folders as in openreasearch/01/...
> 
> But actually it seemed to work fine in the netlify deployment built with commit [6a486dd](https://github.com/alan-turing-institute/the-turing-way/commit/6a486ddc1bfb26e9f71604de9faeb101cd0ef3f3) (and most of my recent commits are just updating branch). Is there a way to get the deployment link of the latest commit? (where you could review).
> 

Ah yes, the links are working in the netlify preview. If you click `Details` next to the `deploy/netlify — Deploy preview ready!` check, you can see your most current book build.

> Because I figured out similar is the case with reproducibility.md, where the content is in different folders than in a single readme file. Thus even there, if you happen to click on the links in Github it'll show error 404, but is working fine in the website!
> On a side note: Shouldn't there be uniformity regarding the structure of each chapter? (as in some are written in just 1 file while some distribute into folders 01,02,03 and so on)
> Thanks

We are currently restructuring all the chapters into subsections like the Reproducibility chapter, they just aren't all done yet! You can keep up with the current progress in Issue #468 or even take a crack at restructuring yourself if you'd like!

Thanks again for contributing, let me know when you are ready for me to finish reviewing this PR and get it merged in!

**Comment by rainsworth** [comment]
Hi again @PranavMahajan25 - it turns out PR #639 is actually going to restructure the remaining chapters, so ignore my previous suggestion of having a go 😂 

I will approve this PR and get it merged, thanks again for your contribution 🎉

**Comment by PranavMahajan25** [comment]
Thanks! I got to brush up my Git skills through this one!

**Pull request merged**
