### PR TITLE
Add 2020-2022 Turing-TPS report to the communication folder

### LINKED ISSUE #1726: Add quarterly report on repo: check with Kirstie
### Summary

* For Turing quarterly report, The Turing Way drafts a document every few months
* It's a good record of what happens in the project and will be valuable to add them on the repo

### What needs to be done?

- [ ] Check with @KirstieJane if we should add the report online (I have all the reports for 2020)
- [ ] What kind of information should be removed (any specific information that is relevant only for internal use)

### Who can help?

* @KirstieJane and @Arielle-Bennett 

---

### Updates

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

Fixes #1726 

* Adding 2020 reports online

### List of changes proposed in this PR (pull-request)

- [ ] If the information can be shared as suggested (Thanks to @Arielle-Bennett for the first review)
- [ ] If anything is missing that should be added

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by Arielle-Bennett** [comment]
Hi @malvikasharan I'm happy with it if Kirstie is!

**Review by KirstieJane — COMMENTED** [review]
I've moved this to the `quarterly_reports` folder in `project_management` - I hope that's ok?

**Comment by KirstieJane** [comment]
Lets close this after the Research Fish submission I'm doing.... brb.... (not today, likely next week)

**Comment by malvikasharan** [comment]
Nudging @KirstieJane for review of this PR.

**Review by aleesteele — APPROVED** [review]
I saw the bot checking some things for language, but that was mostly due to the link names. This looks good to me - what a massive collection of work!

**Pull request merged**
