### PR TITLE
Add SVG images

### PR DESCRIPTION
**Pull request by da5nsy**
### Summary

Reducing the filesize of images rendered in the book means that the book can be browsed over poorer internet connections.
In the past, this has been achieved through lossy image compression (See #1313) but this reduces the visual quality of images.
For a subset of [the Scriberea images](https://doi.org/10.5281/zenodo.3332807) copies in SVG format exist (`zz-TheTuringWay-Scriberia-2019-20-SVG-where-available.zip`). 
This is a vector graphic format, which means that the images can be rendered at any size, with no loss of quality. 
For illustrations with lots of block colors, this format is also very storage efficient, often outperforming a lossily compressed jpeg.

### List of changes proposed in this PR (pull-request)

- Add the SVG images to the repo.
- Modify the references to all images such that those with SVG versions use the SVG version.
   - I do this by replacing all `filename.jpg` and `filename.png` with `filename.*`, in which case Jupyter Book chooses which to use, and it prioritizes SVGs.
   - I chose to do this rather than hard code the file extensions, so that it will be easier in the future to change the format of an image (one will not have to change the references to that image).
   - It also means that if jupyter book is used to generate a different type of output that doesn't allow SVGs, then it will fall back on the other filetype.
- Update the style guide to mention the `filename.*` usage.
- 37eb85d compresses the largest remaining bitmap images
   - in most cases, images were converted to indexed-color pngs (with ~10 locally indexed colors)
   - where gradients had been used, pixel dimensions were reduced (to long edge = 2000px) and jpeg compression was used

### What should a reviewer concentrate their feedback on?

- [ ] Check to see whether any images are broken
- [ ] Try different browsers and hardware to check that the SVGs render well
- [ ] Are there more vector graphics that could be added? For more recent images there are jpgs and pdfs (and the pdfs seem to be bitmaps, disappointingly)

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by da5nsy** [comment]
37eb85d closes #1313

**Comment by da5nsy** [comment]
_Reminder to **squash and merge** this PR, to avoid adding and then removing `legal-restrictions.svg`_

**Comment by da5nsy** [comment]
It would make me happy to also change over the images also used in `.github\config.yml` to be the SVG versions, since these would look ever so slightly nicer, but they are hardlinked to the zenodo versions, and the SVGs on zenodo are zipped so... 🤷

**Review by EstherPlomp — APPROVED** [review]
I think this looks good! Very handy and some of the pages indeed load faster now <3 Thanks Danny for going over everything - must have been a lot of work!

**Comment by da5nsy** [comment]
Thank you @EstherPlomp for reviewing! ❤️

**Pull request merged**
