### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by LauraCarter**
### Summary

Added our plan from our Open Canvas exercise as part of OLS-2, about the project that we are doing and the community that we want to build.

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: @BrainonSilicon

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Hi Laura. This looks great! Super excited for this project.

**Comment by malvikasharan** [comment]
@BrainonSilicon @LauraCarter should we approve this? 😀

**Comment by BrainonSilicon** [comment]
I would suggest two changes 
- taking our individual names out of the doc (TTW being a community project instead of people owning chapters) 
- there's sentence at the bottom of the proposed readme that possibly needs to be taken out

**Review by BrainonSilicon — CHANGES_REQUESTED** [review]
Hi Laura, 

Maybe run through the for edits ie. 
Line 9 "we are people <...>" 

Line 31 reads passively as does Line 37 and 42 and Line 50. 

There is also a draft/WIP of the last sentence that's repeated - maybe take a look at which sentence is the one you want to include.

**Comment by LauraCarter** [comment]
Thanks @BrainonSilicon! I have made the edits: not sure if you get a notification for that so I'm sending a comment as well.

**Review by BrainonSilicon — APPROVED** [review]
Awesome! This reads well 👍 Happy to approve.

**Pull request merged**
