### PR TITLE
Swap gitter links to Slack links in welcomebot and issue template list

### PR DESCRIPTION
**Pull request by sgibson91**
### Summary

This PR changes links to Gitter in the WelcomeBot and our list of issue templates to a Slack invite link, since that is now where the community chat happens.

### List of changes proposed in this PR (pull-request)

* `.github/config.yaml`
* `.github/ISSUE_TEMPLATE/config.yaml`

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
The build error was due to sphinx update which is not added in the Jupyter Book yet. I have updated your requirement.txt file. I hope that fixes it.

**Comment by sgibson91** [comment]
@malvikasharan The requirements wasn't up-to-date because my fork wasn't. I've synced and pushed.

**Review by malvikasharan — APPROVED** [review]
Thanks for updating this @sgibson91. I had not updated the Slack link here as they are valid only for 30 days, whereas Gitter is open.

However, we can set a recurring reminder to update the Slack link here every time I publish a newsletter to keep them up to date. What do you think?

**Comment by sgibson91** [comment]
So, followed the instructions for generating a link and compared it with one that was posted in gitter a while ago, and they were the same 😂

**Comment by malvikasharan** [comment]
Let's merge this! We can test in 30 days if need to keep updating. 🌺

**Comment by sgibson91** [comment]
I set myself a reminder to test

**Comment by sgibson91** [comment]
So I just checked the link on the new issue template works and it does!

**Pull request merged**
