### PR TITLE
Adjusting the look of Tables across the entire Book

### PR DESCRIPTION
**Pull request by paulowoicho**
### Summary

Fixes #<NUM>

Some tables in the Turing Way have headers that span multiple columns and/or rows. When written in markdown these are hard to read, and when written in plain HTML, they do not render as intended. 

This PR moves the styling for such tables to the book-wide stylesheet so that future contributions that contain similar tables can benefit from the styling. This PR also adds documentation to the stylesheet to support further stylesheet improvements. Finally, this PR adds a note about styling HTML content in the Consistency chapter.

### List of changes proposed in this PR (pull-request)

* Move table styling to book-wide stylesheet (all tables now look different and are reasonably responsive)
* Format stylesheet in a way that makes it easier to read and improve
* Add a note about styling in the maintaining consistency chapter.

**If this is good to go, we might consider documenting how to use the current content of the StyleSheet in a subchapter in the Style Guide. See #1657 **

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by martinagvilas** [comment]
@paulowoicho looks awesome!

Just to check, do you intend the tables to look like this:
image

or like this: 

image

(regarding the top border)

**Review by BatoolMM — COMMENTED** [review]
@paulowoicho I love the new style especially the background colour for the table header. I was wondering if it is maybe worth adding `:hover` selector on `<tr>` to highlight table rows on mouse over.
e.g.`tr:hover {background-color: #EEEEEE;}` or maybe lighter like`tr:hover {background-color: #f7f7f7;}`

**Comment by paulowoicho** [comment]
> @paulowoicho looks awesome!
> 
> Just to check, do you intend the tables to look like this:
> image
> 
> or like this:
> 
> image
> 
> (regarding the top border)

@martinagvilas, thanks for catching that! The second option is what I was going for. I primarily used the tables on [this page](https://deploy-preview-1656--the-turing-way.netlify.app/reproducible-research/licensing/licensing-software.html) to check the styling so I didn't notice the effect on top borders for other tables.

I will update the PR to reflect this

**Comment by paulowoicho** [comment]
> @paulowoicho I love the new style especially the background colour for the table header. I was wondering if it is maybe worth adding `:hover` selector on `<tr>` to highlight table rows on mouse over.
> e.g. `tr:hover {background-color: #EEEEEE;}` or maybe lighter like `tr:hover {background-color: #f7f7f7;}`

Thanks @BatoolMM. I think that's a great idea. I will update the PR with this as well

**Comment by martinagvilas** [comment]
> @martinagvilas, thanks for catching that! The second option is what I was going for. I primarily used the tables on [this page](https://deploy-preview-1656--the-turing-way.netlify.app/reproducible-research/licensing/licensing-software.html) to check the styling so I didn't notice the effect on top borders for other tables.

Awesome! In case you need a quick solution, I was able to get the top border displayed by adding the `!important` key like this:

```
th, td {
border: 1px solid #999999 !important; 
text-align: center; 
padding: 10px
}
```

**Comment by paulowoicho** [comment]
> > @martinagvilas, thanks for catching that! The second option is what I was going for. I primarily used the tables on [this page](https://deploy-preview-1656--the-turing-way.netlify.app/reproducible-research/licensing/licensing-software.html) to check the styling so I didn't notice the effect on top borders for other tables.
> 
> Awesome! In case you need a quick solution, I was able to get the top border displayed by adding the `!important` key like this:
> 
> ```
> th, td {
> border: 1px solid #999999 !important; 
> text-align: center; 
> padding: 10px
> }
> ```

Thanks! Just pushed another commit with the edit

**Review by martinagvilas — APPROVED** [review]
Looks great to me!

**Review by BatoolMM — COMMENTED** [review]
Amazing @paulowoicho 👍

**Pull request merged**
