### PR TITLE
Updating the landing page

### PR DESCRIPTION
**Pull request by da5nsy**
### Summary

as per #1955, to make it less intimidating (#1851, #1919, probably others) and to direct readers to the recommended ways of interacting with the guide (browse or keyword search).

### List of changes proposed in this PR (pull-request)

- I've tried to cut down the initial message to the bare minimum
  - I've moved out some of the text into a new 'history' section. **This would need expanding or removing before a merge** - it is currently a [stub](https://en.wikipedia.org/wiki/Wikipedia:Stub#Basic_information). I imagine this could be a good place for origin stories, key people, funding thanks etc. This interacts with #1731 - probably makes sense to include a link to a fuller history rather than have a duplicate 'history' on the landing page, unless the plan was for it to be there anyhow.
  - I've cut words where I could.
- I've tried to keep the language impersonal (avoiding language like 'we recommend...' because 'we' seems like an odd concept in this setting). This has meant that the language is quite direct (The option of 'We recommend not trying to read the book from start to end' has been passed over in favor of 'Do not try to read the guide from start to finish'). **Suggestions on how to make this sound friendlier are welcome!**
- I would like to be able to link to a summary page (really just the navigation pane but on a page of its own). I can't find a way to get jupyter book to create this page through URL manipulation, though there might be a way that I haven't found. **Help requested in finding this.**
- Talking or URL manipulation, I assume that there is a better way to link to the search page than with the full hardcoded URL. I hope that someone who understands how this works better than me will be able to **fix this**.
- (Unrelated to the main goal - I've hyphenated 'open source' since it is an adjective in this case.)

### What should a reviewer concentrate their feedback on?

Bolded above, but to summarise:
~~- [ ] Extend/remove history section (see note above regards #1731)~~ The history section will arrive at some point, at which point we can work out the best way to link to it.
~~- [ ] Make wording friendlier~~ It's actually fine.
~~- [ ] Find a way to generate a full-page clone of the navigation page, to be linked to from 'browse the chapters'~~ I'm actually happy with people having to use the normal navigation; it's good practice to have them use the standard navigation rather than creating a new/different/redundant navigation path.
~~- [ ] Fix my hacky link to the search page~~ I've actually removed it, see above logic.

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: 

### Updates

- I decided that everything was actually fine! (See crossed out to do list)

### CODE REVIEW

**Comment by da5nsy** [comment]
Just seen that I've unknowingly undone fae00bf0d0cfdb0604c277ab0fed52dc64b44a91 - I do think that "open-source" reads better (vs. "open source") in this context, but I'm curious to see if @paulowoicho or @malvikasharan have strong feelings?

- https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/o/open-source
- https://www.computerhope.com/jargon/o/opensour.htm

**Comment by malvikasharan** [comment]
We use Open Science as a noun, that refers to a field of research/practice. Hyphenated open-science is an adjective, which means the same but is not used to refer to open science/open research/open source ...

So to avoid inconsistency with how open science is referred to in literature/community, I would keep it unhyphenated.
> Just seen that I've unknowingly undone [fae00bf](https://github.com/alan-turing-institute/the-turing-way/commit/fae00bf0d0cfdb0604c277ab0fed52dc64b44a91) - I do think that "open-source" reads better (vs. "open source") in this context, but I'm curious to see if @paulowoicho or @malvikasharan have strong feelings?

**Comment by da5nsy** [comment]
Hi @malvikasharan 

I'm talking about the specific phrase "The Turing Way is an open-source community-driven book" where "open-source" is an adjective and "book" is the noun.

I feel quite strongly that it should be hyphenated in this situation.

**Comment by ha0ye** [comment]
I see @da5nsy's point, but I see "open source" as an adjective very frequently, so the hyphen throws me off. Describing a book as "open source" also feels slightly odd; and I wonder if "community-developed community-driven" would work as an alternative.

**Comment by da5nsy** [comment]
@ha0ye 
I like the idea of circumnavigating the problem, but I'm not sure "community-developed" is the way to go. For me, the important point that is communicated by the phrase "open-source" is that people can actually see the underlying code for the project.

To be honest, I was already a little unhappy with this sentence - it's the first sentence people read and it's super long and jumbly (however, we fall down on hyphenation). I'm going to change this PR back to WIP and try to improve it.

**Comment by malvikasharan** [comment]
@ha0ye Using "Open Source" for books is not unusual (For [example](https://www.freecodecamp.org/news/taking-off-the-successful-launch-of-an-open-source-book-7553a2262898/)). The concept comes from open source framework for project development, which applies to different areas of open science. 

Another option is to use open book (let's not talk about hyphenation again 😅) project (as used by [O'Reilly](https://www.oreilly.com/openbook/)).
@da5nsy My suggestion is to not get stuck on details as we are going to launch a Governance proposal (see #2035), which will include updating our vision and mission statements that most members agree with. The vision statement will then become the opening line of the book.

**Comment by da5nsy** [comment]
> The vision statement will then become the opening line of the book.

Aha, good to know. Thanks @malvikasharan. I shan't strain too much over getting it perfect then.

**Comment by da5nsy** [comment]
I think this is ready for review now.

Main goals of this PR: 
- Clarify the landing page text
   - previously it was quite wordy, and "open source" (however you like to hyphenate it) was doing some heavy lifting. I've broken that out into "open source", "open contribution" and "open licenced" which I think better explain what we mean by "open source" (and do so in a way that is hopefully more understandable to folks who are new to the terms).
- Add a 'warning' not to try to read the whole thing.
   - I'm quite happy with this now, and I think this will be useful to newcomers.

These commits may be shortlived due to #2035, #2033, and #2032, but I think this works as a temporary modification, and there may well be pieces that could be incorporated long term.

**Review by malvikasharan — APPROVED** [review]
@da5nsy this looks really great! I like the breaking down of open to -source, -contribution, -license. 
Also, I absolutely adore the addition of the buffet approach. I am happy with how it looks and approve to merge it.

**Pull request merged**
