### PR TITLE
add software to delete personal data

### PR DESCRIPTION
**Pull request by EstherPlomp**
### Summary
This PR adds some suggestions for software to delete personal data. 

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Review by EKaroune — APPROVED** [review]
looks great to me! Thanks

**Review by JimMadge — APPROVED** [review]
LGTM :+1:

**Comment by EstherPlomp** [comment]
Thanks both!

**Comment by EstherPlomp** [comment]
@all-contributors please add @JimMadge for review

**Pull request merged**
