### PR TITLE
Persona Heidi

### PR DESCRIPTION
**Pull request by HeidiSeibold**
### Summary

* Add persona of community members
  * current PR is created with Heidi's response
* Currently it is a first draft and quite short

Related to PR #1106 and issue #1181

### List of changes proposed in this PR (pull-request)

* Adding Heidi's profile

### What should a reviewer concentrate their feedback on?

- [ ] Is the text sufficient? Would you like more/other info about me?
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thanks, Heidi. I am sorry for coming to this so late. I wanted to include this in the newsletter this month. Can I ask you to write a bit more that includes the following aspects that we were discussing about in the #1106? I am using this chance to call for support for the work you are doing wither in The Turing Way or otherwise in your own research.

> How did you get involved in The Turing Way and what motivated you to work on your current contributions?
> What impact The Turing Way has had on you, your work, or your network? Please use the SMART criteria (Specific, Measurable, Achievable, Relevant, and Time-bound) to frame your answers.
> What impact you would like to create with your work in The Turing Way? Please use the SMART criteria (Specific, Measurable, Achievable, Relevant, and Time-bound) to frame your answers.

**Comment by HeidiSeibold** [comment]
Thanks for your comment @malvikasharan. :+1: 

Can you take a look at the update and let me know if and how I can improve it? Thanks!

**Comment by malvikasharan** [comment]
So well written. Thank you, Heidi. I edited the newsletter here #1222 with your earlier comments. I will add a few lines from here.

I am tagging @pgadige for a review of this PR.

**Comment by malvikasharan** [comment]
This PR has now moved to https://github.com/alan-turing-institute/the-turing-way/pull/1310.

**Pull request closed without merging**
