### PR TITLE
[Ready for review]: Fix duplicate paragraph

### PR DESCRIPTION
**Pull request by lukeconibear**
### Summary

Fixes duplicated paragraph for _Style enforcement_ in the `reviewing-motivation.md` page.

### List of changes proposed in this PR (pull-request)

- [x] `reviewing-motivation.md`: Remove duplicate paragraph for _Style enforcement_.
- [x] `reviewing-motivation.md`: Adding omit flags for _Title_ and _Table of Contents_ headings to not be auto-included in the _Table of Contents_.
- [x] `reviewing-motivation.md`: Fixed links in _Group knowledge and cohesion_ and _Importance and personal benefits_. Changed to a [referenced target header](https://jupyterbook.org/reference/cheatsheet.html#target-headers). Added the corresponding target header to `reviewing-recommend.md`.
- [x] `reviewing-motivation.md` and `reviewing-recommend.md`: Changed headings to CamelCase.

### Acknowledging contributors

- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file: [lukeconibear](https://github.com/lukeconibear)

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thanks for the PR @lukeconibear. It is not mandatory (only soft requirement), but we recommend camel casing for readability of titles. I know not all chapters are consistent as the style guide was written only last year. But you have time, can you please apply this to the files you are editing in this branch: https://the-turing-way.netlify.app/community-handbook/consistency/consistency-formatting.html#check-2-ensure-proper-title-casing-for-headers?

**Comment by malvikasharan** [comment]
@all-contributors please add @lukeconibear for typo fix

**Comment by malvikasharan** [comment]
@all-contributors please add @lukeconibear for bug fix

**Comment by lukeconibear** [comment]
Thanks @malvikasharan for your help. I have updated the files in this PR with your suggestion. Let me know if there is anything else.

**Review by malvikasharan — APPROVED** [review]
Amazing!! Thank you so much. Approving this. 🎊

**Pull request merged**
