### PR TITLE
[Ready for Review] Data Licenses

### PR DESCRIPTION
**Pull request by IIITM-Jay**
## Summary
With reference to #1075
As I have done with my writings on the subchapter *"Data Licenses"*, want the valuable feedbacks and suggestions. I am thinking to include the following subsections under it.
## Subsections:
 1.**Intoduction**(_a type of short summary within 5-6 lines and a flow chart to be more clear_) that discusses the following:
 * Why to use Data Licenses
 * What are Data Licenses
 * A flow chart to describe various scenarios where these are applicable
 
 2. **License Creation,Adaptation and Termination** that discusses the following:
 * How to use these licenses in your own document
 * How to use other's licensed material
 * What are the consequences of termination and violating the laws abide by them
 
 3.**An extensive use of Data Licenses in Aritificial intelligence(AI)**
 
 4.**An extension to "BIG DATA SCIENCES"**
 
 5.**A Case Study**
 
 ## Work done so far
 - [x] **Intoduction**
 - [x] **License Creation,Adaptation and Termination**
 - [x] **An extensive use of Data Licenses in Aritificial intelligence(AI)**
 - [x] **An extension to "BIG DATA SCIENCES"**
 -  [x] **A Case Study**
 
 ## Updates 
 Done completely

### CODE REVIEW

**Comment by IIITM-Jay** [comment]
@malvikasharan the latest commit is to be viewed under ***Data Licenses***.

**Comment by IIITM-Jay** [comment]
@malvikasharan  because of creating this file also I have taken my nearly one and a half week and then I have contributed to ***"Leadership and Management"*** too and then I had worked on your guide for ***"PROJECT DESIGN"*** AS stated by you too and this I had  invested my whole month contributing to this repo and organization

**Comment by IIITM-Jay** [comment]
Moreover @malvikasharan I had added contents to **risk assessment** and I have not removed any previous works by earlier members , it just moved that is I have shifted to it's right place where it should have to be.

**Comment by IIITM-Jay** [comment]
@malvikasharan please have a look and suggest changes on the same. Need some reviews on risk assessment too.

**Comment by IIITM-Jay** [comment]
Hi @rosiehigman may I request you to please review it what I have done so far. I would love to have your valuable feedbacks and suggestions on the same.

**Comment by IIITM-Jay** [comment]
@malvikasharan should I close this PR.

**Comment by KirstieJane** [comment]
As lead investigator of The Turing Way I'm going to close this PR as I don't think we're moving forwards in a productive way in these conversations.

**Pull request closed without merging**
