### PR TITLE
[do not merge] Debugging TOC for #2897

### PR DESCRIPTION
**Pull request by da5nsy**

### CODE REVIEW

**Comment by sgibson91** [comment]
Thank you 🙏🏻 To clarify, we are expecting all of these to be changed in the sidebar?

**Comment by sgibson91** [comment]
Can confirm that (at least for the first change) what we expected happened, i.e., the sidebar changed, but the actual titles did not

Screenshot 2022-12-01 at 18 06 11
Screenshot 2022-12-01 at 18 06 01

**Comment by sgibson91** [comment]
This is the only TOC-related message in the logs which I think is unrelated:

```
6:04:22 PM: [etoc] missing index.html written as redirect to 'welcome.html'
```

**Comment by sgibson91** [comment]
Definitely!

**Comment by da5nsy** [comment]
> This is the only TOC-related message in the logs which I think is unrelated:
> 
> ```
> 6:04:22 PM: [etoc] missing index.html written as redirect to 'welcome.html'
> ```
Agreed - unrelated (presumably...).
#2887

**Pull request closed without merging**
