### PR TITLE
Move welcome to index.md

### LINKED ISSUE #2887: [BUG] `[etoc] missing index.html written as redirect to 'welcome.html'` build note
@aleesteele: https://github.com/alan-turing-institute/the-turing-way/pull/2883#issuecomment-1326225433 :

> Tagging @da5nsy here, getting the error `[etoc] missing index.html written as redirect to 'welcome.html'` build error? Not sure why that might be the case?

This does not cause the CI to fail, so not urgent, but...

- My best guess is that that warning occurs because of this issue: https://github.com/executablebooks/sphinx-external-toc/issues/50 in which case we would need to clear out the cache at netlify.

- My second best guess is that it is because we have `root:` and `format:` in the opposite order in [our TOC](https://github.com/alan-turing-institute/the-turing-way/blame/main/book/website/_toc.yml) vs the [JB docs](https://jupyterbook.org/en/stable/structure/configure.html?highlight=index#configure-all-entries-in-the-toc).

### PR DESCRIPTION
**Pull request by JimMadge**
### Summary

Fixes #2887

Moves the welcome page from `welcome.md` to `index.md` and hence to `index.html` in the html build.

This isn't really a bug fix, as `jupyter-book` handles the root being `welcome.md` fine and creates an `index.html` which redirects to the welcome page. However,

- This removes the message about an `index.html` being created which has caused some confusion as it looks quite like a warning or error #2887 #2986.
- An `index.html` is [a good idea to help navigation regardless](https://github.com/executablebooks/sphinx-external-toc/blob/091d23a248544d5c556753ad853e9acdb1e682e6/sphinx_external_toc/events.py#L315-L320)

The page is still titled `Welcome` on the page itself and in the ToC.

### List of changes proposed in this PR (pull-request)

* Move `welcome.md` to `index.md`
* Update links
* Update redirects

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?
- [ ] Do we dislike the welcome page's path being `/index.html`?
- [ ] Are the redirects correct?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thanks for proposing the change and explaining the issue @JimMadge.

This update is fine as the book's URL https://the-turing-way.netlify.app always resolves to the landing page (welcome currently, and index with this change). I am happy to have this merged.

**Review by malvikasharan — APPROVED** [review]

**Comment by JimMadge** [comment]
@malvikasharan Can I add some contributors here using the bot?

**Comment by malvikasharan** [comment]
Absolutely!!

**Comment by JimMadge** [comment]
@all-contributors
please add @sandygudie for bugs
please add @TheAbstract for bugs

**Comment by da5nsy** [comment]
For future reference @JimMadge - since the all contrib bot opens separate pull requests, and each pull request has to modify the html for the whole segment, it's best to do one at a time

**Comment by da5nsy** [comment]
And also, thank you so much for working through this issue and merging a PR to address it! 🥳

**Comment by JimMadge** [comment]
> For future reference @JimMadge - since the all contrib bot opens separate pull requests, and each pull request has to modify the html for the whole segment, it's best to do one at a time

Oh actually, I should know better. Because I did exactly this before and spent an afternoon fixing the merge conflicts manually :scream:.

**Comment by da5nsy** [comment]
> > For future reference @JimMadge - since the all contrib bot opens separate pull requests, and each pull request has to modify the html for the whole segment, it's best to do one at a time
> 
> Oh actually, I should know better. Because I did exactly this before and spent an afternoon fixing the merge conflicts manually 😱.

Oh nooooo! 😨

**Pull request merged**
