### PR TITLE
Patricia's talk for the Hacker Within in Birmingham

### LINKED ISSUE #191: Present Turing Way at Bham Hacker Within
### Summary

@pherterich is invited to present the Turing Way to the local hacker within group on Feb 18th. Title is "The Turing Way - supporting reproducibility and Open Research" 

### What needs to be done?

- [x] @pherterich to provide slides in a PR somewhere to comment by 13th Feb. Slides are at https://github.com/alan-turing-institute/the-turing-way/blob/PH-hackerwithintalk/conferences/TuringWay_HackerWithin.ppt which isn't really helpful as they can't be previewed through GitHub 
- [x] @pherterich and @KirstieJane and other interested people to go through a trial run on 14th Feb
- [x] @pherterich to present and feed back any interesting comments

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Fixes #191 

Slides for @pherterich's talk on 18 February in Birmingham

### List of changes proposed in this PR (pull-request)

* Upload slides

### What should a reviewer concentrate their feedback on?

- [ ] @KirstieJane for feedback on how long the talk is and whether it's covering the right topics

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [humans.md](humans.md).

### CODE REVIEW

**Comment by r-j-arnold** [comment]
One extra thing to include after slide 8 is non-selfish reasons to work reproducible e.g. to facilitate reuse to advance research faster.

Slide 12 could do with heavy modification or deletion- we intend that each chapter will have its own checklists and they aren't spit up like this (though we may do so in the future. Otherwise good and the slides are *beautiful*.

**Comment by KirstieJane** [comment]
Thanks @r-j-arnold. I disagree that we need to change the point about the checklists. I understand that we don't have them in that format now, but we *do* want to aim for stand alone 1 side of A4 checklists for the different members of the research team.

I did a run through with @pherterich yesterday and one of the challenges is time - there's a lot to say already! I think the plan is to cover the non-selfish reasons on the slides defining the reproducibility crisis and the term itself (so slides 6 and 7). My opinion is that you don't need an additional slide for these points, but definitely make sure that they're mentioned (as @r-j-arnold said!)

Heavily agree that the slides look lovely though!! 😍

**Comment by pherterich** [comment]
Yeah, made some changes after our discussion yesterday @KirstieJane and will refine after a run through with colleagues at lunchtime. New version of slides to follow this afternoon :smile:

**Comment by KirstieJane** [comment]
Oh - @pherterich - can you move this presentation to a folder with the name of the event? Just to keep the directory structure similar to the other ones.

And if you can add a pdf version when you're done that would make for easy viewing online.

Finally, if you can update the table in the README to a) link to your talk and b) include the DOI for citing (maybe in a new column?) that would be awesome! 🚀 🌟

**Pull request closed without merging**
