### PR TITLE
Adding a short section on RAMs

### PR DESCRIPTION
**Pull request by AidaMehonic**
### Summary

Adding a short section on RAMs to the Open Infrastructure Roles chapter.

### What should a reviewer concentrate their feedback on?

- [ ] Adding hyperlinks to other relevant parts of The Turing Way. 

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:  @dingaaling @aldenc

### CODE REVIEW

**Review by dingaaling — APPROVED** [review]
lgtm!

a few small thoughts:
- is new "software" considered knowledge? to me, it sounds like a form to contain knowledge. i wonder if an example like a  "new algorithm" or "new model" might better capture the distinction between what academia incentivises + what RAMs focus on
- The current "inspired by" roles focus on the user community aspect of RAM work. Perhaps these roles can focus on the "tools packaging/promoting" side of the RAM role: 
1. Solutions Engineer: "A Solutions Engineer interfaces with customers and identifies their needs. A Solutions Engineer with then work with various departments... to ensure a plan is in motion to improve the customer's experience."
2. Forward Deployed Engineer: "Engineers with broad skills to enable many capabilities and use cases of [a product] by iterating closely with customers and bridging the gap between the product suite and a customers' specific implementation needs."

**Comment by malvikasharan** [comment]
@AidaMehonic thank you so much for developing this chapter, and @dingaaling thank you for reviewing this. I have made some minor formatting related updates so that the chapter appears in the book with the image and alt text as intended.

I will leave the content review on Jennifer, and for some formatting suggestions you can refer to this chapter: https://the-turing-way.netlify.app/community-handbook/style.html. Looking forward to reading this. 🙌

**Review by aldenc — APPROVED** [review]
looks good to me!

**Comment by AidaMehonic** [comment]
Adding a section on RAMs! 🐏

**Pull request merged**
