### PR TITLE
Update collaboration cafe guidelines

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Doesn't close an open issue.

During the Collaboration Cafe on 18 September, @malvikasharan and I brainstormed how to improve the process and make it clearer. This PR captures her and my contributions ✨ 

### List of changes proposed in this PR (pull-request)

* Update description and some processes for collaboration cafes
* Add template for hackmd

### What should a reviewer concentrate their feedback on?

- [ ] Does it make sense? Are we missing any other clarifications?
- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by KirstieJane** [comment]
@alexmorley - do you know why the CI is failing here? I think maybe Jupyter Book upgraded and we need to change something about our setting? 

From [the logs](https://app.netlify.com/sites/the-turing-way/deploys/5d829b0fbabe07000798ceeb):

```
10:02:34 PM: The version of the book you are modifying doesn't match the
10:02:34 PM: version of the command-line tool that you're using. Please run
10:02:34 PM:     jupyter-book upgrade /opt/build/repo/book/website
10:02:34 PM: to upgrade your book to the CLI version.
10:02:34 PM: This book's version: 0.4.2
10:02:34 PM: Your CLI's version: 0.6.0
10:02:34 PM: See above for the error message.
```

**Comment by alexmorley** [comment]
I'm actually not sure but I imagine you are right. I would try pinning the version of jupyter-book in requirements.txt to what it was before.

**Comment by KirstieJane** [comment]
Thanks @alexmorley 😸 

@choldgraf or @emdupre - do you have any thoughts on this jupyter-book error?

(You can read into this that while I probably _could_ figure out what's going on, I won't have time for a few days and it will almost certainly take me much longer than someone who has more experience in this area! Don't worry if y'all are busy.... I can find time next week or the week after.... but :x:s make me sad!)

**Comment by KirstieJane** [comment]
Ooooh - @alexmorley made our tests pass! I AM HAPPY AGAIN!

@choldgraf - I'd still love your thoughts, but we'll probably move to a different issue/PR 😸

**Comment by choldgraf** [comment]
Hey @KirstieJane - sorry for the slow response, I was out of town. It sounds like this error specifically is resolved - as @emdupre mentions it is because we're starting to require a degree of consistency between the jupyter book CLI and the book that's actually being built. The reason for this is because otherwise the builder might run into errors that are a result of the CLI / book version mismatch, and this way we can explicitly call out this error.

**Pull request merged**
