### PR TITLE
Updated rdm-fair.md

### PR DESCRIPTION
**Pull request by Varachkina**
Added link to the video on FAIR principles

### Summary
I deleted the line `For a more practical overview` and replaced it with the necessary information + video

### List of changes proposed in this PR (pull-request)

* deleted the old information 
* added new information on FAIR principles  + added links to video

### CODE REVIEW

**Comment by BrainonSilicon** [comment]
Hi @Varachkina. Was there an Issue associated with this Pull Request?

**Comment by BrainonSilicon** [comment]
Found the Issue - it was #2487! Thanks for working on it @Varachkina

**Review by aleesteele — APPROVED** [review]

**Comment by aleesteele** [comment]
Great job @Varachkina! 🎉 

@all-contributors please add @Varachkina for typos

Feel free to merge your pull request! 🚀

**Comment by aleesteele** [comment]
@all-contributors please add @Varachkina for content

**Comment by aleesteele** [comment]
@all-contributors please add @Varachkina for bugs

**Comment by da5nsy** [comment]
Good bot. Thank you.

**Pull request merged**
