### PR TITLE
Get open science branch up to date

### PR DESCRIPTION
**Pull request by r-j-arnold**
Alex restructured the master branch to have a separate folder for chapters (among other things). Merge those changes into the open science branch so when I create the open science chapter it can be put in the correct folder immediately.

### CODE REVIEW

**Comment by KirstieJane** [comment]
Ah - now I see that you're also adding the open science chapter in https://github.com/alan-turing-institute/the-turing-way/pull/139/commits/7f8e69acb5a0cfd24ef9e5fa35140878132a528e 😸 

So maybe do that, and then make a PR to master to update the notes about the january sprint?

**Comment by r-j-arnold** [comment]
Alex made changes to master to make it neat. This included making a folder for chapters

Those changes aren't in the open science branch because it was created prior to those changes.

This pull request gets the alan turing open science branch up to date with alan turing master.

This is necessary because I want to open a [WIP] pull request for the open science chapter on the open science branch and I want to start with the chapter in the correct folder.

Is that clear?

**Comment by r-j-arnold** [comment]
> Ah - now I see that you're also adding the open science chapter in [7f8e69a](https://github.com/alan-turing-institute/the-turing-way/commit/7f8e69acb5a0cfd24ef9e5fa35140878132a528e) 😸
> 
> So maybe do that, and then make a PR to master to update the notes about the january sprint?

Sorry, which notes do you mean, the ones about the CI etc chapter?

**Comment by KirstieJane** [comment]
Yes - I think what wasn't clear is that the pull request came from your fork, not a PR to keep the `open-science` branch up to date with master.

I think the clearest process would have been:

1. a PR to keep `open-science` up to date with `master`. This would have been from `master` branch to `open-science` branch.
2. a separate PR to include `open_science.md` into the `open-science` branch. This would have been from your fork to `open-science`.

The biggest point of confusion for me was which branch was going to where.

Alternatively, one PR (which is what you had) but calling it something like your new title of "Get open science branch up to date" would totally work. OR putting [WIP] in the title so I didn't jump in and review before you were ready 🤣 🤦‍♀️ 

Does that make sense? Jump in gitter if it doesn't and we can chat there.

Happy to merge this though as a combination of the two actions above.

**Comment by r-j-arnold** [comment]
Yep, I had intended to do one pull request for getting up to date and the another for adding the chapter but my brain just completely glitched and I forgot that commits made after you make the pull request *get added to the pull request* and bundled in with them.

I'll remember that and try to keep my request messages clearer about what branch is going where in the future. 

I'll merge now, and I've got a quick clarification about the notes I want to ask which I'll put on gitter.

**Comment by KirstieJane** [comment]
✨ Totally understand. Thanks so much @r-j-arnold 👾

**Pull request merged**
