### PR TITLE
fix broken links in CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by srishti-nema**
### Summary

*Minor corrections which fix some links*

### List of changes proposed in this PR (pull-request)

Fixes the following links in the [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md) file :
* [2.1 Expected Behaviors](https://github.com/srishti-nema/the-turing-way/blob/master/21-expected-behaviours)
* [4 Enforcement Manual](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md#enforcement-manual) at the end of Section 2.3
* [xvzf Code of Conduct](http://xvzf.io/) given in Section 5

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thanks @srishti-nema! I will add a tag for others to review this. 🎊

**Comment by malvikasharan** [comment]
Thanks for the review @EstherPlomp <3 @srishti-nema Please go ahead and merge it! 🎊

**Comment by srishti-nema** [comment]
> Thanks for the review @EstherPlomp <3 @srishti-nema Please go ahead and merge it! confetti_ball

I don't have merging rights, I guess.

**Comment by malvikasharan** [comment]
Here I merged! :)

**Pull request merged**
