### PR TITLE
Tidy up talks folder

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Doesn't fix any open issues

This PR is a tidy up PR for the conferences folder 😸 

### List of changes proposed in this PR (pull-request)

* Add DOI column for talks repo
* Did a little tidying up (eg remove `-` for missing abstract and made long file names shorter)

### What should a reviewer concentrate their feedback on?

- [x] Does this render properly?
- [x] @pherterich - can we add the pptx version of your talk? It makes re-using much easier 😸 

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [humans.md](humans.md).

### CODE REVIEW

**Comment by pherterich** [comment]
@KirstieJane GitHub in browser complained that the ppt is too big (includes one of @sgibson91 's gifs...). Will attempt other ways to upload later this week.

**Comment by KirstieJane** [comment]
Thanks @pherterich! I think for this version you could just delete the gif and replace with a textbox that has the link to the gif in the repo. Does that make sense?

**Comment by pherterich** [comment]
I did have that first for the presentation and then realised it's not too smart when internet doesn't work but didn't think as far as reverting back :woman_facepalming: 
Now fixed in #237

**Comment by KirstieJane** [comment]
Hey @pherterich - I don't think you meant to close this PR so I'm going to re-open it and merge.

**Pull request merged**
