### PR TITLE
[Ready to review] Restructure Open Research chapter

### PR DESCRIPTION
**Pull request by jspickering**
### Summary

Addresses part of #468  

Restructure Open Research chapter

### List of changes proposed in this PR (pull-request)

* Made new folder structure within Open Research chapter
* Moved different sections into separate .md files

### What should a reviewer concentrate their feedback on?

- [x] Does it look okay?
- [ ] Should I remove the contents page from the first section?

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by pherterich** [comment]
Note: we need to update the table of contents to show properly in the book :smile:

**Comment by jspickering** [comment]
I've updated the main TOC page, but I'm not sure how to change the contents within the chapter itself :S

**Comment by pherterich** [comment]
@alexmorley the netlify checks are stuck somewhere and we can't figure out where and hitting Travis restart build buttons doesn't do anything. Could you give this a look to see why we can't get it in please?

**Comment by sgibson91** [comment]
Maybe push a new commit to re-trigger the build?

**Comment by alexmorley** [comment]
The deploy history is here https://app.netlify.com/sites/the-turing-way/deploys

Will continue conversation about debugging any issues here at #404 (which is a) a great issue ID a b) will stay around after this PR is merge :) )

**Comment by pherterich** [comment]
Restructuring worked, but now none of the contents link anywhere, so will create an issue for someone to tackle that :smile:

**Pull request merged**
