### PR TITLE
Fix Typo in reproducibility.md

### PR DESCRIPTION
**Pull request by jmgate**
### Summary

Just inserted a missing `t` in `deailed`.

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [humans.md](humans.md).

### CODE REVIEW

**Comment by KirstieJane** [comment]
@jmgate - do you want to be added to humans.md? You checked the box but I don't think you're in there yet?

If you _do_ want to be added I think I'm going to try to use the fancy [all-contributors bot 🤖 ](https://allcontributors.org/) to add you if that's ok? Obviously if you don't want to be added then you don't have to be!

**Comment by jmgate** [comment]
I'm fine being added&mdash;this is a worthwhile project to be a part of.

**Comment by KirstieJane** [comment]
Fabboooo - lets see if this works.... @allcontributors[bot] please will you add @jmgate to our project for reviewing and adding documentation ✨

**Comment by KirstieJane** [comment]
Nearly! @allcontributors[bot] please add @jmgate for reviewing.

Thank you @jmgate - I'm going to merge this now!

**Comment by KirstieJane** [comment]
Ah, that's why. Sorry @allcontributors[bot]. Please add @jmgate for review.

**Pull request merged**
