### PR TITLE
Reduce image sizes to lower than 1MB

### LINKED ISSUE #1313: [accessibility] Reduce image sizes to lower than 1 mb  ( 26 PR ideas for HacktoberFest participants)
## :tada::balloon::cake: **Welcome Hacktober Contributors! This is The Turing Way repository** :cake::balloon::tada:

:dizzy::hatched_chick::sunny: _We're excited that you're here and want to contribute._ :sunny::hatched_chick::dizzy:

### About Hacktober and The Turing Way
Hacktober is a month long celebration of Open Source Projects where the goal is to make 4 Pull Requests during the month.

#### A bit about Git
If you’re new to git then here are [some instructions](https://help.github.com/articles/signing-up-for-a-new-github-account/) to help you get going. Remember that you can ask us any questions you need to along the way.

A [Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request) (what Hacktober is measured on) lets you tell others about changes you've pushed to a branch in a repository on GitHub. Once a pull request is opened, you can discuss and review the potential changes with collaborators and add follow-up commits before your changes are merged into the base branch.

Under the Issues listed in our Hacktober tag, we’ve outlined what needs to be done, and how you can go about addressing it. Once the Issue has been addresses, you can submit a Pull Request for review (tell us what you’ve done) and we can incorporate it into The Turing Way.

We’ve also created this special Hacktoberfest tag to make is easy for you to find places to contribute if you’re new.

In the spirit of Hacktoberfest, please only do a few of these to submit your PR so that we can learn and grow as a community together.

#### Our Community
Please read our core Contributors document and our Code of Conduct while you engage in The Turing Way. We want to ensure that every user and contributor feels welcome, included and supported to participate in The Turing Way community.

In addition, for Hacktober we would also like to recognise the work that you are doing. If you would like to be featured on our [Twitter](https://twitter.com/turingway?s=20) Hacktoberfest series then: 
- Add your twitter handle to the comments when you submit your PR, 
- What brings you to Open Source, Hacktoberfest, and/or The Turing Way,
- and anything else you’d like to celebrate about your contribution!

We welcome all contributions to this project via GitHub issues and pull requests. Please follow these guidelines to make sure your contributions can be easily integrated into the projects. As you start contributing to The Turing Way, don't forget that your ideas are more important than perfect pull requests. ❤️

If you have any questions that aren't discussed below, please let us know through one of the many ways to get in touch.

# Summary of Issue

* Problem: Many images in the online books are very large and take enormous time to load (listed below)
* Solution (suggested for PRs): Reduce the image size to make them lower than 350 KB
* Image location: [book⁩/⁨website⁩/figures⁩](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/website/figures)

### What needs to be done?

From the file path [book⁩/⁨website⁩/figures⁩](https://github.com/alan-turing-institute/the-turing-way/tree/master/book/website/figures) please select a maximum of 2-3 files from the list below to create a PR. To select, but click on the checkbox and comment below in the issue so others know which files you will be working on.

- [x] community.jpg
- [x] ThatCouldBeAChapter.png
- [x] reproducibility.jpg
- [x] communication.jpg
- [x] bookdash.png
- [x] binder_comic.png
- [x] file-collection.jpg
- [x] flipped_taj_mahal.png
- [x] welcome.jpg
- [ ] collaboration.jpg
- [ ] data-ecosystem.jpg
- [ ] distributed-collaboration.jpg
- [x] Provenance.jpg
- [x] ResearchCompendium.jpg
- [x] contributors-twopanel.png
- [ ] outreach.jpg
- [ ] project-design.jpg
- [ ] ethics.jpg
- [ ] data-privacy.jpg
- [ ] allcontributorsbot-emoji.png
- [ ] persona-creation.png
- [ ] virtual_machine.png
- [ ] Contributors.png
- [ ] scriberia-newsletter.png
- [ ] templates.png
- [ ] testing_motivation_2.png

### Who can help?

- Anyone who would like to participate in Hacktoberfest or contribute to The Turing Way GitHub repository for the first time
- easier to do locally (by git) but not mandatory
---

### PR DESCRIPTION
**Pull request by giannidsp**
### Summary

Fixes #1313 

I'm going to reduce the size of some images.

### List of changes proposed in this PR (pull-request)

Images that were reduced:

- [ *] reproducibility.jpg

- [ *] communication.jpg

- [ *] bookdash.png

### CODE REVIEW

**Comment by malvikasharan** [comment]
Thank you @giannidsp 👏. @paulowoicho I have added you to this repo with write access - can you please accept my invite (in your email) and then review and approve this PR if everything looks good?

**Comment by paulowoicho** [comment]
No worries @malvikasharan. Thank you @giannidsp for your work on this!

**Review by paulowoicho — COMMENTED** [review]
Hey @giannidsp. Thanks again for your work on this. I wonder if it's possible to reduce the size of the images without reducing the image dimensions. That way, when the book is deployed to Netlify, the images will not be too small.

**Comment by giannidsp** [comment]
> Hey @giannidsp. Thanks again for your work on this. I wonder if it's possible to reduce the size of the images without reducing the image dimensions. That way, when the book is deployed to Netlify, the images will not be too small.

Sure, of course. Apology for that. Give me a chance.

**Comment by giannidsp** [comment]
@paulowoicho ready! Anything you can leave me a comment. I hope it helps.

**Comment by paulowoicho** [comment]
> @paulowoicho ready! Anything you can leave me a comment. I hope it helps.

Thanks for this! It all looks good!

**Review by paulowoicho — APPROVED** [review]

**Pull request merged**
