### PR TITLE
Test PR. Do not merge

### PR DESCRIPTION
**Pull request by da5nsy**
Testing #2861

### CODE REVIEW

**Comment by da5nsy** [comment]
My question here is: do PRs use the CI instructions that existed when they were made, or when the tests are started?

**Comment by da5nsy** [comment]
> My question here is: do PRs use the CI instructions that existed when they were made, or when the tests are started?

Oh interesting, looks like it's the latter, good to know.
That means that for literally all open PRs we'll have to either ignore the tests or do upstream pulls. Cool cool cool. 😞

**Comment by bsipocz** [comment]
> That means that for literally all open PRs we'll have to either ignore the tests or do upstream pulls. Cool cool cool.

Yes, PRs will use the config they have in their branches, so all of them basically need a rebase whenever significant CI changes were made (which to be frank makes total sense)

**Comment by bsipocz** [comment]
Basically the base of the branch that matters, not what happened concurrently (same idea, one has to rebase to see a regression or CI fixed in main but not on the feature branch)

**Pull request closed without merging**
