### PR TITLE
[Ready for Review] Add hack-my-binderhub session materials

### PR DESCRIPTION
**Pull request by annakrystalli**
### Summary

Adding the materials associated with the afternoon Hack my BinderHub session. Because it is more of a practical exercise and much of the information is useful during group work, I opted for an explanatory md format. I also think it will be more useful if repeating the workshop this way.

### List of changes proposed in this PR (pull-request)

* Adding `hack-my-binderhub.md` to workshop materials

### What should a reviewer concentrate their feedback on?

- [ ] *Content (typos?/inconsistencies? etc.*
- [ ] *General proposed session flow.*

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x ] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by r-j-arnold** [comment]
Hey @annakrystalli, this looks great!

Incredibly minor nitpicks below, but it's essentially fie so marking as approved now.

You have "Aim of any critique should be to improve community understanding and project quality." twice, (though perhaps this is deliberate for emphasis?)

Perhaps rephrase "More likely to provide solutions rather than problems (preferable)." to "Preferable to provide solutions rather than problems" 

"Be explicit about what feedback you need: eg" eg should be e.g.

**Comment by pherterich** [comment]
❤️ Wondering if the "contributing" directly section could make use of something like a "look out for things labelled "good first issue" or something similar. Most people in the room will know, but if someone with less knowledge would like to re-use this, it might be a useful pointer. Otherwise awesome, so looking forward to our picoWOW ❇️

**Comment by annakrystalli** [comment]
Thanks for the input all.

@r-j-arnold I've incorporated most of your suggestions. I am repeating myself but with a slightly different point. I'll just leave it for now but if you feel you can think of a better phrasing but retaining the slightly different points feel free to edit directly.

@pherterich I haven't mentioned labels because I think more of the focus is for participants to open new issues, not try to find issues that already open to work on? Should be guiding them to already open issues?

**Comment by KirstieJane** [comment]
My tiny 2cents on the issue labels thing. I think it would be good to orient people to what issues look like - including those that are easy to contribute to....but I understand that that isn’t the goal of this workshop so basically don’t mind whichever way you choose @annakrystalli!

**Comment by KirstieJane** [comment]
NEVERMIND! It’s merged already.

Well done!! Excited for tomorrow ✨✨✨

**Comment by annakrystalli** [comment]
Sorry for the jumping the gun! I can mention labels briefly and suggest that open issues can be targets of contribution but mention it more informaly rather than putting it the instructions and encourage them to contribute new issues if possible.

**Pull request merged**
