### PR TITLE
[WIP] improve research compendia chapter

### LINKED ISSUE #1003: Small issues in chapter research compendia
### Summary

- Link for subsections does not work as I expected. See screenshot from https://the-turing-way.netlify.com/research_compendia/research_compendia.html:

image
- A few typos

### What needs to be done?

- [x] Can anyone tell me how to do links to subsections of the chapter? :grimacing: 
- [x] Fix typos (I can do that)

### Who can help?

People who know stuff about git books and links. :book: 

---

### Updates

- Created PR #1004 
- Please comment about the link stuff below :clap:

### PR DESCRIPTION
**Pull request by HeidiSeibold**
### Summary

Fixes #1003 

### List of changes proposed in this PR (pull-request)

* Typo fixes
* Link fix

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

This could be a good first PR to review/merge, if someone wants to practice :nerd_face: 

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by growupboron** [comment]
@HeidiSeibold Here's my Pull Request for the link fixes #1077

**Comment by HeidiSeibold** [comment]
Maybe the link problem is because we are closing two round brackets? One for the link and one for the side note. :thinking:

**Comment by growupboron** [comment]
@HeidiSeibold Updated the PR with latest commit of Glossary Link fix.

**Comment by HeidiSeibold** [comment]
Thanks @growupboron! 

@malvikasharan quick question: should I be able to see the changed version when I click on `deploy/netlify Details`? When I do that it seems nothing has changed.

**Review by inwaves — APPROVED** [review]
Approving this for the typo fixes. It looks like the link fixes have already gone in as part of #1077.

**Pull request merged**
