### PR TITLE
[Ready for review] Updating Github templates

### LINKED ISSUE #476: Update Github Issue Templates
### Summary

This issue will update the Github issue templates options one has when opening a new issue.
 

The user will have options for opening specific types of issues such as [NEW-CHAPTER] etc.  

### What needs to be done?

- [ ] Move templates that already exist in `chapters/CHAPTER_ISSUE_TEMPLATE.md` and `chapters/CHAPTER_TEMPLATE.md` to `.github/`

### PR DESCRIPTION
**Pull request by tallamjr**
### Summary

This PR adds templates for creating a new chapter. This will allow a user to be able to choose between a general issue or whether they want to create a new chapter

Fixes #476 

### List of changes proposed in this PR (pull-request)
```
        renamed:    templates/CHAPTER_ISSUE_TEMPLATE.md -> .github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md
        renamed:    .github/ISSUE_TEMPLATE.md -> .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
```

### What should a reviewer concentrate their feedback on?

- [ ] Is this what is desired by the team.

It will give an interface that is akin to:
image

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by KirstieJane** [comment]
I'm happy with this. Tagging a few of the core team to see what they think about having a chapter PR 😄 

@LouiseABowler @pherterich @rosiehigman @rainsworth

**Comment by rainsworth** [comment]
I love this!

**Comment by LouiseABowler** [comment]
I really like this idea, we've got the two templates so let's make it easy for the community to use them 😁 Thanks @tallamjr!

Some of the links/information in [CONTRIBUTING.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md) will need updating to reference the chapter template - [Where to start: issues](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md#where-to-start-issues) and [The process of writing chapters](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md#the-process-of-writing-chapters) are the places I can immediately think of.

**Comment by pherterich** [comment]
This is so cool :+1:

**Comment by rainsworth** [comment]
I'll get on that @LouiseABowler !

**Comment by rosiehigman** [comment]
This looks awesome, thanks @tallamjr! :rocket:

**Pull request merged**
