### PR TITLE
Indent numbered list blocks to avoid number reset

### PR DESCRIPTION
**Pull request by inwaves**
### Summary

Fixes small grammatical error regarding noun determiner.

### List of changes proposed in this PR (pull-request)

* On the Netlify-hosted _Turing Way_, the numbered list indices are reset because of the code blocks at each point. This means the list looks as below, with 1. as the index for all points. To fix this, indent the code blocks with 4 spaces.
image

### What should a reviewer concentrate their feedback on?

- [x] Ensure fix remedies the list indexing on Netlify.

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: @inwaves

### CODE REVIEW

**Comment by inwaves** [comment]
As part of this PR, we should also indent the short paragraph that says:
_"Make sure that you are on your master branch locally, if not, then checkout your master branch using the command git checkout master"_

This is such that the last point of the numbered list shows 6. instead of 1.

I didn't catch this on the first commit, but if that makes sense I will submit a second one.

**Comment by malvikasharan** [comment]
That's a good catch. Maybe something we can add to the style guide. Would you like to add a sentence to [this page](https://github.com/alan-turing-institute/the-turing-way/blob/master/book/website/community-handbook/style.md) under a new section "Tips", using a special content-box (see [here for details](https://the-turing-way.netlify.app/community-handbook/style/style-more-styling.html))?

We would also need to add a sentence about an issue as discussed here #1670
> The way some external links are written trigger a warning in the Jupyter-Book build. External links should be written down with https:// (e.g. https://twitter.com) and not with www. (e.g. www.twitter.com) or without prefix (e.g. twitter.com)

**Review by malvikasharan — APPROVED** [review]
Thank you @inwaves for fixing it.

**Comment by inwaves** [comment]
Thanks @malvikasharan, I'll look to add the update to the style guide tomorrow.

**Pull request merged**
