### PR TITLE
[Ready for review] Reproducibility chapter

### PR DESCRIPTION
**Pull request by pherterich**
### Summary

First draft for the reproducibility chapter, without version history as I messed up and apparently didn't just work on my old WIP draft, sorry :disappointed: .

This should address the discussion in #101 

### What should a reviewer concentrate their feedback on?
* Happy to get detailed feedback on phrasing already.
* Some of the more conceptual thinking in #101 might still apply (e.g. if a matrix of various guidelines out there would be useful)

### Acknowledging contributors

@labarba has provide super useful input, happy to update the humans.md file accordingly if that's ok.

### CODE REVIEW

**Comment by r-j-arnold** [comment]
Hi @pherterich quick note, all your commits are being put on this pull request because you made it to master, so open_data.md's been chucked in with this pull request. I suggest you revert that commit, crete an open_data branch on your repo, and then add the file there since it's nothing to do with this pull request

**Comment by r-j-arnold** [comment]
He @pherterich looks good. I'll follow up with notes as I go through in more detail.

- The link to the guardian article looks a little weird in brackets between sentences. How about changing it to something like Media outlets have [reported](https://www.theguardian.com/science/2018/aug/27/attempt-to-replicate-major-social-scientific-findings-of-past-decade-fails) on...

**Comment by r-j-arnold** [comment]
"loosing trust" -> "losing trust"

**Comment by r-j-arnold** [comment]
Could you spell out the link between why reproducibility is important for trust and why working reproducibly saves time a bit more, I think the connection could do with a little more emphasis.

**Comment by r-j-arnold** [comment]
The "Why you should care about reproducibility" section;

- "Desaster" -> "Distaster"
- "well documented analyses ensure you have easy access to the latest results **and** your work can easily be written up and collaborators can easily get on board as additional authors." I think that **and** should be a comma?
- "Well documented work means ~~others~~ your work can easily be picked up and continued - either by other in your lab or yourself if you want to build on your own work after a longer period."
- "All research outputs that are shared can be built upon by others" Maybe change this to "can be built upon **more easily** by others"

**Comment by r-j-arnold** [comment]
In the bullet point list of the chapters the top two don't start with capital letters, could you fix that?

Other wise, looks good to me! I particularly like the figure.

**Comment by r-j-arnold** [comment]
Looks great! I'll mark it as approved but others may want to comment before you merge.

**Comment by pherterich** [comment]
Thanks @r-j-arnold ! Would probably be good if @KirstieJane has a read through if she has the time, but good to know that we have another chapter almost ready to go :smile:

**Comment by pherterich** [comment]
I'll merge this now, if anyone wants to add anything, they can discuss in #101 or open PRs with changes they would like to see.

**Pull request merged**
