### PR TITLE
First draft of abstract for UKRI Cloud Workshop demonstration

### PR DESCRIPTION
**Pull request by sgibson91**
@KirstieJane feel free to edit, restructure, or scrap as needed 🙂

### CODE REVIEW

**Comment by sgibson91** [comment]
@KirstieJane Abstract submission closes on Friday (11/01/2019) and I still need to run this by the BinderHub team

**Comment by KirstieJane** [comment]
Looks GREAT! 👾 

There's more information you need to provide though, right? Can you add that information in when you submit.

If it's all quite straightforward then no need for me to approve before you send it along to the binder team and then submit!! 😸

**Comment by sgibson91** [comment]
I think those are just tick boxes that we went through before Christmas? They'll be in the HackMD on this issue #91

**Comment by sgibson91** [comment]
@KirstieJane I added a link to the BinderHub docs? First paragraph is a brief description of what it does

**Comment by sgibson91** [comment]
Excellent. I'll merge and drop the link in the binder chat room 😊(Might also send a separate email to Tim/Chris just so it doesn't get lost in the wave of messages.)

**Pull request merged**
