### PR TITLE
Updated README-French.md

### PR DESCRIPTION
**Pull request by aakashraj01**
### Summary

Updated the README-French Related to issue #2107 ([HACKTOBERFEST] README translated versions to update during HacktoberFest)

### List of changes proposed in this PR (pull-request)

* *Added the new translations following the changes in Harmonise README and Landing file  #2032 and made sure it matches the current English README.*
* *Changed the hyperlinks in several places, due to:*
         -They kept the English title, so they weren't pointing anywhere.
         -They didn't go back 1 directory to reach the root path and then reach the same endpoint as the English Readme.
* *Reordered the READMEs list (on the first lines), as it says it's listed alphabetically, so in order to still be listed alphabetically in French I had to change the order.*

### What should a reviewer concentrate their feedback on?

- [x] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:  @Aakash-Raj-2001

### CODE REVIEW

**Comment by BatoolMM** [comment]
Amazing, thank you @Aakash-Raj-2001! Let me now once it's ready for review!

**Comment by Aakash-Raj-2001** [comment]
I guess its ready for review ..You can review it and do the needful asap :) @BatoolMM

**Comment by BatoolMM** [comment]
Thank you @Aakash-Raj-2001 🎉🎉 - I've added your name to the contributors! I will also look for reviewers but let me know if you know anyone who can review it - thank you gain!

**Comment by Aakash-Raj-2001** [comment]
> Thank you @Aakash-Raj-2001 🎉🎉 - I've added your name to the contributors! I will also look for reviewers but let me know if you know anyone who can review it - thank you gain!

Hey @BatoolMM . I know one guy who can review this PR...I can tag him here @aniketh-varma :)

**Comment by Aakash-Raj-2001** [comment]
> @Aakash-Raj-2001 can you suggest a French speaking reviewer to review this PR?

@malvikasharan  Idon't know any reviewer .So sorry :(

**Comment by malvikasharan** [comment]
@SamGuay Not sure if you are active on this repo, but if you are, can I ask you to help with this PR please?

**Comment by SamGuay** [comment]
Yes, I'll review it, didn't see it before!

**Review by SamGuay — APPROVED** [review]
Had to refactor a lot, so I edited myself the file. Now ready to be merged.

**Pull request merged**
