### PR TITLE
[QuickFix] Add youtube links to collaboration cafe page

### PR DESCRIPTION
**Pull request by KirstieJane**
### Summary

Doesn't close an open issue

Added the youtube links to the collaboration cafe overview and schedule page.

### List of changes proposed in this PR (pull-request)

* Added youtube links 📽 

### What should a reviewer concentrate their feedback on?

- [ ] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hey @allcontributors bot - please can we add @orchid00 for ideas?

**Comment by orchid00** [comment]
Thank you

**Comment by malvikasharan** [comment]
#710 is redundant with this. I will close that.

**Comment by KirstieJane** [comment]
@malvikasharan - I'm so sorry for missing your PR in #710 🤦‍♀.

Can you give this a review and click merge if it looks ok?

**Comment by malvikasharan** [comment]
No problem at all. Those were the missing YouTube links from September, you would have needed to add the one from October anyway. :)

**Pull request merged**
