### PR TITLE
remove unnecessary comments

### PR DESCRIPTION
**Pull request by dpdong19**
fixes issue #2506

### CODE REVIEW

**Review by harisood — APPROVED** [review]
Looks great @dpdong19 , I think we're ready to merge

**Comment by aleesteele** [comment]
Congratulations on your first pull request, @dpdong19! So happy to have you here and with _The Turing Way_ community, and thanks for joining us during CarpentryCon.

We would love if you stayed in touch with us through [Slack](https://tinyurl.com/jointuringwayslack), [Twitter](twitter.com/turingway), or right here in the Github repo. Hope to see you in one of our community calls (which happen on a weekly basis: [you can find more info here](https://hackmd.io/@turingway/demo-intro).

I'm also going to tag you with all-contributors-bot now, to make sure that you're added to the [Contributors table](https://github.com/alan-turing-institute/the-turing-way#contributors). Congratulations again on making your first pull request, and merging it into the repo!

**Comment by aleesteele** [comment]
@all-contributors-bot please at @dpdong19 for bugs

**Comment by aleesteele** [comment]
@all-contributors please add @dpdong19 for bugs

**Pull request merged**
