### PR TITLE
[Ready for review] Intro slides for book dash

### PR DESCRIPTION
**Pull request by rainsworth**
### Summary

This pull request includes the (1st draft) of the PDF slides for the introduction to the book dash.

### List of changes proposed in this PR (pull-request)

* Intro slides added to workshops/book_dash

### What should a reviewer concentrate their feedback on?

- [x] Is there anything missing that should be added?
- [x] Anything that's overkill that should be removed?

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by pherterich** [comment]
Nice one, wondering if some of the detailed reproducibility stuff can be left out to save time. They could read that part of the book and fix typos and style if they are really interested :wink: 
One of the things that should go in here or is the follow up (not sure what's best) is how we get from this to some group building and the group meeting can really just be assigning one/two of us as primary helpers/ sounding boards to them based on skills and what they are trying to tackle? Probably should be separate, but have we assigned that as a task to one of us? Suggestions @rosiehigman @KirstieJane

**Comment by rainsworth** [comment]
Thanks @pherterich! Good call on removing some of the details on reproducibility.

Are there any other types of contributions we can highlight? So far:
* Proofread existing chapters (check for typos, grammar, links, etc.)
* Add further information to an existing chapter
* Suggest topics for new chapters (particularly if you can write them!)
* Review [Ready to review] pull requests
* Contribute to discussion [WIP] pull requests and issues
* Submit a case study or your tips and tricks for reproducible research via our Google submission form (link in README).
* Checklists
* Let us know if you are struggling with contributing in any way so that we can improve our Contributing Guidelines!

Will highlight "good first issues" and other tags when discussing issues.

Anything else I should add/remove? @rosiehigman  

@KirstieJane suggested reformating/separating the sections of the chapters (like the reproducibility chapter) and to emphasise that a chapter can be 3 paragraphs (which should help lower the barrier for folks to start writing a new chapter).

We'd like to encourage around 1/3 of the group to write new material, 1/3 to focus on editing existing material, and 1/3 on more out of the box endeavours!

We should also make a book dash mcr label for issues and a hackmd.

Perhaps we should highlight our main goals of the dash

**Comment by rainsworth** [comment]
I've made a hackmd for manchester book dash: http://bit.ly/book-dash-mcr

**Comment by rosiehigman** [comment]
That list looks pretty good, do we have some case studies already in the Google form which people could write up during the dash?
Good idea re: the HackMD, can we put the link to that in the slides?

**Comment by rainsworth** [comment]
@pherterich @rosiehigman updated slides are [here](https://github.com/alan-turing-institute/the-turing-way/blob/6efe1322e4eeab41b99fb3fadf65cc2ee41b9573/workshops/book-dash/RA_IntroBookDashMCR.pdf)

**Comment by pherterich** [comment]
No case studies in our form yet :cry:

**Pull request merged**
