### PR TITLE
[WIP] Machine learning chapter

### LINKED ISSUE #476: Update Github Issue Templates
### Summary

This issue will update the Github issue templates options one has when opening a new issue.
 

The user will have options for opening specific types of issues such as [NEW-CHAPTER] etc.  

### What needs to be done?

- [ ] Move templates that already exist in `chapters/CHAPTER_ISSUE_TEMPLATE.md` and `chapters/CHAPTER_TEMPLATE.md` to `.github/`

### PR DESCRIPTION
**Pull request by informationcake**
### Summary

Best practises for reproducible machine learning projects. Examples of workflows with test data. Tips/tricks for pipelines and python modules to help with reproducibility. 

Fixes #476  

### What should a reviewer concentrate their feedback on

- [ ] Proof-reading
- [ ] Sub-section ideas

### Acknowledging contributors

By submitting this pull request I confirm that:

- [x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by rainsworth** [comment]
@all-contributors please add @informationcake for doc

**Comment by rainsworth** [comment]
@all-contributors please add @jmoldon for doc

**Comment by rainsworth** [comment]
@all-contributors please add @tallamjr for doc

**Comment by rainsworth** [comment]
@all-contributors please add @joe-fennell for doc

**Comment by tallamjr** [comment]
As this PR is due to be merged to `alan-turing-institute/the-turing-way:machine_learning` branch, is it OK I go ahead with the merge, such that @joe-fennell, @jmoldon, @informationcake and myself can then continue to work from our own independent forks now that the book dash/sprint is over?

Having said that, I am happy to continue development at `informationcake/the-turing-way:machine_learning` if it's simpler

**Comment by rainsworth** [comment]
Hi @tallamjr - yes please go ahead and merge and work in the ```alan-turing-institute/the-turing-way:machine_learning``` branch! Thanks & sorry for the delayed response!

**Pull request merged**
