### PR TITLE
Tag curated chapters for the data study group

### LINKED ISSUE #2018: Chapter curation for data study group
### Summary

* We will post the chapter links that we would like DSG to participants to use

### What needs to be done?

- [ ] @DaisyParry and @malvikasharan are curating this
- [ ] Add detailed tag in the chapter

---

### PR DESCRIPTION
**Pull request by malvikasharan**
### Summary

Fixes #2018 

* We are tagging a few chapters for Data Study Group that we can share with a single link

### List of changes proposed in this PR (pull-request)

* Add this sentence at the end of the chapters that we want DSG participants to read: 
```
***Chapter Tags**: This chapter is curated for the `Turing Data Study Group` (`turing-dsg`).*
```
* Check with @DaisyParry and @EKaroune if they look ok.

### What should a reviewer concentrate their feedback on?

- [x] Everything looks ok?

### Acknowledging contributors

- [x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by malvikasharan** [comment]
@EKaroune and @DaisyParry if you are happy with this simple solution at the moment, can you please approve and merge this?

**Comment by DaisyParry** [comment]
Hey @malvikasharan , The list of chapters looks great. Would I count as a contributor here who needs to go on the list? Thanks

Hey @malvikasharan , The list of chapters looks great. Would I count as a contributor here who needs to go on the list? Thanks - if not will go ahead and close :D

**Comment by malvikasharan** [comment]
You are absolutely a contributor here. Let me already add you.
@all-contributors please add @DaisyParry for content.

**Comment by malvikasharan** [comment]
@all-contributors please add @DaisyParry for content

**Comment by DaisyParry** [comment]
> @malvikasharan
> 
> I've put up [a pull request](https://github.com/alan-turing-institute/the-turing-way/pull/2044) to add @DaisyParry! 🎉

Thanks so much @malvikasharan <3

**Comment by malvikasharan** [comment]
I will leave it for @EKaroune to approve and merge this 🙌
Daisy, you can then use this link to share in DSG network/docs: "https://the-turing-way.netlify.app/search.html?q=turing-dsg#" (the search tag is 'turing-dsg' which I hope will be more uniquely found in the chapter you have curated.

**Review by EKaroune — APPROVED** [review]
Looks great!

**Comment by DaisyParry** [comment]
> I will leave it for @EKaroune to approve and merge this 🙌
> Daisy, you can then use this link to share in DSG network/docs: "https://the-turing-way.netlify.app/search.html?q=turing-dsg#" (the search tag is 'turing-dsg' which I hope will be more uniquely found in the chapter you have curated.

Thanks so much @malvikasharan ! We have added this to our PI docs and it works amazing - what a resource!!!

**Pull request merged**
