### PR TITLE
[WIP]: Adding a searchbar

### PR DESCRIPTION
**Pull request by gkiar**
### Summary

Will eventually add a search bar/button and address #472 

### List of changes proposed in this PR (pull-request)

* This has been addressed for now in Jupyter-book directly (https://github.com/jupyter/jupyter-book/pull/196). Once merged there, this PR will be updated.

By submitting this pull request I confirm that:

- [ ] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).

### CODE REVIEW

**Comment by rainsworth** [comment]
@all-contributors please add @gkiar for doc

**Comment by rainsworth** [comment]
@all-contributors please add @gkiar for review

**Comment by malvikasharan** [comment]
Hey @gkiar, I followed your PR on Jupter-book. Looks like you did an amazing amount of work there and waiting for a few last tweaks to add. Do you want to have a look at that, in case that's something you would still be interested in?

**Comment by gkiar** [comment]
HI @malvikasharan ! Thanks for following up. The hanging point for the PR there is a lightweight JS library for modals rather than adding dependency to bootstrap. I found one, here: https://micromodal.now.sh/.

I've done a world-class bad job at finishing this, as I've been jumping between my extracurricular projects and trying to finish up my Ph.D. If anyone felt compelled to make the modifications, they should absolutely feel free to do so. Otherwise, continue poking me whenever it is of interest and I will _eventually_ be able to make it the top of my stack. Sorry about my tardiness, and thanks for reaching out  ☹️

**Comment by malvikasharan** [comment]
Hi @gkiar, since the search option is available in netlify and looks like Jupyterbook, has been using it already (feature exists in The Turing Way too: https://the-turing-way.netlify.app/search.html), I wonder if this PR is ok to close here?

**Comment by gkiar** [comment]
Yep- Sorry for not circling back before that happened on its own 😓

**Comment by malvikasharan** [comment]
No worries! Just cleaning up some PRs 👍

**Pull request closed without merging**
