### PR TITLE
testing margin-caption

### PR DESCRIPTION
**Pull request by da5nsy**
### Summary

Fixes #<NUM>

*Lorem ipsum dolor sit amet, consectetur adipiscing.*

### List of changes proposed in this PR (pull-request)

* *Lorem ipsum dolor sit amet, consectetur adipiscing.*
* *Lorem ipsum dolor sit amet, consectetur adipiscing.*

### What should a reviewer concentrate their feedback on?

- [ ] *Lorem ipsum dolor sit amet, consectetur adipiscing.*
- [ ] Everything looks ok?

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
- [ ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file:

### CODE REVIEW

**Comment by bsipocz** [comment]
oh, wow, I haven't messed up a rebase this magnificently for a long time :)

**Comment by bsipocz** [comment]
I'm not sure what the purpose of this test was, but I suppose this is now cleaned up and put on top of main.

**Comment by da5nsy** [comment]
This PR was to test https://github.com/executablebooks/jupyter-book/pull/1679#issuecomment-1079822114
(in the days before I was able to do local tests...)

**Comment by bsipocz** [comment]
Great. It's good to do some #closember type triaging then :)

**Comment by da5nsy** [comment]
Yup! I thought I'd closed this one already 😅

**Pull request closed without merging**
